### ISSUE TITLE
使用流程是否可以再详细一些？

### ISSUE THREAD

**Issue by lkun** [Dromara/soul#10]
目前光看代码，还是有点晕，能否提供一个实践性的例子？比如由客户端发起请求，先经过ng，ng再转发到soul-gateway，现在没有办法知道ng怎么到达soul-gateway的。

**Comment by yu199195** [comment]
直接http访问soul的，ng只是用来代理soul的集群

**Comment by dlhf** [comment]
divide插件多层目录，method直接写路径名称就好了。。。test/demo,代码就对应@RequestMapping("/test/demo")，0.0
