### ISSUE TITLE
support custom parameters in sofa plugin

### ISSUE THREAD

**Issue by tydhot** [dromara/soul#1001]
If sofa need generic invoke with custom parameters, it is different with Dubbo, it need  to construct a GenericObject.So this operation is also needed in sofa plugin.
https://www.sofastack.tech/projects/sofa-rpc/generic-invoke/

**Comment by wuudongdong** [comment]
Please assign to me. Thanks

**Comment by tydhot** [comment]
> Please assign to me. Thanks

good luck
