### ISSUE TITLE
What is the performance of Soul?

### ISSUE THREAD

**Issue by jjzwu** [dromara/soul#1023]
## Question

// your question here;

What is the performance of Soul? Is there any pressure test data？The performance of the Dubbo interface is poor when it is undertested。

**Comment by yu199195** [comment]
can you  find out the reason for Dubbo's poor performance？ can you provider test data？ not ask us

**Comment by jjzwu** [comment]
When I pressed the Dubbo interface, the standalone machine reached 1W QPS. When I pressed the same port through the Soul, the single player only had 500 QPS.
