### ISSUE TITLE
DataSyncConfiguration have some remark error

### ISSUE THREAD

**Issue by Silencesk** [dromara/soul#1024]
## Describe the bug

i found `org.dromara.soul.admin.config.DataSyncConfiguration` have some remark error, the (default strategy) has two. it can probably mislead user.
![image1](https://user-images.githubusercontent.com/4735494/105153902-f1a52300-5b43-11eb-9845-393a9415ae54.png)
![image2](https://user-images.githubusercontent.com/4735494/105154112-287b3900-5b44-11eb-8ace-949a9787758a.png)

## Environment

- Soul version(s): [2.2.1]

## Debug logs

<details>

</details>

**Comment by Silencesk** [comment]
according to the code, websocketListener is default.

**Comment by dengliming** [comment]
Can you correct the comment?

**Comment by Silencesk** [comment]
i can
