### ISSUE TITLE
About dubbo request parameter

### ISSUE THREAD

**Issue by hebaceous** [dromara/soul#1026]
##### Dubbo api
```
public interface API {
  public void someMethod(Integer id, String name)
}
```
##### Request JSON (The document says that parameters should be passed like this)
```
{
    "id" : 123,
    "name" : "Alex"
}
```
But actually I can do it with `{"id1":123,"name2":"Alex"}`.json key name is useless
But I can't pass parameters like this `{"name":"Alex","id":123}`. because it requires `id` before `name`

#### Solution
parameters are treated as json array. like this `[123,"Alex"]`. no named and ordered

**Comment by KevinClair** [comment]
When parameters are treated as json array, how to recive java object.

**Comment by hebaceous** [comment]
> When parameters are treated as json array, how to recive java object.

[123,"Alex",{"id":231,"name":"ABC"},[{"age":22}]]
