### ISSUE TITLE
How was the Soul performance？

### ISSUE THREAD

**Issue by jjzwu** [dromara/soul#1027]
## Question

// your question here;

When I pressed the Dubbo interface, the standalone machine reached 1W QPS. When I pressed the same Dubbo interface through the Soul, the single player only had 500 QPS. I'd like to know the official pressure test data。

**Comment by yu199195** [comment]
what version？  what config？   Machine configuration?   Thread configuration?  

What's the point of your question?

**Comment by yu199195** [comment]
Our pressure test performance loss was probably less than 10 percent
