### ISSUE TITLE
NullPointerException happend with  nacos data-sync 

### ISSUE THREAD

**Issue by plutokaito** [dromara/soul#1030]
## Describe the bug
when i start admin with nacos data-sync which one has no plugins, no selectors and so on;  on other way , this is a new application;  and now i start bootstrap, there is npe happend.
![image](https://user-images.githubusercontent.com/7955473/105347342-baa53f00-5c21-11eb-9f14-b1afe8611a93.png)
 

## Environment

- Soul version(s): 2.2.1

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
can you fix it？ or ask how to config nacos befer soul。。。

**Comment by plutokaito** [comment]
> can you fix it？ or ask how to config nacos befer soul。。。

ok，
1. i will ask someone how to config nacos  before soul; 
2.i will confirm in the right config, is NullPointerException happen,
3.if  it happened,  i try to fix it.

**Comment by Rookie45** [comment]
> > can you fix it？ or ask how to config nacos befer soul。。。
> 
> ok，
> 
> 1. i will ask someone how to config nacos  before soul;
>    2.i will confirm in the right config, is NullPointerException happen,
>    3.if  it happened,  i try to fix it.


I also met this problem，through debugging, it is found that Nacos mechanism is the cause. The server（soul-admin）config must change before nacos recording，so you should change plugin，selector and rule configs on admin web page，then this exception will disappear.  Hope to help you.

**Comment by plutokaito** [comment]
lt refer  to [config nacos](https://www.jianshu.com/p/8294289145a7) to fix it.
