### ISSUE TITLE
soul-admin & soul-dashboard  new features about plugins and resources

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#1034]
## Feature Request
1.Add a resource management menu, mainly add, delete, edit and query the buttons and menus of all pages
2.Remove menu User, Role, Resource to User Management
3.Remove menu Plugin, PluginHandler,Authentication,Metadata,Dictionary to Basic Configuration
4. When adding a new plugin, add the corresponding button to resource
5. Put the newly added resource menu to permission control
6. When adding and deleting plugins, resources and permissions must be linked (addition and deletion of resources, binding and unbinding of permissions)

**Comment by fengzhenbing** [comment]
get it

**Comment by nuo-promise** [comment]
## Sequence Diagram of user resource permissions
![image.png](https://cdn.nlark.com/yuque/0/2021/png/2312798/1611725185234-8885d623-543a-44a4-b614-c67abd7a0555.png#align=left&display=inline&height=658&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1316&originWidth=1908&size=203065&status=done&style=none&width=954)
![image.png](https://cdn.nlark.com/yuque/0/2021/png/2312798/1611727441378-92137759-0c95-4410-b34d-5ff7ef494eeb.png#align=left&display=inline&height=679&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1358&originWidth=1986&size=363730&status=done&style=none&width=993)
## Query the resource list by page
### **Interface Type**

- HTTP/HTTPS
### **Descriptio**

- Click resource query to obtain resource information.
### **Request method**

- GET
- /resource

**Sample request parameters**
```java
localhost:9095/resource
```
### **Response parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| code | int | Yes | Status Code |
| message | string | Yes | Response description |
| data | Object | 否 | Custom message body|



### **data entity List<ResourceVO> -> ResourceVO**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| id | string | Yes | Resource id |
| parentId | string | Yes | Resource parent id |
| title | string | Yes | Resource title |
| name | string | Yes | Resource Name |
| url | string | Yes | Route URL |
| component | string | Yes | The name of the component used by the page. |
| resource_type | int | Yes | Resource Type 0: Main Menu 1: submenu 2: function button |
| sort | int | Yes | Menu display sorting |
| icon | string | Yes | Menu display icon |
| is_leaf | int | Yes | Is leaf node 0 not 1 yes|
| is_route | int | Yes | Whether it is a route (extended use) 1: Yes 0: No |
| perms | string | Yes | Permission settings for Page child controls: sys:user:add (new feature)/sys:user:edit (edit feature) |
| status | int | Yes | Resource status 1 is valid. 0 is invalid. |
| dateCreated | string | Yes | Role creation time|
| dateUpdated | string | Yes | Role creation time |



**Sample response parameters**
```java
{
    "code": 200,
    "message": "query success",
    "data": {
        "page": {
            "currentPage": 1,
            "prePage": 1,
            "nextPage": 2,
            "pageSize": 12,
            "offset": 0,
            "totalPage": 14,
            "totalCount": 157
        },
        "dataList": [
            {
                "id": "1346775491550474240",
                "parentId": "",
                "title": "SOUL.MENU.PLUGIN.LIST",
                "name": "plug",
                "url": "/plug",
                "component": "PluginList",
                "resourceType": 0,
                "sort": 0,
                "icon": "dashboard",
                "isLeaf": false,
                "isRoute": 0,
                "perms": "",
                "status": 1,
                "dateCreated": "2021-01-06 05:07:54",
                "dateUpdated": "2021-01-07 18:34:11"
            }
        ]
    }
}
```


## Add a resource interface
### **Interface Type**

- HTTP/HTTPS
### **Description**

- • Add resources
### **Request method**

- POST
- /resource
### **Request parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| parentId | string | Yes | Logon username|
| title | string | Yes | Resource tit|
| name | string | Yes | Resource Name|
| url | string | Yes | Route URL|
| component | string | Yes | The name of the component used by the page.|
| resource_type | int | Yes | Resource Type 0: Main Menu 1: submenu 2: function button|
| sort | int | Yes | Menu display sorting|
| icon | string | Yes | Menu display icon|
| is_leaf | int | Yes | Is leaf node 0 not 1 yes|
| is_route | int | Yes | Whether it is a route (extended use) 1: Yes 0: No|
| perms | string | Yes | Permission settings for Page child controls: sys:user:add (new feature)/sys:user:edit (edit feature)|
| status | int | Yes | Resource status 1 is valid. 0 is invalid|

**
**Sample request parameters**
```java
localhost:9095/resource
```
### **Response parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| code | int | Yes | Status Code |
| message | string | Yes | Response description|
| data | Object | 否 | Custom message body|



**Sample response parameters**
```java
{
    "message": "add success!",
    "code": 200,
    "data": 1,
}
```
## Edit resources
### **Interface Type**

- HTTP/HTTPS
### **Description**

- • Obtain resource information based on user ID
### **Request method**

- GET
- /resource/{id}
### **Request parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| id | string | Yes | Resourceid |



**Sample response parameters**
```java
http://localhost:9095/resource/xxxxxxx
```


### **Response parameters ResourceVO
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| id | string | Yes | Resource Id |
| parentId | string | Yes | Logon username|
| title | string | Yes | Resource tit|
| name | string | Yes | Resource Name|
| url | string | Yes | Route URL|
| component | string | Yes | The name of the component used by the page.|
| resource_type | int | Yes | Resource Type 0: Main Menu 1: submenu 2: function button|
| sort | int | Yes | Menu display sorting|
| icon | string | Yes | Menu display icon|
| is_leaf | int | Yes | Is leaf node 0 not 1 yes|
| is_route | int | Yes | Whether it is a route (extended use) 1: Yes 0: No|
| perms | string | Yes | Permission settings for Page child controls: sys:user:add (new feature)/sys:user:edit (edit feature)|
| status | int | Yes | Resource status 1 is valid. 0 is invalid|
| dateCreated | string | Yes | Resource creation time|
| dateUpdated | string | Yes | Role update time|

**Sample response parameters**
```java
{
    "code": 200,
    "message": "detail success",
    "data": {
        "id": "1347046566244003840",
        "parentId": "1346777449787125760",
        "title": "SOUL.BUTTON.SYSTEM.SYNCHRONIZE",
        "name": "",
        "url": "",
        "component": "",
        "resourceType": 2,
        "sort": 3,
        "icon": "",
        "isLeaf": true,
        "isRoute": 0,
        "perms": "system:plugin:modify",
        "status": 1,
        "dateCreated": "2021-01-07 13:05:03",
        "dateUpdated": "2021-01-17 12:06:23"
    }
}
```
## After editing the resource information saved by the user
### **Interface Type**

- HTTP/HTTPS
### **Description**

- • Save the resource information after editing the resource information.
### **Request method**

- PUT
- /resource/{id}
### **Request parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| parentId | string | Yes | Logon username|
| title | string | Yes | Resource tit|
| name | string | Yes | Resource Name|
| url | string | Yes | Route URL|
| component | string | Yes | The name of the component used by the page.|
| resource_type | int | Yes | Resource Type 0: Main Menu 1: submenu 2: function button|
| sort | int | Yes | Menu display sorting|
| icon | string | Yes | Menu display icon|
| is_leaf | int | Yes | Is leaf node 0 not 1 yes|
| is_route | int | Yes | Whether it is a route (extended use) 1: Yes 0: No|
| perms | string | Yes | Permission settings for Page child controls: sys:user:add (new feature)/sys:user:edit (edit feature)|
| status | int | Yes | Resource status 1 is valid. 0 is invalid|



**Sample request parameters**

```java
http://localhost:9095/resource/xxxxxxx
```
### **Response parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| code | Integer | Yes | Status Code |
| message | string | Yes | Error message|
| data | Object | 否 | Business data |

**Sample response parameters**

**
```java
{
	"code": 200,
	"msg":"update success",
	"data":null/xxx
}

```
## Delete resources
### **Interface Type**

- HTTP/HTTPS
### **Description**

- • Delete resources in batches
### **Request method**

- DELETE
- /resource/batch

**Request parameters**

|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| ids | List | Yes | Resource ids |



**Sample response parameters** 
{
    "message": "delete success!",
    "code": 200,
    "data": 1
}**
```java
[xxxx,xxxxx,xxxxx] Resoruce ID
```
### **Response parameters**
|Parameter | Type | Required | Description |
| :--- | :--- | :--- | :--- |
| code | int | Yes | Status Code |
| message | string | Yes | Response description
| data | Object | No | Response descriptios|



**Sample response parameters**
```java
{
    "message": "Delete success!",
    "code": 200,
    "data": 1
}
```
