### ISSUE TITLE
throw NullPointerException  when synchronizing data with nacos

### ISSUE THREAD

**Issue by xuziyang** [dromara/soul#1045]
## Describe the bug
When soul-bootstrap starts，it throws an exception
![image](https://user-images.githubusercontent.com/8465969/105619998-f400c900-5e32-11eb-8614-600d6c2efaab.png)

## Environment

Soul version(s): master

## Steps to reproduce
1. When the data of auth,plugin,rule,selector,meta_data, any one of them is not exist
2. Modify soul-bootstrap's configuration file application-local.yml to configure the synchronization policy as nacos.
3. start soul-bootstrap

**Comment by plutokaito** [comment]
u can config like this, [nacos sync config](https://www.jianshu.com/p/8294289145a7), Hope help u.
