### ISSUE TITLE
about nacos-sync-data, maybe some code is redundant.

### ISSUE THREAD

**Issue by Zhoutzzz** [dromara/soul#1049]
## Question

// your question here;
when I use nacos-sync-data, if I change auth data at admin, then changed data will be send NaosDataChangedListener#updateAuthMap method invoke, but in this method,the configInfo param is old data, and the AUTH_MAP also old, there old data change equal no change, so, what use is this code.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
![image](https://user-images.githubusercontent.com/42396616/105631888-a5cbe400-5e8b-11eb-8f3a-1aeb0eedb6e7.png)

**Comment by nuo-promise** [comment]
> ## Question
> // your question here;
> when I use nacos-sync-data, if I change auth data at admin, then changed data will be send NaosDataChangedListener#updateAuthMap method invoke, but in this method,the configInfo param is old data, and the AUTH_MAP also old, there old data change equal no change, so, what use is this code.
> 
> Please pay attention on issues you submitted, because we maybe need more details.
> If no response anymore and we cannot reproduce it on current information, we will **close it**.
> ![image](https://user-images.githubusercontent.com/42396616/105631888-a5cbe400-5e8b-11eb-8f3a-1aeb0eedb6e7.png)

Personally, I think it is important to ensure data synchronization between admin clusters.
