### ISSUE TITLE
selector config values vanished when reloading the admin page

### ISSUE THREAD

**Issue by strawberry-crisis** [dromara/soul#1057]
## Describe the bug
selector data lost when reloading the admin page

## Environment

- Soul version(s):  2.2.1

## Steps to reproduce
reload the admin browser page and click the "modify" button of the selector

![image](https://user-images.githubusercontent.com/13709330/105725942-7e951580-5f64-11eb-8100-e264863961c3.png)

the values filled in "host", "protocol", "ip:port" vanished

## Expected behavior
data recorded should be displayed correctly

**Comment by nuo-promise** [comment]
> ## Describe the bug
> selector data lost when reloading the admin page
> 
> ## Environment
> * Soul version(s):  2.2.1
> 
> ## Steps to reproduce
> reload the admin browser page and click the "modify" button of the selector
> 
> ![image](https://user-images.githubusercontent.com/13709330/105725942-7e951580-5f64-11eb-8100-e264863961c3.png)
> 
> the values filled in "host", "protocol", "ip:port" vanished
> 
> ## Expected behavior
> data recorded should be displayed correctly

which plugin page?

**Comment by strawberry-crisis** [comment]
I found that when Selector configuration modal loads, it will detect whether the endpoint is connectable. If the endpoint can not be connected it will clear the configs saved before. Enhancements may be applied.

**Comment by nuo-promise** [comment]
> I found that when Selector configuration modal loads, it will detect whether the endpoint is connectable. If the endpoint can not be connected it will clear the configs saved before. Enhancements may be applied.

/soul-client/springmvc-register init services
![image](https://user-images.githubusercontent.com/46160170/107033849-da775e00-67f0-11eb-8edc-f8f978c282a4.png)

UpstreamCheckService -> clear handler info
![image](https://user-images.githubusercontent.com/46160170/107034305-7bfeaf80-67f1-11eb-9fea-5d74b93d7f66.png)

The service starts registering with Admin, which then splices the connection information of the registry, as you can see on the web page. This connection information is cleared if the service is offline.
