### ISSUE TITLE
Add test case for soul-admin

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#1071]
## Add test case for soul-admin

Task List:

- [ ] ResourceController & ResourceMapper & ResourceService @0x12FD16B 
- [x] RoleService & RoleMapper & RoleController @Wincher 

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by wolf2s** [comment]
ResourceController & ResourceMapper & ResourceService

**Comment by Wincher** [comment]
RoleService & RoleMapper & RoleController

**Comment by 0x12FD16B** [comment]
I want to participate ResourceController & ResourceMapper & ResourceService test cases developing task.

**Comment by dengliming** [comment]
Done. Thanks to @0x12FD16B @Wincher
