### ISSUE TITLE
是否考虑SPI化，

### ISSUE THREAD

**Issue by owen200008** [Dromara/soul#109]
整体SPI化
1. 代码架构化，业务由接入方实现
2. 交互协议SPI化，由具体业务层（公司）实现自己的交互协议接入，比如错误返回，每个公司已经存在的协议不可能因为要接入网关而修改
3. 前置过滤器的SPI化，基于业务编排过滤器（这部分不需要接入admin，基于配置加载即可）
4. plugin的SPI化，减少写代码出错的概率，尽量一个插件只使用自己模块的代码

**Comment by owen200008** [comment]
使用类似dubbo的模式
1. 按需加载
2. 代码模块化

**Comment by yu199195** [comment]
有考虑，你有什么好的代码可以pr上来，我们一起来看看
