### ISSUE TITLE
Cannot edit authentication details

### ISSUE THREAD

**Issue by SpaceEmpire** [dromara/soul#1094]
## Describe the bug

auth_path data were not show，cannot edit

## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

![18_05_23__02_05_2021](https://user-images.githubusercontent.com/11566211/107021324-f540d700-67de-11eb-9a0b-7986c144a2da.jpg)
![18_06_15__02_05_2021](https://user-images.githubusercontent.com/11566211/107021333-f7a33100-67de-11eb-8a93-179ca7c65fc7.jpg)

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
can you fix it?

**Comment by SpaceEmpire** [comment]
> can you fix it?

let me try

**Comment by nuo-promise** [comment]
> > can you fix it?
> 
> let me try

I will fix it

**Comment by SpaceEmpire** [comment]
> > > can you fix it?
> > 
> > 
> > let me try
> 
> I will fix it

ths

**Comment by fengzhenbing** [comment]
Fixed
