### ISSUE TITLE
建议：路由配置策略与 负载均衡可参考springcloud zuul来实现

### ISSUE THREAD

**Issue by lilybj2009** [Dromara/soul#111]
Http API 网关，最重要的两个核心功能是Http代理转发 与 负载均衡。
看了Soul目前的路由配置实现，比较被动繁琐。
如果微服务架构是基于springcloud + eureka + Soul , 那么Soul的路由功能无法做到服务自动发现。
前端（APP或H5）请求头还需要传递module，对已经上线的springcloud项目从zuul网关迁移到Soul网关非常不友好。
一点建议：路由配置策略与 负载均衡可参考springcloud zuul来实现。
另外：API网关面向外网，一般都重点支持Http协议，可以专一做好Http代理转发这一块。贪多会消化不良。
如果Soul在功能上与Zuul类似，高并场景下QPS与平均响应延迟比Zuul强很多，那么Soul取代Zuul 网关的日子就不远了。
推荐gateway中的模型设计：
![image](https://user-images.githubusercontent.com/18653352/67136960-a3c6ae80-f260-11e9-8d0f-998dcf827dd6.png)

**Comment by yu199195** [comment]
感谢建议，我们在重新改造，过段时间会重新发布全新的版本

**Comment by yufewang** [comment]
hi，这个特性发布了么？
