### ISSUE TITLE
Questions about IP + Port register

### ISSUE THREAD

**Issue by moonyang** [dromara/soul#1113]
The springboot project uses http to register, and the registration is successful. When the project port is not completely started, the check timing task is executed, and the port is found to be blocked, so the configuration information of the ip is deleted. check the url=XXXX:8080 is fail, how to solve this problem?

**Comment by yu199195** [comment]
pls in english

**Comment by moonyang** [comment]
client message  
[20210220 16:21:09.652] | [INFO] | [PC-201901071437] | [pool-1-thread-1] | [o.d.s.c.s.i.SpringMvcClientBeanPostProcessor] | --> http client register success
soul admin message   
2021-02-20 16:21:11.557 ERROR 25096 --- [upstream-task-6] o.d.s.a.s.impl.UpstreamCheckService      : check the url=XXXX:8080 is fail

**Comment by yu199195** [comment]
1. you can close checked 
2.  why can not checked fail？

**Comment by moonyang** [comment]
if i close checked, If the node is already offline, it will not be alive and there will be traffic to the node。

**Comment by 512222607** [comment]
i got the same problem
in org.dromara.soul.admin.service.impl.UpstreamCheckService class,i add a zombie set.
it contains the faild upstream and to make the fail upstream checkd more times.
the faild upstream will be removed from the set after a certain number of times.
