### ISSUE TITLE
弱弱问个注入的问题

### ISSUE THREAD

**Issue by xiaoluozai** [Dromara/soul#112]
大神，找了很久，没找到SoulWebHandler的List<SoulPlugins>参数的在哪里注入，能否指导指导
![image](https://user-images.githubusercontent.com/24823537/67155372-823cf400-f340-11e9-86ec-6c41c5ccf8a8.png)

**Comment by yu199195** [comment]
只是spring的参数注入，在前面有很多个soul 插件的注入，这里在方法上就可以写成一个list
