### ISSUE TITLE
Add  defualt failback Impl  for Hystrix Plugin In Soul Bootstrap

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1122]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by xiaoshen11** [comment]
get it

**Comment by HoldDie** [comment]
get
