### ISSUE TITLE
Can I use soul dubbo plugin as Spring cloud gateway's filter?

### ISSUE THREAD

**Issue by ryuhi** [dromara/soul#1126]
Can I use soul dubbo plugin as Spring cloud gateway's filter? 
In my company, the gateway is Spring cloud gateway and choiced by Tech Director, and using in release environment, but I want to transform http request to dubbo RPC request, so ...

If it can be used as Spring Cloud Gateway filter, how should I do? Thanks a lot.

**Comment by yu199195** [comment]
No you cannot， maybe you must  development by youself
