### ISSUE TITLE
If the service takes a long time to start,admin checkd upstream fail,it can't be registed

### ISSUE THREAD

**Issue by 512222607** [dromara/soul#1127]
## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
can you fix it？

**Comment by dengliming** [comment]
Duplicate of [https://github.com/dromara/soul/issues/1113](https://github.com/dromara/soul/issues/1113)
