### ISSUE TITLE
#UpstreamCacheManager#根据selectorId找不到对应的UpstreamList

### ISSUE THREAD

**Issue by feiyan-affection** [dromara/soul#1128]
## Task

A clear and concise description of Task

Task List:

- [x] task1
- [ ] task2
- [ ] task3
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/27754514/109246688-a9051780-781d-11eb-86fe-6cfd7f2cad10.png">

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by yu199195** [comment]
pls in english

**Comment by feiyan-affection** [comment]
.
