### ISSUE TITLE
如何理解插件热插拔机制，新增插件还是得注解 Bean，服务还是得重启啊

### ISSUE THREAD

**Issue by xiaoluozai** [Dromara/soul#113]
我理解的热插拔，要不通过 SPI 方式加载、要不就是其他方式 load class，但我在Soul里没看到类似的实现，请问大神Soul是如何实现热插拔的（扩展文档看了几遍也看不出端倪）
谢谢！

**Comment by yu199195** [comment]
那你写了java代码不重启？比如dubbo你扩展了他的spi接口，spring实现了别人的接口，不需要重启吗

**Comment by xiaoluozai** [comment]
> 比如 dubbo 你扩展了他的 spi 接口，spring 实现了别人的接口，不需要重启吗

未来是否可以将插件用jar形式发布，扩展类加载，进一步实现热加载？

**Comment by yu199195** [comment]
3.0 规划了，只需要上次jar包到指定目录就好了

**Comment by xiaoluozai** [comment]
> 3.0 规划了，只需要上次 jar 包到指定目录就好了

期待~

**Comment by zhangcj** [comment]
期待
