### ISSUE TITLE
Modify the buildRealURL method to get query in DividePlugin

### ISSUE THREAD

**Issue by jcmob-afj** [dromara/soul#1133]
## Feature Request

Modify the buildRealURL method to get query in DividePlugin  plugin
Because now the way to get query is to do decode
If our query method does not require decode ,the resulting redirect URL will not be what we want

#### Is your feature request related to a problem? Please describe
1. The buildRealURL method in DividePlugin, Notice now the way to get query
```java
    private String buildRealURL(final String domain, final SoulContext soulContext, final ServerWebExchange exchange) {
        String path = domain;
        final String rewriteURI = (String) exchange.getAttributes().get(Constants.REWRITE_URI);
        if (StringUtils.isNoneBlank(rewriteURI)) {
            path = path + rewriteURI;
        } else {
            final String realUrl = soulContext.getRealUrl();
            if (StringUtils.isNoneBlank(realUrl)) {
                path = path + realUrl;
            }
        }
        String query = exchange.getRequest().getURI().getQuery();  //Please note that
        if (StringUtils.isNoneBlank(query)) {
            return path + "?" + query;
        }
        return path;
    }
```
2.The returned result is decode
```java
    public String getQuery() {
        if ((decodedQuery == null) && (query != null))
            decodedQuery = decode(query);
        return decodedQuery;
    }
```

#### Describe the solution you'd like
1.If my request url is with a callback :
http://127.0.0.1:9195/click?source=centent&appid=1119087595&uuid=0000CA8D-BEB6-45AB-AC6B-468272295361&callback=https%3a%2f%2fblog.csdn.net%2fcallbck%3fclickId%3d34523452345235afdadfae%26uuid%3d0000CA8D-BEB6-45AB-AC6B-468272295361

2.The final URL obtained by the DividePlugin is shown below :
http://127.0.0.1:10086/click?source=centent&appid=1119087595&uuid=0000CA8D-BEB6-45AB-AC6B-468272295361&callback=https://blog.csdn.net/callbck?clickId=34523452345235afdadfae&uuid=0000CA8D-BEB6-45AB-AC6B-468272295361

3.DividePlugin will break the integrity of URLs

#### Describe alternatives you've considered

1. getRawQuery()  replace getQuery()
```java
    private String buildRealURL(final String domain, final SoulContext soulContext, final ServerWebExchange exchange) {
        String path = domain;
        final String rewriteURI = (String) exchange.getAttributes().get(Constants.REWRITE_URI);
        if (StringUtils.isNoneBlank(rewriteURI)) {
            path = path + rewriteURI;
        } else {
            final String realUrl = soulContext.getRealUrl();
            if (StringUtils.isNoneBlank(realUrl)) {
                path = path + realUrl;
            }
        }
//        String query = exchange.getRequest().getURI().getQuery();
        String query = exchange.getRequest().getURI().getRawQuery();  // getRawQuery()  replace getQuery()
        if (StringUtils.isNoneBlank(query)) {
            return path + "?" + query;
        }
        return path;
    }
```
2.getRawQuery()
```java
    public String getRawQuery() {
        return query;
    }
```

**Comment by dengliming** [comment]
Resolved by [https://github.com/dromara/soul/pull/1134](https://github.com/dromara/soul/pull/1134)  Thanks to @jcmob-afj
