### ISSUE TITLE
Support ETCD as soul-register-center

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1147]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by strawberry-crisis** [comment]
can I try it
