### ISSUE TITLE
Support Consul as soul-register-center

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1148]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by ming4J** [comment]
> let me do this

spring-cloud-starter-consul-discovery 

For the compatibility of the project is not high fault tolerance

Personally, I’m more inclined use [this](https://github.com/rickfast/consul-client) client
