### ISSUE TITLE
Slf4j 的日志记录方式问题

### ISSUE THREAD

**Issue by xingguang2013** [Dromara/soul#115]
在需要记录 error 异常日志时，Slf4j 还不支持类似 
```java
LOGGER.error("websocket send result is exception :{}", e);
```
这种方式,打印出来的日志中无法将 `{}` 转换为异常对象 e。是由于 `LOGGER.error()` 的重载方法主要有 `public void error(String msg, Throwable t);` 和 `public void error(String format, Object arg);` 上面会调用前者，所以会导致异常信息对象不会替换 `{}`。

**Comment by yu199195** [comment]
这是个bug。下个版本修护
