### ISSUE TITLE
create dubbo api bean by JdkDynamicAopProxy,  can not get SoulDubboClient.class in ApacheDubboServiceBeanPostProcessor.postProcessAfterInitialization

### ISSUE THREAD

**Issue by plm479104792** [dromara/soul#1153]
## Describe the bug

create dubbo api bean by JdkDynamicAopProxy,  I can not get SoulDubboClient.class in ApacheDubboServiceBeanPostProcessor.postProcessAfterInitialization

## Environment
 soulVersion = 2.2.1
project:  spring-web

## Steps to reproduce
1. application.xml           
       <aop:aspect id="logintegrationaop" ref="logAdvice">
            <aop:pointcut id="logintegrationpointcut" expression="(execution(* com.aifocus.member.service.*.*(..)))" />
            
            <aop:around method="myDubboAroundAdvice" pointcut-ref="logintegrationpointcut"/>
        </aop:aspect>
    <aop:aspectj-autoproxy proxy-target-class="true">
    </aop:aspectj-autoproxy>
2. debug project
    
![image](https://user-images.githubusercontent.com/27324381/110194257-a6846c80-7e72-11eb-9e0c-129e163d6c39.png)

![image](https://user-images.githubusercontent.com/27324381/110194567-c8322380-7e73-11eb-809c-b96a161a074b.png)

## Expected behavior

I can get SoulDubboClient.class info

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by plm479104792** [comment]
![Uploading image.png…]()

**Comment by plm479104792** [comment]
![Uploading image.png…]()

**Comment by dengliming** [comment]
Thanks for reporting this issue. Can you try to fix?

**Comment by plm479104792** [comment]
> Thanks for reporting this issue. Can you try to fix?

Add an "@Inherited" annotation to the SoulDubboClient.class annotation
![image](https://user-images.githubusercontent.com/27324381/110593436-875d4600-81b6-11eb-84ca-916aed18a994.png)

**Comment by plm479104792** [comment]
![Uploading image.png…]()
can fix it

**Comment by yu199195** [comment]
can you provider pr to fix it?
