### ISSUE TITLE
配置成功了但是请求代理时一直报-106

### ISSUE THREAD

**Issue by Fieeeeee** [dromara/soul#1157]
## Describe the bug

本地启好了相关服务，但是调用代理接口时报：
详细返回 json：
{
  "code": -106,
  "message": "未能找到合适的调用url,请检查你的配置!",
  "data": null
}

查看代码感觉有可能是  
String urlPath = exchange.getAttribute(Constants.HTTP_URL);
`if (StringUtils.isEmpty(urlPath)) {
            Object error = SoulResultWrap.error(SoulResultEnum.CANNOT_FIND_URL.getCode(), SoulResultEnum.CANNOT_FIND_URL.getMsg(), null);
            return WebFluxResultUtils.result(exchange, error);
        }`
请问这个值如何塞进去呢
## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
1. please in English.
2. provide your config.
