### ISSUE TITLE
Requesting Http proxy and it returns -106

### ISSUE THREAD

**Issue by Fieeeeee** [dromara/soul#1158]
## Question

I started the admin and proxy server successfully, but it returned an error  when I sent a request to the server like:
`{
  "code": -106,
  "message": "未能找到合适的调用url,请检查你的配置!",
  "data": null
}`
here is my  configuaration:
`
spring:
  main:
    allow-bean-definition-overriding: true

soul:
  http:
    adminUrl: http://localhost:9095
    port: 9195
    contextPath: /http
    appName: proxyee
    full: false
`

I try to find the answer why this problem occured, I saw 
![image](https://user-images.githubusercontent.com/34617908/110211793-35c16c80-7ed3-11eb-9f20-106f5c62102f.png)

I think this may be the answer, please help me  to fix it or tell me how can I fix it, thanks:)

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by leohou0430** [comment]
check soul-admin divide plugin config, do you config selector and rule, if you selector conditions is uri, please use 'match' type /http/**

**Comment by Fieeeeee** [comment]
> check soul-admin divide plugin config, do you config selector and rule, if you selector conditions is uri, please use 'match' type /http/**.
> if can not work,please show your soul-admin config

![image](https://user-images.githubusercontent.com/34617908/110264622-b6c45500-7ff4-11eb-94a2-dd4b3bf7d64a.png)
![image](https://user-images.githubusercontent.com/34617908/110264697-d9ef0480-7ff4-11eb-9533-1b5bf8b3638c.png)

Here is my soul-admin config, I don't  configure anything.

**Comment by dengliming** [comment]
https://dromara.org/zh/projects/soul/quick-start-http/
