### ISSUE TITLE
rate_limiter可能会造成STW问题

### ISSUE THREAD

**Issue by Ryan12138** [Dromara/soul#116]
lua脚本中根据容量cap每次扣减1，标识可容许请求数量减一，然后将剩余数字set进缓存。此时设置的ttl时间为传入时间，导致redis key过期时间重置，但是容许数量减一，等同于速率不变，减少容量。以此循环，待容许数量为0，需等待redis key自动过期后方可使用，相当于拦截所有请求，造成STW。

**Comment by yu199195** [comment]
STW是啥。。

**Comment by Ryan12138** [comment]
> STW是啥。。

额，stop the world，比喻而已，只是觉得有点像。
假设按接口粒度配置限流，速率为2，容量为5(应该是2s内可处理5个请求的意思吧)。测试调用1s/次，应该是一直不满足限流条件的，但是当前脚本里的写法会导致每次剩余值减一，过期时间不变。最终调用5次以后剩余数为0，过期时间2s，这2s里所有该接口的请求都会被拦截(因为剩余可用请求数一直为0)，待redis key过期后才能放行。
