### ISSUE TITLE
grpc has bug

### ISSUE THREAD

**Issue by linsongGong** [dromara/soul#1165]
1.the grpc subscriber service has bug,the context_path is always null;
2.the grpc load balance is useless;

**Comment by dengliming** [comment]
Thanks for reporting this issue. We have introduced a registry center recently and will refactor this part of the code later.

**Comment by SaberSola** [comment]
Thanks for reporting this issue. we will fix it this week

**Comment by yu199195** [comment]
@SaberSola   it fix？
