### ISSUE TITLE
In the divide plugin, the realPath attribute value is empty, but the path has a value.

### ISSUE THREAD

**Issue by hackeryutu** [dromara/soul#1176]
## Question

// your question here;

In the divide plugin, the realPath attribute value is empty, but the path has a value.

In the divide plugin, the realPath attribute value is empty, but the path has a value.
![image](https://user-images.githubusercontent.com/16240260/111621103-8796ba80-8822-11eb-86c8-fb44a708f0e0.png)

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by yu199195** [comment]
whats you contextpath？

**Comment by hackeryutu** [comment]
contextPath value is /0591

**Comment by hackeryutu** [comment]
I expect the contextPath value to be /

**Comment by hackeryutu** [comment]
Why always truncate the first directory as contextpath

`  private void setSoulContextByHttp(final SoulContext soulContext, final String path) {
        String contextPath = "/";
        String[] splitList = StringUtils.split(path, "/");
        if (splitList.length != 0) {
            contextPath = contextPath.concat(splitList[0]);
        }

        String realUrl = path.substring(contextPath.length());
        soulContext.setContextPath(contextPath);
        soulContext.setModule(contextPath);
        soulContext.setMethod(realUrl);
        soulContext.setRealUrl(realUrl);
    }`

**Comment by yu199195** [comment]
you can config context-path  plugin

**Comment by hackeryutu** [comment]
I configured the handler rule in the context-path plugin as /, and the result of visiting "qa.com/0951" is "qa.com0951"

version 2.3.0-snapshot

i found code

`       Optional<String> optional = Arrays.stream(context.getPath()
                .split(handle.getContextPath()))
                .reduce((first, last) -> last);`

path is /0591
contextPath is /
split result is  empty string and "0591"

**Comment by yu199195** [comment]
whats  you  real uri  is  ?

**Comment by yu199195** [comment]
if order module have /0591,  and pay module have /0591,  whats router?

**Comment by hackeryutu** [comment]
I can route based on the host attribute in the http header

**Comment by hackeryutu** [comment]
Thank you for solving the problem！
