### ISSUE TITLE
Can soul be deployed in k8s?

### ISSUE THREAD

**Issue by lesliedou** [dromara/soul#1184]
Can soul be deployed in k8s?

**Comment by yu199195** [comment]
yes， spring-boot  can be deployed in k8s？

**Comment by lesliedou** [comment]
i want to know how to set gateway ipaddress?

> yes， spring-boot can be deployed in k8s？

**Comment by lesliedou** [comment]
bootstrap gateway , how to set synchronized address？ because this ip is dynamic？

**Comment by dengliming** [comment]
May I ask how your K8s cluster handles calls across service namespace. As far as I know,  K8s can use kube-dns to resolve cross-namespace calls. So you can use domain as your address.
