### ISSUE TITLE
前面页面是用什么技术开发的？

### ISSUE THREAD

**Issue by okuc** [Dromara/soul#119]
前面页面是用什么技术开发的？怎么看不到源代码呢？
想添加一些提示，结果找不到源码。

**Comment by yu199195** [comment]
在dromara组织下，soul-dashboard项目

**Comment by okuc** [comment]
> 在dromara组织下，soul-dashboard项目

您好！我在dashboard项目下好像只看到了前端页面的后台请求接口，并没有看到前端具体的每一个页面内容呢？

**Comment by yu199195** [comment]
https://github.com/Dromara/soul-dashboard

**Comment by okuc** [comment]
> https://github.com/Dromara/soul-dashboard

看到了，非常感谢。

**Comment by alant77** [comment]
请问我本地启动soul-admin之后，进入管理系统，本地并没有soul-dashboard,是怎么展示前端页面的？
