### ISSUE TITLE
websocket支持需要自己增加插件websocket么？！还是直接配置divide

### ISSUE THREAD

**Issue by jingb** [Dromara/soul#120]
（1）需要在plugin表插入一条websocket的数据么？！初始化sql脚本没有
**尝试过插入，但selector和rule的配置界面和divide的不一样，无法设置一些具体的东西**
（2）直接的divide配置selector和rule？具体要怎么配置
我在现在selector的配置是
![image](https://user-images.githubusercontent.com/9337766/68524860-90aa7a00-0306-11ea-86ee-bcac9878ac34.png)
rule的配置和selector差不多  过滤method=/ws

调用网关的指令是 
./telsocket -url 'ws://192.168.1.123:9001/?module=websocket&method=/ws&rpcType=websocket'

参考了xiaoyu发的[微信文章 ](https://mp.weixin.qq.com/s?src=11&timestamp=1573280613&ver=1963&signature=lYziqBM0R7sBAlznNBLCOvqwXhjPdgFkbsnTfy0TfZVzFhIZDVliQB5oHXyF1RApjHM556mB5OE6hmToXKgFngc7WI3Ly5uXatV6ZBALr3X3Zfwobu4CFh4f9CMODG6w&new=1)   里面关于websocket的描述

现在的情况是rule和selector都匹配到了   然后报下面的错   
 Resolved [IllegalStateException: Could not create URI object: Expected hostname at index 5: ws://:/192.168.1.123:18899/ws] for HTTP GET /

感觉websocket的支持描述还是太少了   自己在那调代码……

重要的是  不知道是直接配divide还是要加个websocket的插件……两种方式我都试过了   

@yu199195

**Comment by yu199195** [comment]
不需要加ws://

**Comment by jingb** [comment]
翻了下代码，找到拼url的地方  
把selector http配置的  ws:// 
改成 ws 就走通了
