### ISSUE TITLE
dubbo插件调用时候一直报错，下载的soul代码是最新的。

### ISSUE THREAD

**Issue by islandforus** [Dromara/soul#123]
POST: localhost:9001

{
    "interfaceName":"org.dromara.soul.test.dubbo.api.service.DubboTestService",
    "method":"insert",
    "paramClass":"org.dromara.soul.test.dubbo.api.entity.DubboTest",
    "classParams":
        {
            "id":"xxxx",
            "name":"xiaoyu"
        }
    
}
另外，dubbo插件使用这块的文档应该没有更新了，和代码的测试示例对应不起来。

**Comment by islandforus** [comment]
调试源码发现： DubboProxyService类的genericInvoker方法获取 GenericService genericService这个对象的时候一直是null，不知道什么原因。

**Comment by yu199195** [comment]
一直是null，那就是你的zk没配置对，分组，版本号

**Comment by islandforus** [comment]
dubbo处理：
应用名： test-dubbo-service
协议：dubbo
注册地址：   zookeeper://127.0.0.1:2181
端口号： 208889

**Comment by islandforus** [comment]
规则配置：

条件： 
method = insert
Hystrix处理：
分组Key：test-dubbo-service
命令Key：insert
分组： group1

Dubbo配置： 
版本号： 2.6.0
分组： group1

**Comment by yu199195** [comment]
这个问题，建议自己debug下，dubbo的服务引用源码。

**Comment by java-Learner-lx** [comment]
> POST: localhost:9001
> 
> {
> "interfaceName":"org.dromara.soul.test.dubbo.api.service.DubboTestService",
> "method":"insert",
> "paramClass":"org.dromara.soul.test.dubbo.api.entity.DubboTest",
> "classParams":
> {
> "id":"xxxx",
> "name":"xiaoyu"
> }
> 
> }
> 另外，dubbo插件使用这块的文档应该没有更新了，和代码的测试示例对应不起来。

您现在 dubbo和soul集成通了吗
