### ISSUE TITLE
InvalidClassException exception occurred while using cluster synchronization with ZooKeeper

### ISSUE THREAD

**Issue by jerbo99** [dromara/soul#1238]
## Describe the bug
java.io.InvalidClassException: org.dromara.soul.common.dto.SelectorData; local class incompatible: stream classdesc serialVersionUID = 4390101035898118220, local class serialVersionUID = 6055627969752212141

## Environment
- Soul version(s): [2.3.0]
- soul.sync configuration in application.yml：
     Comment out websocket.urls, enable zookeeper and its child nodes url, sessionTimeout, connectionTimeout

## Steps to reproduce
soul-admin-bin-2.3.0-RELEASE.tar.gz and soul-bootstrap-bin-2.3.0-RELEASE.tar.gz downloaded from https://github.com/dromara/soul. single node uses http The register and websocket sync were normal, and then changed to multi-node register and websocket sync using zookeeper. The above error was reported when the soul-bootstrap when starting.

**Comment by dengliming** [comment]
Thanks for reporting this issue. Can you fix it?

**Comment by yu199195** [comment]
please in english,  if not , we will close it

**Comment by jerbo99** [comment]
Trying

**Comment by jerbo99** [comment]
After many tests, I found that using OpenJDK (eg. build 1.8.0_65-b17) will encounter this problem, but using HotSpot (eg. build 1.8.0_181-b13) will not.
Defining serialVersionUID in SelectorData can avoid this problem in OpenJDK. At the same time, the related data that already exists in zookeeper needs to be deleted, and register client also needs to update soul-common.jar

**Comment by dengliming** [comment]
@jerbo99 Thanks. Can you submit PR to optimize this issue?

**Comment by jerbo99** [comment]
Ok. In addition, whether to make the following improvements:
1. Add -Dlog.home = ${LOG_DIR} to the startup parameters, when using commands like bin/start.sh, the log output through logback will also be located in the correct log directory
2. The initial password in sql does not need to be encrypted. If aes.secret.key is modified during the deployment process, the default password can also be used to log in.
