### ISSUE TITLE
soul 2.3.0 divide plugin handler only add one

### ISSUE THREAD

**Issue by linchuyao** [dromara/soul#1241]
<img width="500" alt="WeChatbb4cb0f260a46f77ca00fa6780d2b970" src="https://user-images.githubusercontent.com/32710423/114031203-b813c680-98ad-11eb-9fe7-556a8b4fd60c.png">

**Comment by yu199195** [comment]
why our can add ?

**Comment by linchuyao** [comment]
i am from soul 2.2.1 upgrade to 2.3.0 . Have data compatibility problem？

**Comment by dengliming** [comment]
Can you show me your plugin config? like this.
![image](https://user-images.githubusercontent.com/7796156/114043053-894f1d80-98b8-11eb-88d8-fbdcbbd22b75.png)

**Comment by linchuyao** [comment]
![Uploading WeChat3535dbdb686cc7d05609151c495c5a5c.png…]()

**Comment by linchuyao** [comment]
![Uploading WeChat3535dbdb686cc7d05609151c495c5a5c.png…]()

**Comment by linchuyao** [comment]
<img width="500" alt="WeChat3535dbdb686cc7d05609151c495c5a5c" src="https://user-images.githubusercontent.com/32710423/114128605-4f6d2e00-992f-11eb-9162-379ee6d20c47.png">

**Comment by fengzhenbing** [comment]
@linchuyao Your  plugin config about divide  is not the latest.  You can solve it as follow:
Config the divide plugin like [this](https://user-images.githubusercontent.com/7796156/114043053-894f1d80-98b8-11eb-88d8-fbdcbbd22b75.png).
or you can just drop the soul database, restart soul-admin,  then the [schema.sql ](https://github.com/dromara/soul/blob/master/soul-admin/src/main/resources/META-INF/schema.sql) will reexcute.

**Comment by linchuyao** [comment]
It seems that there is an incompatibility in upgrading from the lower version to 2.3.0. I have to redeploy and migrate the original configuration to the new library

**Comment by dengliming** [comment]
@linchuyao  yes. It should be that [schema.sql ](https://github.com/dromara/soul/blob/master/soul-admin/src/main/resources/META-INF/schema.sql)  failed to execute when admin was started. you can check the log.

**Comment by linsongGong** [comment]
did not encounter the same problem, but I found that when the number of nodes is greater than 7, part of the nodes will be lost, I solve this problem by increase the handle field of the soul.selector table.
