### ISSUE TITLE
how to set contextPath like v1,v2

### ISSUE THREAD

**Issue by panyox** [dromara/soul#1242]
## Question
using apache dubbo

eg.
http://test.com/v1/user/info
http://test.com/v2/user/info

so the contextPath should be v1,v2 or user?
i set contextPath is user, and try to use rewrite plugin, but it's not working, what should i do?

**Comment by dengliming** [comment]
https://dromara.org/zh/projects/soul/context-path-plugin/

**Comment by panyox** [comment]
> https://dromara.org/zh/projects/soul/context-path-plugin/

selector
<img width="763" alt="WX20210409-004305@2x" src="https://user-images.githubusercontent.com/77569707/114064942-b6a5c680-98cc-11eb-995b-568bc35e8058.png">

rule
<img width="597" alt="WX20210409-004330@2x" src="https://user-images.githubusercontent.com/77569707/114064965-be656b00-98cc-11eb-9bb3-3dbcde2faaad.png">

is this right?

**Comment by panyox** [comment]
### the url already replaced, but result still not working, i'm so confused

<img width="1305" alt="WX20210409-013936@2x" src="https://user-images.githubusercontent.com/77569707/114072500-eb1d8080-98d4-11eb-9363-4600cc14443a.png">

<img width="608" alt="WX20210409-014011@2x" src="https://user-images.githubusercontent.com/77569707/114072437-dc36ce00-98d4-11eb-85a4-9494f4aea366.png">

<img width="703" alt="WX20210409-014430@2x" src="https://user-images.githubusercontent.com/77569707/114072919-50717180-98d5-11eb-98f7-74a682e8bf59.png">

<img width="701" alt="WX20210409-014413@2x" src="https://user-images.githubusercontent.com/77569707/114072785-33d53980-98d5-11eb-812c-f2020c0d5299.png">

if remove v1 from url, it works, the contextPath is /app

<img width="552" alt="WX20210409-014800@2x" src="https://user-images.githubusercontent.com/77569707/114073392-cfff4080-98d5-11eb-807e-6cf3643e7e9a.png">

**Comment by panyox** [comment]
i resolved it, context-path must be worked with divide plugin

**Comment by panyox** [comment]
a little pity, why not do this work on context-path, in these scenes: i don't need load balance at all
```
// set the http url
String domain = buildDomain(divideUpstream);
String realURL = buildRealURL(domain, soulContext, exchange);
exchange.getAttributes().put(Constants.HTTP_URL, realURL);
```
