### ISSUE TITLE
关于获取到api的返回的json的问题

### ISSUE THREAD

**Issue by xtz9681** [Dromara/soul#126]
请问我可以在哪里获取到ServerWebExchange中返回的response的json呢？

**Comment by yu199195** [comment]
你要获取返回的json干嘛

**Comment by xtz9681** [comment]
因为要拓展，想根据返回的内容的codeNum和message做到网关对外统一格式输出。。。但不太了解这个类，只能拿到codeNum，不知道怎么获取message

**Comment by yu199195** [comment]
网关现在就有统一返回的啊，如果你想自定义返回，等下一个版本
