### ISSUE TITLE
Soul Admin Grpc upstream check bug

### ISSUE THREAD

**Issue by kenWu-github** [dromara/soul#1260]
## Describe the bug
Prerequisite: Soul Admin process is running normally, start the Grpc project, select http for registerType, successfully register the selector and other information to Soul Admin
1. Kill the Grpc process, and the processing information (handle) in the Soul Amin selector is cleared normally.
2. Restart the Soul Admin process and kill the Grpc process. At this time, the processing information (handle) in the Soul Amin selector is not cleared. In this case, restart the Grpc process and then close it, the processing information in the Soul Amin selector will not be deleted

## Environment

- Soul 2.3.1-SNAPSHOT

## Solution
file: SoulClientRegisterServiceImpl

![image](https://user-images.githubusercontent.com/9426606/114523810-39d16e80-9c77-11eb-9b5c-fd09daeab0d9.png)

**Comment by SaberSola** [comment]
we will fix it this week Thanks
