### ISSUE TITLE
2.3.0-RELEASE版本的dubbo能用么

### ISSUE THREAD

**Issue by nileblack** [dromara/soul#1262]
## Question
```
<bean id ="alibabaDubboServiceBeanPostProcessor" class ="org.dromara.soul.client.alibaba.dubbo.AlibabaDubboServiceBeanPostProcessor">
   <constructor-arg  ref="soulRegisterCenterConfig"/>
</bean>
```
AlibabaDubboServiceBeanPostProcessor 这个类根本就没有啊

**Comment by dengliming** [comment]
`AlibabaDubboServiceBeanPostProcessor`  Already removed in `2.3.0`. Use `org.dromara.soul.client.alibaba.dubbo.AlibabaDubboServiceBeanListener`  instead. BTW, we only accept English now. Thanks.
