### ISSUE TITLE
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO) occurs while starting soul-admin with start.bat

### ISSUE THREAD

**Issue by xiaotong-wang** [dromara/soul#1263]
When I launched Soul-Admin by 'remote download' in Windows, and I met a bug。Looking forward for your help!
1. I  modified mysql config in application.yaml
![image](https://user-images.githubusercontent.com/73211077/114567462-da3e8780-9ca5-11eb-9f89-f9bdf1f14578.png)
2. start.bat
3. The error message in console 
![image](https://user-images.githubusercontent.com/73211077/114567576-f04c4800-9ca5-11eb-8ee0-789f8a33c9b6.png)
4. The error message in soul-admin-error.log
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)

**Comment by dengliming** [comment]
Thanks for reporting this issue. This is because the configuration file is not in effect in `windows`. Currently you can modify the `start.bat` configuration.

`-Dspring.config.location` => `--spring.config.location`

BTW, we only accept English now.

**Comment by xiaotong-wang** [comment]
> 感谢您报告此问题。这是因为配置文件在。目前，您可以修改配置。`windows``start.bat`
> 
> `-Dspring.config.location=file:%BASE_DIR%\conf\` => `--spring.config.location=file:%PRGDIR%..\conf\`
> 
> 顺便说一句，我们现在只接受英语。

Thanks for your timely reply and I have changed the commit into English.

**Comment by xiaotong-wang** [comment]
> Thanks for reporting this issue. This is because the configuration file is not in effect in . Currently you can modify the configuration.`windows``start.bat`
> 
> `-Dspring.config.location=file:%BASE_DIR%\conf\` => `--spring.config.location=file:%PRGDIR%..\conf\`
> 
> BTW, we only accept English now.

Thanks for your timely reply and I have changed the commit into English.

**Comment by dengliming** [comment]
It that work for you?

**Comment by xiaotong-wang** [comment]
> It that work for you? Already reupload the dist package. https://github.com/dromara/soul/releases/tag/2.3.0

yes, thx!
