### ISSUE TITLE
Connection refused during graceful shutdown and startup

### ISSUE THREAD

**Issue by jerbo99** [dromara/soul#1266]
(springboot http service, registered with zookeeper) The upstream service gracefully shutdown, or when it is just started, there is a "Connection refused" in the soul-bootstrap.

Suggestion: When the upstream service gracefully shutdown, first go offline from the registration center, wait 1-2 seconds before rejecting new requests, and finally stop the service until the existing requests are processed or timeout; when starting, delay register until the service is started.

**Comment by yu199195** [comment]
can you fix it?

**Comment by jerbo99** [comment]
I think that the code in persistInterface can be change to async and delay n seconds. But I don't know how to judge that the service has been startup completed, to judge when to execute. I haven't figured out how to change the graceful shutdown.

**Comment by jerbo99** [comment]
In soul-register-common, set the started flag through ApplicationRunner, async persistInterface judges whether it can be register according to the flag.

**Comment by jerbo99** [comment]
Registration has been decoupled by queue, no longer need to be async

**Comment by jerbo99** [comment]
The problem of connection refused during shutdown was solved by adding a shutdown hook to close zkClient and delaying other hooks for n seconds.
