### ISSUE TITLE
能否在新版本支持，调用日志查看，最好是可视化，查看AppKey所有的调用情况，以便针对每一个appKey进行统一调用了哪些接口，什么时候调用

### ISSUE THREAD

**Issue by wangdazhong001** [dromara/soul#1267]
## Feature Request

类似参考http://demo.fizzgate.com/
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by yu199195** [comment]
please in english
