### ISSUE TITLE
关于soul的线程模型

### ISSUE THREAD

**Issue by Wang-Ray** [dromara/soul#1279]
Soul通过自定义`WebHandler`的实现`SoulWebHandler`来作为切入口，在`handle`方法中而外配置了调度器（`subscribeOn(scheduler)`），代码如下：
```java
@Override
public Mono<Void> handle(final ServerWebExchange exchange) {
    return new DefaultSoulPluginChain(plugins)
                .execute(exchange).subscribeOn(scheduler);
}
```
这样相当于增加了一层线程池，是不是想把业务处理从io线程中解耦出来呢？但是由于是Reactive编程模型，业务处理并不会阻塞，感觉没必要再增加这一级线程池，看了Spring Cloud Gateway的相关实现，没有额外增加类似的一层线程池，不知道理解得对不对，请大家指教。

**Comment by yu199195** [comment]
please in english
