### ISSUE TITLE
关于设置选择器规则Hystrix处理

### ISSUE THREAD

**Issue by muistar** [Dromara/soul#128]
![image](https://user-images.githubusercontent.com/24907627/70214536-9022c900-1776-11ea-87bb-f7abc2c817ca.png)
请问如何设置才能生效，现在不修改任何配置的话，永远都是返回业务异常信息，不会走到网关的熔断里

**Comment by yu199195** [comment]
自己理解下熔断的概念先。。。

**Comment by muistar** [comment]
> 自己理解下熔断的概念先。。。

sorry,已经知道情况了，超时情况下会走到熔断的...

**Comment by muistar** [comment]
大佬，顺便问下，cloud的注册中心使用nacos时，这边新增了一个SpringCloudNacosConfiguration类似于SpringCloudConfiguration配置，只修改@ConditionalOnProperty(prefix = "spring.cloud.nacos.discovery", name = "server-addr")，注释掉eureka-client jar包就跟cloud-eureka一样使用，路由+限流+熔断什么暂时都没问题，后面支持nacos大概会什么时候，现在这么改内心慌得一比~~
