### ISSUE TITLE
Vote  SteNicholas to Init Committers

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1280]
@SteNicholas  I communicated with you before, and you said you didn't have time to participate
Would you like to continue to participate in the community now? Explain the reasons for your current involvement ?

**Comment by SteNicholas** [comment]
@yu199195 , for the soul community, previously I was busy for my work and had a little time to contribute to the community. Recently, I'm available to contribute to the feature implementations and bugfix to the soul community, and review the pull requests. I believe I'm capable of doing this committers.
