### ISSUE TITLE
Discuss about initial committers

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1282]
Hi, community.

Our project is under discussion about joining in the Apache Incubator.

It's helpful to launch a discussion about the initial committers list based on codes and community contributions.

### codes 
I propose the following 2 rules to soul and soul-dashboard (Both conditions are met):

* Commits count >=7 in one project
* Add code lines >=1000  in one project

### community
* Actively running the community as a mentor （mentor ： Meetup organizers or Community keynote speaker）
* Answering community questions

### proposal

The following contributors will be nominated initial committers.

### soul (github-id) :
yu199195
dengliming
tydot
SteNicholas
Asxing
nuo-promise
huangxfchn
lw1243925457
SaberSola
CCLooMi
Trafalgar-YuI
0x12FD16B
KevinClair

### soul-dashboard (github-id)
xlgm
fightingting
fengzhenbing

### community(github-id)
kimmking: as Apache Dubbo & ShardingSphere PMC member, he organizes source sharing activities, bringing important help to the community.
tuohai666 : as Apache ShardingSphere PMC member, he is actively involved in community discussions and activities, and give powerful help about the community conform to Apache Way.

### Finally

Above is just my suggestion, welcome anybody to discuss together （Fair, just and open）.

Voters can either respond "agree, yes, +1", or "advice".

**Comment by Asxing** [comment]
+1

**Comment by tuohai666** [comment]
Thanks Yu for add me to the initial committers list. 

I am also the release manager of ShardingSphere, wrote the release guide and finished the incubating release.

I will do the same thing in Apache way if/when Soul is ready for a incubating release. Maybe I would make the release a little faster to be finished.

**Comment by kimmking** [comment]
+1

Thanks Yu for adding me to the initial committers list.
I will take more to develop and improve community.  : )

**Comment by dengliming** [comment]
+1 

Thanks Yu for adding me to the initial committers list. Let's make the community be even better.

**Comment by fengzhenbing** [comment]
+1

Thanks Yu for adding me to the initial committers list.
I will work harder with everyone to contribute to the community .

**Comment by SaberSola** [comment]
+1  
Thanks Yu for adding me to the initial committers list.
I will work harder than before to make the community better.

**Comment by lw1243925457** [comment]
+1
Thanks Yu for adding me to the initial committers list.
I will work harder than before to make the community better.

**Comment by onlyonezhongjinhui** [comment]
yes

**Comment by tangtian8** [comment]
agree

**Comment by strawberry-crisis** [comment]
agreed

**Comment by hjmJhon** [comment]
+1

**Comment by SaberSola** [comment]
Thanks Yu for adding me to the initial committers list. 
I will try my best to make the community better.

**Comment by nuo-promise** [comment]
+1

Thanks Yu for adding me to the initial committers list.
I will treat the community as my second business and work hard to contribute to the community.

**Comment by Wincher** [comment]
agree

**Comment by MarcusJiang1306** [comment]
agree

**Comment by tydhot** [comment]
+1 
I am willing to be the init committer for this project. Lets's do something different.

**Comment by ttttangzhen** [comment]
agree

**Comment by peiht** [comment]
+1

**Comment by hellboy0621** [comment]
agree

**Comment by sydgeek** [comment]
+1

**Comment by zendwang** [comment]
+1

**Comment by wilbur1991** [comment]
+1

**Comment by jinze1107** [comment]
+1

**Comment by midnight2104** [comment]
+1

**Comment by 0x12FD16B** [comment]
+1.
Thanks Yu for adding me to the initial committee, I will try my best to contribute to the community.

**Comment by prFor** [comment]
+1

**Comment by Johar77** [comment]
+1

**Comment by kennhua** [comment]
+1

**Comment by renzhuyan** [comment]
+1

**Comment by synchronizedlock** [comment]
+1

**Comment by plutokaito** [comment]
+1

**Comment by Redick01** [comment]
+1

**Comment by fightingting** [comment]
+1
Thanks Yu for adding me to the initial committers list.
I will work harder than before to make the community better.

**Comment by PayneWoo** [comment]
+1

**Comment by zhaiweij** [comment]
+1

**Comment by abysscat-yj** [comment]
+1

**Comment by songyuequan** [comment]
+1

**Comment by fcwalker** [comment]
+1
I will try to achieve these two rules

**Comment by wuliendan** [comment]
+1
Thanks Yu for adding me to the initial committers list.

**Comment by Trafalgar-YuI** [comment]
+1

**Comment by jnzhouhao** [comment]
+1

**Comment by SpaceEmpire** [comment]
+1

**Comment by itdachaoge** [comment]
+1

**Comment by yu199195** [comment]
@wuliendan  you not in init committer list....

**Comment by lxl910128** [comment]
+1

**Comment by xiaoshen11** [comment]
+1

**Comment by wyc192273** [comment]
+1

**Comment by qianglu1989** [comment]
+1

**Comment by BetterWp** [comment]
+1

**Comment by charlesgongC** [comment]
+1

**Comment by zibuyu28** [comment]
+1

**Comment by xxiancheng** [comment]
+1

**Comment by zibuyu28** [comment]
totally agree

**Comment by SpaceEmpire** [comment]
+1

**Comment by charlesgongC** [comment]
+1

**Comment by kminjava** [comment]
Agree.I will work harder to contribute code to the group to reach the limits!

**Comment by KevinClair** [comment]
+1
Thanks Yu for adding me to the initial committers list.
I will try my best to make the soul better.

**Comment by keru-s** [comment]
+1
Thanks to Soul for steering me into open source, hope for the better.

**Comment by candyYu** [comment]
Agree. I want to participate more in open source.

**Comment by yiwenlong** [comment]
Agree. 
Soul is a very valuable project. I know that it is widely used within the enterprise, of course, including the company I work for. 
Its performance is very high and the code quality is very good. After joining Apache, it will definitely help more people and organizations.
I am very happy that I have coding for such an excellent project, and I will continue to contribute to it.

**Comment by Trafalgar-YuI** [comment]
Agree.
Thanks Yu for adding me to the initial committers list.
Let me enter the open source world. I will try my best to contribute to the community.

**Comment by stephenshen1993** [comment]
Agreed. 
It's great to see Soul grow, and I will try to contribute to the community and become a committer within a year.

**Comment by jjnnzb** [comment]
Agree. Soul is advanced in design concepts and elegant in coding, and the whole community of Dromara is so friendly.

**Comment by xlgm** [comment]
+1
Agree. I want to participate more in open source.

**Comment by cchenxi** [comment]
Agree.
I will participate more in the community.

**Comment by Zhoutzzz** [comment]
Agree.
Soul is a good high-performance gateway. In the process of participating in the dromara community to contribute to soul, the committers will enthusiastically participate in the discussion of issus and answer questions from gateway users and developers,and the discussion process for each issue are very valuable, which makes me enjoy.

**Comment by FocusZhouGD** [comment]
Agree.
I will spend more time contributing to the community and become a committer.

**Comment by branchen** [comment]
Agree.
I wish all projects of community will be better.

**Comment by jinze1107** [comment]
Agree


> Agree.
> I will spend more time contributing to the community

metoo

**Comment by Lin1nGithub** [comment]
+1

**Comment by lahmXu** [comment]
+1

**Comment by KuanYa** [comment]
+1

**Comment by itmiwang** [comment]
+1
Thanks Yu for adding me to the initial committers list.
I will try my best to make the soul better.

**Comment by CCLooMi** [comment]
+1

**Comment by SteNicholas** [comment]
+1

**Comment by cocoZwwang** [comment]
+1

**Comment by huangxfchn** [comment]
agree++

**Comment by yu199195** [comment]
We inform the community to participate in, everyone's enthusiasm, love open source, this discussion has no objection ,
If there are no further comments, we will be closed within the next 1 day.

**Comment by cwangtf** [comment]
agree, try to become a committer early
