### ISSUE TITLE
soul could support gray publish strategy

### ISSUE THREAD

**Issue by linchuyao** [dromara/soul#1288]
I have such scenarios. We need to publish gray level, support different strategies, and implement fixed list and module taking operation

**Comment by tuohai666** [comment]
Hi @linchuyao ,

Can you list the strategies needed in detail? Such as in or %=

**Comment by Asxing** [comment]
In my opinion, we can build a stage environment to solve this problem skillfully. Of course, this is only a form of grayscale release. For specific grayscale strategy scenes, I think we still need to discuss in detail.

**Comment by linchuyao** [comment]
> 嗨@linchuyao，
> 
> 您能否详细列出所需的策略？如in或％=

for example request queryString have user_id field ，i can config strategy if user_id%5=0  or if user_id in(1,2,3)  this request will route gray environment

**Comment by tuohai666** [comment]
Got it. 
We can treat these expressions  as boolean expression. If a expression is true then the query turn into gray.
1. Set the parameter, like 'user_id'.
2. Set the expression, like ${user_id}%5=0 , ${user_id} in (1,2,3)
Maybe we could use groovy script parse the expression. Any suggestion? @Asxing @linchuyao

**Comment by linchuyao** [comment]
> Got it.
> We can treat these expressions as boolean expression. If a expression is true then the query turn into gray.
> 
> 1. Set the parameter, like 'user_id'.
> 2. Set the expression, like ${user_id}%5=0 , ${user_id} in (1,2,3)
> 
> Maybe we could use groovy script parse the expression. Any suggestion? @Asxing @linchuyao

i think so

**Comment by tuohai666** [comment]
I published this requirement as a new feature issue https://github.com/dromara/soul/issues/1295
