### ISSUE TITLE
Add Http-Header-Max-Size to divide plugin

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#1290]
Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

Feature

each request.getHeaders()   length , if  > custom config

**Comment by Asxing** [comment]
Why develop a filter when we can configure it with the server.max-http-header-size parameter?

**Comment by yu199195** [comment]
Add to divide plugin

**Comment by Asxing** [comment]
> Add to divide plugin

👌, thx.

**Comment by zendwang** [comment]
I want to get it,OK?

**Comment by zendwang** [comment]
Default parameters don't change on divide plugin  when custom config updated.
refer to #1294 !
This issue should fix the bug or not?

**Comment by WYUSIG** [comment]
assign to me plz
