### ISSUE TITLE
Support boolean expression rule for gray release

### ISSUE THREAD

**Issue by tuohai666** [dromara/soul#1295]
For now there are 4 matching rules: **match**, **=**, **regEx**, **like**. A new customized rule with parameters will make gray release more flexible. The previous discussion can be found at https://github.com/dromara/soul/issues/1288
![image](https://user-images.githubusercontent.com/24643893/115527786-f654b100-a2c3-11eb-83d0-b006a3dc3e5a.png)

I suggest that we add a **boolean expression** rule, if the expression is **true** then the query will be routed to the new version.

The provision may like:

1. Set the parameter(from URI or Header), like 'user_id'.
2. Set the expression, like ${user_id}%5=0 , ${user_id} in (1,2,3)

With this rule, users can simply control the new version proportion by adjust the expression instead of design the URI or Header.

Maybe we could use groovy script parse the expression, or something else.

Tasks list:

- [x] Support SpEL condition
- [ ] Support Groovy condition

**Comment by zhaiweij** [comment]
The groovy script is more flexible

**Comment by onlyonezhongjinhui** [comment]
groovy script

**Comment by zendwang** [comment]
The groovy script is more flexible, but user shoud be programmer .we need to consider the cost of study.

**Comment by tuohai666** [comment]
> The groovy script is more flexible, but user shoud be programmer .we need to consider the cost of study.

Agree. I wonder how to parse a common expression, any suggestions?

**Comment by zendwang** [comment]
Spring Expression Language (SpEL)

**Comment by yu199195** [comment]
>Spring Expression Language (SpEL) 

good idea

**Comment by yu199195** [comment]
> The groovy script is more flexible

good idea

**Comment by zhaiweij** [comment]
groovy script + SpEL  ?

**Comment by yu199195** [comment]
> groovy script + SpEL ?

the two strategy
