### ISSUE TITLE
The request body is too large

### ISSUE THREAD

**Issue by Gaaahan** [dromara/soul#1300]
## Question
When forwarding a request using Soul (version: 2.2.1, plugin: SpringCloud, data synchronization: WebSocket), the request body is too large to access the Soul
Error code: 413
Error message: Request Entity  Too Large。
<img width="435" alt="微信图片_20210422150429" src="https://user-images.githubusercontent.com/63275565/115678992-aee22980-a384-11eb-89c4-715e9de0801e.png">

## Solution
I changed the request body size for Nginx and Tomcat at the beginning, but it didn't seem to work. Later, someone in the WX message group raised the problem of netty, so I went to check online and found that the default maximum value of netty request is 8K。
we need to go to the aplication or  bootstrap modify the configuration:

     server.max-http-header-size: 10240000

PS: 1. Tomcat and nginx also need to configure max-http-header-size。
      2. Spring Boot 2.0 or less is not work, you need to hack and autowired a class：NettyReactiveWebServerFactory,look here：https://blog.csdn.net/qq_34083066/article/details/103689859

**Comment by SaberSola** [comment]
can you fix it?
i think The core of the problem is configuration the http max header size.
so it can be solved in this way
first You can customize httpRequestDecoder in EventLoopNettyCustomizer.java 
Then config maxHeaderSize u want to set

**Comment by Gaaahan** [comment]
Yes, I have solved this problem for the time being. I set the max-http-header-size of the service directly. Spring Bootboot2.0 can be used to solve this problem
