### ISSUE TITLE
api gateway can't matching routes http status 500

### ISSUE THREAD

**Issue by starslau** [dromara/soul#1301]
If I request the route is not defined in soul-admin, the http status code returned by the gateway is 500,
(`{
    "code": 500,
    "message": "Internal Server Error"
}`),
 and the gateway information error reporting is "java.lang.NullPointerException: null",
`java.lang.NullPointerException: null
	at org.dromara.soul.plugin.global.DefaultSoulContextBuilder.build(DefaultSoulContextBuilder.java:63) ~[soul-plugin-global-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.dromara.soul.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.web.filter.WebSocketParamFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/test/goods/selectByName?name=%E6%B5%8B%E8%AF%953" [ExceptionHandlingWebHandler]`
 I think the response code of gateway should be defined by HTTP status code, that is 404

**Comment by tydhot** [comment]
I think that is a good idea. Feel free to submit a pr.:)

**Comment by plutokaito** [comment]
if my thinking is not in wrong way, that's meaning  if `NullPointException` happened, the result  return HTTP_NOT_FOUND state？

**Comment by yu199195** [comment]
yes
