### ISSUE TITLE
DefaultSignService这个类硬依赖了javafx的组件

### ISSUE THREAD

**Issue by LilithBristol** [Dromara/soul#131]
org.dromara.soul.web.plugin.before.DefaultSignService 这个类依赖了javafx.util.Pair

javafx 在jdk11都被移出标准javase了

建议不要硬依赖javafx的东西了 用了个其他发行版的jdk8直接找不到

apache common lang3里好像也有pair 

![image](https://user-images.githubusercontent.com/20179864/70864046-65601e00-1f89-11ea-8b53-630819c962ec.png)

**Comment by yu199195** [comment]
嗯，

**Comment by adventurer2008** [comment]
我现在也报这个错误，那怎么解决呢？

**Comment by adventurer2008** [comment]
换了jdk就可以了

**Comment by yu199195** [comment]
这个在最新的版本已经修护
