### ISSUE TITLE
GsonUtils.getInstance().convertToMap() throws exception

### ISSUE THREAD

**Issue by ttttangzhen** [dromara/soul#1311]
## Describe the bug
when I run this unit test 
`org.dromara.soul.plugin.dubbo.common.param.DubboBodyParamResolveServiceTest#testBuildParameterWithNull`

if I set varible `body` with 
```
{
  "complexBean": {
    "dubboTest": {
      "id": null,
      "name": null
    },
    "idLists": [
      null,
      null
    ],
    "idMaps": {
      "id2": null,
      "id1": null
    }
  },
  "name": null
}
```

the method will throws Exception because of that the json has a key `idList` contain null.

do you think it need to be fixed?
if so, I will fix it.

**Comment by dengliming** [comment]
@ttttangzhen yes. please feel free to submit a pr.
