### ISSUE TITLE
Maybe soul admin's sort with order by need to be polish

### ISSUE THREAD

**Issue by tydhot** [dromara/soul#1318]
## Describe the bug
<img width="961" alt="image" src="https://user-images.githubusercontent.com/27889201/115966738-85322980-a561-11eb-90ae-b57e078e0d10.png">
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/27889201/115966747-9418dc00-a561-11eb-88ae-49f01fc3a8ce.png">
if I choose order by status, I think page 2's first plugin should be in page 1.

## Environment

- Soul version(s): 2.3.1 master brand

**Comment by dengliming** [comment]
Currently, the sort only applies to the current page.
