### ISSUE TITLE
服务隔离是否有考虑支持Sentinel？

### ISSUE THREAD

**Issue by AngryApe** [Dromara/soul#132]
@ihenjoy 我目前在公司也负责网关，现在网关服务隔离同样采用了Hystrix，由于Hystrix采用了线程池的方式隔离应用，生产环境有很多应用，每个网关服务器上都有2000+线程。考虑到网关是性能型应用，这种方式太过于笨重，相比之下，Sentinel采用信号量（线程计数器）隔离的方式就轻了很多，不知道是否有这方面考虑？

**Comment by yu199195** [comment]
Sentinel 太重太重，对网关来说，不是很适合接入。 Hystrix u也可以使用信号量。。。

**Comment by Wang-Ray** [comment]
Sentinel还好吧，封装得挺好的，也挺完善。

**Comment by ihenjoy** [comment]
现在 soul 配置上也是 基于信号量的
