### ISSUE TITLE
Add query conditions for some pages in Soul-Dashboard

### ISSUE THREAD

**Issue by fengzhenbing** [dromara/soul#1328]
- [x] Add conditon of selectorName field and ruleName filed in  PluginList/plugin page.@fengzhenbing
- [x] Add conditon of status field   in BasicConfig/plugin page.@WYUSIG
- [x]  Add conditon of fieldName field   in BasicConfig/PluginHandle page.@WYUSIG
- [x] Check if there are other conditions that need be added.@fengzhenbing

**Comment by WYUSIG** [comment]
assign these to me plz 🥰

- [ ] Add conditon of status field in BasicConfig/plugin page.

- [ ] Add conditon of fieldName field in BasicConfig/PluginHandle page.

**Comment by fengzhenbing** [comment]
The search field in PluginList/plugin page maybe like this:

![image](https://user-images.githubusercontent.com/4169359/117234048-d5a96100-ae56-11eb-900c-000e624c1a18.png)

**Comment by fengzhenbing** [comment]
The status field in PluginList/plugin page maybe like this:

![image](https://user-images.githubusercontent.com/4169359/117235989-5f0e6280-ae5a-11eb-95ec-3bf8aafef1fc.png)

**Comment by fengzhenbing** [comment]
The fieldName field in BasicConfig/PluginHandle page maybe like this:

![image](https://user-images.githubusercontent.com/4169359/117236140-bc0a1880-ae5a-11eb-874e-3ecba4e0c3a3.png)

**Comment by WYUSIG** [comment]
thanks.🥰
