### ISSUE TITLE
NacosServerRegisterRepository class miss authentication parameters

### ISSUE THREAD

**Issue by PandaUncle** [dromara/soul#1341]
## Describe the bug
If nacos server enable auth, an exception will throw:
Error creating bean with name 'soulServerRegisterRepository'
the reason is NacosServerRegisterRepository.init function do not set authentication parameters for nacosProperties variable。

**Comment by PandaUncle** [comment]
NacosClientRegisterRepository has the same problem

**Comment by yu199195** [comment]
you can fix it

**Comment by PandaUncle** [comment]
> you can fix it

ok
