### ISSUE TITLE
Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $

### ISSUE THREAD

**Issue by wangdazhong001** [dromara/soul#1356]
## Question
Access to other languages, after successful registration, edit the corresponding rulelist in divide, click modify, and save without modification after entering the web editing. Then to call the interface, there will be a 500 error.
// your question here;
![image](https://user-images.githubusercontent.com/49627839/116380453-8eafe000-a846-11eb-91e2-0d011630992c.png)

https://user-images.githubusercontent.com/49627839/116380780-dfbfd400-a846-11eb-8447-e591acf1ac74.mp4

Please pay attention on issues you submitted, because we maybe need more details. 
After investigation, the cause of the cause is the handle in the rule table. The handle is theoretically an object by default. This is caused by the database version, and the corresponding database can be used to solve it.

If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by wangdazhong001** [comment]
For reference

**Comment by nuo-promise** [comment]
> For reference


Sorry, we have gone through the test according to your video process. Use the registration information you provided to test and observe that the data stored in the database is normal. You can debug it according to our source code.
