### ISSUE TITLE
dubbo版本配置后请求失败

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#137]
o.d.soul.web.plugin.AbstractSoulPlugin   :dubbo selector success selector name :/dubbo
o.d.soul.web.plugin.AbstractSoulPlugin   : test-dubbo-service:org.dromara.soul.test.dubbo.api.service.DubboTestService match dubbo rule is name :/dubbo/findByLong
o.d.s.web.plugin.hystrix.DubboCommand    : dubbo rpc have error:No provider available from registry localhost:2181 for service org.dromara.soul.test.dubbo.api.service.DubboTestService on consumer 172.16.20.62 use dubbo version 2.6.0, may be providers disabled or not registered ?

**Comment by yu199195** [comment]
这么明显的错误，自己去解决把

**Comment by java-Learner-lx** [comment]
确实。头大了。添麻烦了，搞定了
