### ISSUE TITLE
外部容器

### ISSUE THREAD

**Issue by luoyanjun0000** [Dromara/soul#143]
由于公司架构原因，怎么把soul部署到外部tomcat

**Comment by yu199195** [comment]
soul-web使用的是springboot的内置的webflux，soul-admin使用内置的tomcat，你可以改造后者

**Comment by luoyanjun0000** [comment]
嗯，
soul-web，webflux也可以改造为是使用servlet3.1,然后部署到外部tomcat吧


谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "流浪诗人"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 下午3:20
收件人: "Dromara/soul"<soul@noreply.github.com&gt;; 
抄送: "Tuple"<331345834@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Dromara/soul] 外部容器 (#143)




soul-web使用的是springboot的内置的webflux，soul-admin使用内置的tomcat，你可以改造后者
