### ISSUE TITLE
创建selectorCondition问题

### ISSUE THREAD

**Issue by xixincan** [Dromara/soul#144]
使用http自动注册时，默认的创建选择器的选择器条件： 
           SelectorConditionDTO selectorConditionDTO = new SelectorConditionDTO();
            selectorConditionDTO.setParamType(ParamTypeEnum.URI.getName());
            selectorConditionDTO.setParamName("/");
            selectorConditionDTO.setOperator(OperatorEnum.MATCH.getAlias());
            selectorConditionDTO.setParamValue(contextPath);
是设置uri match方式，但是paramValue取的是contextPath，没有追加通配符/**，导致未能匹配选择器,需要在后台手动添加通配符才能路由到被代理的服务。

**Comment by yu199195** [comment]
这可能是个bug。。

**Comment by xixincan** [comment]
另外我还发现，在创建选择器时主机明层localhost还拼写错了。。。233333
            DivideUpstream divideUpstream = new DivideUpstream();
            divideUpstream.setUpstreamHost("localohost");
            divideUpstream.setProtocol("http://");
            divideUpstream.setUpstreamUrl(uri);

**Comment by yu199195** [comment]
你可以提供一个pr上来
