### ISSUE TITLE
我要在自定义插件里在request 里面放一些值传给后端的服务怎么做呀

### ISSUE THREAD

**Issue by mahe09** [Dromara/soul#148]
@Override
    public Mono<Void> execute(ServerWebExchange exchange, SoulPluginChain chain) {
        System.out.println("TokenValidPlugin execute");
        String token = exchange.getRequest().getQueryParams().getFirst("token");
        if (token == null){
            Object error = SoulResultWarp.error(-301, "失效", null);
            return SoulResultUtils.result(exchange, error);
        }

        String val = redisTemplate.boundValueOps(token).get();
        if (val == null){
            Object error = SoulResultWarp.error(-302, "过期", null);
            return SoulResultUtils.result(exchange, error);
        }
       request.add(key,val)---类似于这样
        return chain.execute(exchange);
    }

**Comment by yu199195** [comment]
通过header传递到后端就行了
