### ISSUE TITLE
sign插件无法匹配restful风格的url

### ISSUE THREAD

**Issue by wwjjkk** [Dromara/soul#149]
使用版本2.1.2 
参考文档http用户接入方式，未使用sign插件时能正常通过网关进行访问。启用sign插件后，提示认证未配置路径获取未配置。跟踪源码后发现DefaultSignService 110行是通过anyMatch进行url判断的。而restful类型的url地址注册时url路径中包含**字符串无法通过匹配判断

**Comment by yu199195** [comment]
这种是通过like来进行匹配

**Comment by wwjjkk** [comment]
意思是需要自己手动在插件列表中添加sign的选择器，然后条件里选择like？
