### ISSUE TITLE
Hystrix 修改admin-rule配置不生效

### ISSUE THREAD

**Issue by bigbug-dachong** [Dromara/soul#150]
1、修改admin-rule规则，Hystrix：超时时间
2、bootstrap服务缓存同步，数值正确
3、调用divide转发，超时时间配置不生效。

有没有人遇到过类似的问题。

版本：2.0时期的某个分支

**Comment by klboke** [comment]
可以参考下这个pr，可能是同一个问题：https://github.com/Dromara/soul/pull/96
