### ISSUE TITLE
2.1.2无法配置超时时间

### ISSUE THREAD

**Issue by luoyanjun0000** [Dromara/soul#154]
2.1.2版本，超时时间没有配置入口

**Comment by yu199195** [comment]
超时是hystrix插件配置的

**Comment by luoyanjun0000** [comment]
看代码并不是啊，是divide插件有超时时间，超时和熔断没关系吧，放在divide更合理啊，熔断想用的话可以读divide插件中超时

**Comment by luoyanjun0000** [comment]
> 超时是hystrix插件配置的



> 超时是hystrix插件配置的

看代码并不是啊，是divide插件有超时时间，超时和熔断没关系吧，放在divide更合理啊，熔断想用的话可以读divide插件中超时

**Comment by yu199195** [comment]
你是说前端没有这个输入框？

**Comment by luoyanjun0000** [comment]
> 你是说前端没有这个输入框？

嗯，前端也没有输入框，而且超时时间实在divide插件中设置的
