### ISSUE TITLE
DubboPlugin插件调用是同步

### ISSUE THREAD

**Issue by luoyanjun0000** [Dromara/soul#155]
2.1.2DubboPlugin插件调用是同步，会导致线程阻塞吧

**Comment by yu199195** [comment]
肯定会，异步也会，只有通知机制才不会

**Comment by luoyanjun0000** [comment]
> 肯定会，异步也会，只有通知机制才不会

异步直接返回句柄，用反应式nio模式等代理服务处理时间，同步需要等待服务处理完吧

**Comment by luoyanjun0000** [comment]
reactor不就是需要服务端调用其他服务异步吗，没搞明白

**Comment by Wang-Ray** [comment]
确实是这样的，同步调用dubbo的话，网关会被阻塞。dubbo支持异步，可以改造dubbo插件支持即可。

**Comment by Wang-Ray** [comment]
#166 ，尝试将dubbo从同步修改为异步调用了
