### ISSUE TITLE
bootstrap中SoulExtConfiguration配置类扩展dubbo多参数不生效

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#158]
按文档中去扩展配置类不生效，求大佬帮助一下，bootstrap中SoulExtConfiguration配置类
中加入加载新的配置类：
 @Bean
    public GenericParamResolveService genericParamResolveService(){
        return new MutiGenericParamResolveServiceImpl();
    }
但是还是走默认的default类，求指教

**Comment by cxc222** [comment]
@java-Learner-lx 你修改一下代码
路径：org.dromara.soul.web.configuration.DubboConfiguration
修改：public SoulPlugin dubboPlugin
```java
@Bean
    public SoulPlugin dubboPlugin(@Qualifier("localCacheManager") final LocalCacheManager localCacheManager, @Qualifier("genericParamResolveService") final GenericParamResolveService genericParamResolveService) {
        return new DubboPlugin(localCacheManager, new DubboProxyService(genericParamResolveService));
    }
```

**Comment by java-Learner-lx** [comment]
> @java-Learner-lx 你修改一下代码
> 路径：org.dromara.soul.web.configuration.DubboConfiguration
> 修改：public SoulPlugin dubboPlugin
> 
> ```java
> @Bean
>     public SoulPlugin dubboPlugin(@Qualifier("localCacheManager") final LocalCacheManager localCacheManager, @Qualifier("genericParamResolveService") final GenericParamResolveService genericParamResolveService) {
>         return new DubboPlugin(localCacheManager, new DubboProxyService(genericParamResolveService));
>     }
> ```

这还是需要改源码。对吗

**Comment by java-Learner-lx** [comment]
@cxc222 还是需要改源码 对吗

**Comment by cxc222** [comment]
@java-Learner-lx 你看他源码方法，这里dubboPlugin处理是写死的，所以每次都拿到DefaultGenericParamResolveServiceImpl类。

**Comment by java-Learner-lx** [comment]
@cxc222 好的谢谢，您让我明白了原因 非常感谢，我再熟悉一下

**Comment by cxc222** [comment]
@java-Learner-lx @Qualifier("genericParamResolveService") 换成 @Autowired 也是OK的。

**Comment by yu199195** [comment]
没看懂你们的讨论

**Comment by cxc222** [comment]
> 没看懂你们的讨论

他想实现自定义dubbo参数解析，实现了GenericParamResolveService接口，并设置bean，但是并没有生效。

**Comment by java-Learner-lx** [comment]
@yu199195 
dubbo多参数扩展
文档中：把你的类注册成Spring的bean，覆盖默认的实现。
`@Bean
public GenericParamResolveService genericParamResolveService() {
        return new A();
 }`

但是这么做不生效，还是走的默认的实现org.dromara.soul.web.plugin.dubbo.DefaultGenericParamResolveServiceImpl

发现 源码DubboConfiguration中
`@Bean
    public SoulPlugin dubboPlugin(@Qualifier("localCacheManager") final LocalCacheManager localCacheManager) {
        return new DubboPlugin(localCacheManager, new DubboProxyService(genericParamResolveService()));
    }`

还是引的本类的实例， 所以扩展的不生效

如果说的不对 请大佬指正，谢谢
