### ISSUE TITLE
sign插件问题

### ISSUE THREAD

**Issue by xa-yifan** [Dromara/soul#160]
这个鉴权插件，只要已开启，是全部接口都需要鉴权吗？我测试是这样的，认证管理里面配置资源管理根本不起作用

**Comment by Wang-Ray** [comment]
目前确实是这样的，只有继承了AbstractSoulPlugin的插件（包括9个：DividePlugin，DubboPlugin，HystrixPlugin，MonitorPlugin，RateLimiterPlugin，RewritePlugin，SpringCloudPlugin，WafPlugin，WebSocketPlugin）才支持选择器和规则配置，否则是全局的。

**Comment by springMonton** [comment]
@yu199195 soul对鉴权插件支持，当初设计目标是？？？
目前代码中实现：
1.对于sign插件，选择器和规则，代码中目前是不支持的。
2.只要开启鉴权插件，请求都会进行verify校验，一些不需要鉴权的请求也会被拦截掉。（代码中校验appKey、sign、timestamp不能为空）
3.代码中是否应该支持，对需要鉴权的请求进行拦截校验，不需要的请求直接跳出。不然这种全局的插件意义不大。

**Comment by yu199195** [comment]
自己扩展下SignService 不就好了吗？  @springMonton
