### ISSUE TITLE
选择器中全流量和自定义流量区别?

### ISSUE THREAD

**Issue by yj1760216019** [Dromara/soul#162]
自定义流量和全流量的区别是什么

**Comment by Wang-Ray** [comment]
全流量不需要配置规则，标示全部通过；
自定义流量必须配置规则，基于规则匹配与否决定是否通过

**Comment by yj1760216019** [comment]
MetaData metaData = AbstractLocalCacheManager.findByUri(path);     这个MetaData是如何加载的，业务需要在里边扩展参数
