### ISSUE TITLE
2.1.2 http 用户接入如何不配置 zookeeper时系统在启动时会报错，要求配置zookeeper

### ISSUE THREAD

**Issue by wxp732826840** [Dromara/soul#164]
错误日志
springMvc register must config context-path and zookeeperUrl.... 
既然已经支持websocket了 为什么还要强制zookeeper？

还有在http 用户接入时文档中有这么一句话
"到这里对于 springMvc 项目 还不是最佳的接入方式，因为我们还没有接入ip与端口. 如果是以上的话，还需要在soul-admin 中的divide插件中找到你对应的路由，然后手动填写地址。"
最佳方式 就是 还要单独引入一个zookeeper吗？
我看在文档总有一个 “自定义解析ip与host“  为什么不用这个  非要引入zookeeper呢？

**Comment by yu199195** [comment]
这个意思是你服务的ip+端口需要自动注册，服务停机的时候，自动下线，

**Comment by yu199195** [comment]
没有强制你，如果你不是使用zookeeper注册，请使用-Dsoul.register=false

**Comment by wxp732826840** [comment]
> 这个意思是你服务的ip+端口需要自动注册，服务停机的时候，自动下线，



> 这个意思是你服务的ip+端口需要自动注册，服务停机的时候，自动下线，

这个地方不借助第三方工具自动注册是应该的
自动下线可以使用心跳机制，也不需要借助zookeeper这样的机制啊

咱2.1有一个很大的改进就是提供了摆脱对第三方工具的严重依赖，这个地方自动注册和下线 要借助zookeeper，那么对于 本身系统没有引入zookeeper的系统，整体上感觉没那么好

只是我个人一点点的意见，

**Comment by wxp732826840** [comment]
> 没有强制你，如果你不是使用zookeeper注册，请使用-Dsoul.register=false

明白了 谢谢   我再试一下
