### ISSUE TITLE
文件上传报错 DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144

### ISSUE THREAD

**Issue by whiledevil** [Dromara/soul#167]
Spring 版本 5.2.4.RELEASE
soul 版本 2.1.2-RELEASE

FileSizeFilter 会自行创建 DataBufferDecoder，不会使用 Spring 创建的 DataBufferDecoder对象，导致spring.codec.max-in-memory-size 设置无法解决该报错问题。
这种情况该如何解决？

**Comment by yu199195** [comment]
请在soul里面指定 配置文件里面加行 file.size = 100  单位是mb

**Comment by whiledevil** [comment]
> 请在soul里面指定 配置文件里面加行 file.size = 100 单位是mb

设置成100没有用，报错上传文件并没有超过默认的10mb，报错地点是 LimitedDataBufferList 不是FileSizeFilter 的文件大小判断。

**Comment by yu199195** [comment]
目标接口的的controller写法，不是 File接收吗

**Comment by whiledevil** [comment]
> 目标接口的的controller写法，不是 File接收吗
接口代码如下
    /**
     * 文件上传接口
     */
    @RequestMapping("/upload")
    @SoulClient(path = "/file/upload", desc = "文件上传接口")
    public ResponseMap fileUpload(@RequestParam("file") MultipartFile file) throws BizException {
        return fileService.upload(file);
    }

**Comment by whiledevil** [comment]
> 目标接口的的controller写法，不是 File接收吗

接口代码如下

    @RequestMapping("/upload")
    @SoulClient(path = "/file/upload", desc = "文件上传接口")
    public ResponseMap fileUpload(@RequestParam("file") MultipartFile file, @RequestParam(value = "caseId", required = false) Long caseId) throws IOException, BizException {
        return fileService.upload(file, caseId);
    }

**Comment by yu199195** [comment]
那应该没问题的，postMan 测试下，是不是通过body，设置了file上传模式

**Comment by whiledevil** [comment]
> 那应该没问题的，postMan 测试下，是不是通过body，设置了file上传模式

降级 Spring 版本到 5.2.0.RELEASE 就不会有该问题。 
5.2.0.RELEASE以上所有版本都会报错。
与下面问题应该是同一个原因，但我无法通过修改 FileSizeFilter 中的 messageReaders，来解决该问题。
[https://github.com/spring-projects/spring-framework/issues/23961](url)

**Comment by chyhub** [comment]
> > 那应该没问题的，postMan 测试下，是不是通过body，设置了file上传模式
> 
> 降级 Spring 版本到 5.2.0.RELEASE 就不会有该问题。
> 5.2.0.RELEASE以上所有版本都会报错。
> 与下面问题应该是同一个原因，但我无法通过修改 FileSizeFilter 中的 messageReaders，来解决该问题。
> [spring-projects/spring-framework#23961](https://github.com/spring-projects/spring-framework/issues/23961)
大佬，你上传还有问题吗？我遇到个io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1 的问题，你上传没遇到吗

**Comment by yu199195** [comment]
已经在master修护

**Comment by gaoweicong** [comment]
这个问题解决了吗？ 在 2.2.1版本还是会报错

**Comment by dengliming** [comment]
master上面修复了的 可以试下 还没发release版本

**Comment by leohou0430** [comment]
use master branch code, it's still throw exception.
Exceeded limit on max bytes to buffer : 262144
