### ISSUE TITLE
修改后端管理页面新增菜单，如何操作

### ISSUE THREAD

**Issue by tian6318** [Dromara/soul#174]
想做二次开发新增功能，发现前端业务无从下手，请问采用的额什么框架，如何开发

**Comment by yu199195** [comment]
这是前端的技术问题，找到前端源代码去研究吧

**Comment by tian6318** [comment]
这块能给个提醒，因为线下想加配置菜单，发现，貌似整个页面都是在index.js里渲染，现在不知道权限控制，页面菜单怎么做上去，这边当时开发采用的是什么研发框架，不然二次开发为了统一，需要把整个前端都替换掉。

**Comment by tian6318** [comment]
现在问题就是，后端其实文档足够详细了，但是要改后台配置，这些，看了一天，无从下手
