### ISSUE TITLE
soul对dubbo接口，多参数实现

### ISSUE THREAD

**Issue by springMonton** [Dromara/soul#177]
定义多参数实现类MultipleGenericParamResolveServiceImpl，实现GenericParamResolveService接口

目前能支持多参数类型：

> 基本类型、集合、Map、JavaBean .....
List<JavaBean>、Map<String, JavaBean>

**Comment by springMonton** [comment]
@yu199195 代码已提交pr，如有问题再沟通讨论吧。

**Comment by yu199195** [comment]
已经合并了

**Comment by CCLooMi** [comment]
这个多参数实现方式问题很多啊。太过复杂而且性能和内存消耗大，还做了很多无用功。
1.光是parameterTypes就转换了多次，内存多次copy
2.对于基础类型的转换处理是没有必要的，dubbo泛化调用在传输时没有必要知道参数是什么类型而且最终传输时这些类型信息还会再次丢失，至于需要parameterTypes是为了能够定位到对应的method
附上简洁实现
private Logger log = LoggerFactory.getLogger(getClass());

	@SuppressWarnings("unchecked")
	@Override
	public Pair<String[], Object[]> buildParameter(final String body, final String parameterTypes) {
		ObjectMapper om = new ObjectMapper();
		String[] ptypes=parameterTypes.split(",");
		Object[] params=new Object[ptypes.length];
		if(ptypes.length>0) {
			try {
				Object o = om.readValue(body, Object.class);
				if (o instanceof List) {
					((List<Object>) o)
					.stream()
					.limit(ptypes.length)
					.collect(Collectors.toList())
					.toArray(params);
				} else {
					params[0]=o;
				}
			} catch (Exception e) {
				log.warn("body[{}] parsing failed cause by[{}]", body, e.getMessage());
			}
		}
		return new ImmutablePair<>(ptypes, params);
	}

**Comment by springMonton** [comment]
> 这个多参数实现方式问题很多啊。太过复杂而且性能和内存消耗大，还做了很多无用功。
> 1.光是parameterTypes就转换了多次，内存多次copy
> 2.对于基础类型的转换处理是没有必要的，dubbo泛化调用在传输时没有必要知道参数是什么类型而且最终传输时这些类型信息还会再次丢失，至于需要parameterTypes是为了能够定位到对应的method
> 附上简洁实现
> private Logger log = LoggerFactory.getLogger(getClass());
> 
> ```
> @SuppressWarnings("unchecked")
> @Override
> public Pair<String[], Object[]> buildParameter(final String body, final String parameterTypes) {
> 	ObjectMapper om = new ObjectMapper();
> 	String[] ptypes=parameterTypes.split(",");
> 	Object[] params=new Object[ptypes.length];
> 	if(ptypes.length>0) {
> 		try {
> 			Object o = om.readValue(body, Object.class);
> 			if (o instanceof List) {
> 				((List<Object>) o)
> 				.stream()
> 				.limit(ptypes.length)
> 				.collect(Collectors.toList())
> 				.toArray(params);
> 			} else {
> 				params[0]=o;
> 			}
> 		} catch (Exception e) {
> 			log.warn("body[{}] parsing failed cause by[{}]", body, e.getMessage());
> 		}
> 	}
> 	return new ImmutablePair<>(ptypes, params);
> }
> ```

关于你提到的2个问题，我说一下自己的想法：
1.关于parameterTypes转换多次，我的代码中针对parameterType进行基本类型，数组、集合、Map的判断，但有效处理逻辑其实只有一行代码，为什么要判断这么多呢? 
首先，我想通过代码让编码者了解，目前这个代码能处理到的场景（能支持的参数类型）。
其次，这个多参数处理的代码，目前能覆盖的用例场景有限（test-dubbo-service已写用例），一些考虑不到的参数类型后期可能需要再处理。

2.关于你提供出来的代码，你可以通过test-dubbo-service用例，验证一下代码的正确性。我本地跑了一下你的代码，很多类型是不支持的。你可以继续优化，然后覆盖用例提供出来。

如你有更好的想法和代码实现，欢迎你提供出来共享。

**Comment by yu199195** [comment]
多个和单个是不是可以合并？ 可以合并一个完整版的出来，太复杂的很难支持的，比较没有dubbo的api包，不能通过反射的方式去获取参数列表

**Comment by CCLooMi** [comment]
经过测试是split方法返回了空字符数组导致的，下面是修复后的代码，全部测试用例都跑过了。
private Logger log = LoggerFactory.getLogger(getClass());

	@SuppressWarnings("unchecked")
	@Override
	public Pair<String[], Object[]> buildParameter(final String body, final String parameterTypes) {
		ObjectMapper om = new ObjectMapper();
		String[] ptypes = splitParameterTypes(parameterTypes);
		Object[] params = new Object[ptypes.length];
		if (ptypes.length > 0) {
			try {
				Object o = om.readValue(body, Object.class);
				if (o instanceof List) {
					((List<Object>) o)
					.stream()
					.limit(ptypes.length)
					.collect(Collectors.toList())
					.toArray(params);
				} else {
					params[0] = o;
				}
			} catch (Exception e) {
				log.warn("body[{}] parsing failed cause by[{}]", body, e.getMessage());
			}
		}
		return new ImmutablePair<>(ptypes, params);
	}
	//自己手写分割函数
	private String[] splitParameterTypes(String parameterTypes) {
		parameterTypes=parameterTypes.trim();
		if(parameterTypes.length()==0) {
			return new String[0];
		}
		List<String>ls=new ArrayList<>();
		StringBuilder sb=new StringBuilder();
		int pL=parameterTypes.length();
		for(int i=0;i<pL;i++) {
			if(parameterTypes.charAt(i)!=',') {
				sb.append(parameterTypes.charAt(i));
			}else if(sb.length()>0) {
				ls.add(sb.toString());
				sb.delete(0, sb.length());
			}
		}
		if(sb.length()>0) {
			ls.add(sb.toString());
		}
		String[]ss=new String[ls.size()];
		ls.toArray(ss);
		return ss;
	}

**Comment by springMonton** [comment]
> 经过测试是split方法返回了空字符数组导致的，下面是修复后的代码，全部测试用例都跑过了。
> private Logger log = LoggerFactory.getLogger(getClass());
> 
> ```
> @SuppressWarnings("unchecked")
> @Override
> public Pair<String[], Object[]> buildParameter(final String body, final String parameterTypes) {
> 	ObjectMapper om = new ObjectMapper();
> 	String[] ptypes = splitParameterTypes(parameterTypes);
> 	Object[] params = new Object[ptypes.length];
> 	if (ptypes.length > 0) {
> 		try {
> 			Object o = om.readValue(body, Object.class);
> 			if (o instanceof List) {
> 				((List<Object>) o)
> 				.stream()
> 				.limit(ptypes.length)
> 				.collect(Collectors.toList())
> 				.toArray(params);
> 			} else {
> 				params[0] = o;
> 			}
> 		} catch (Exception e) {
> 			log.warn("body[{}] parsing failed cause by[{}]", body, e.getMessage());
> 		}
> 	}
> 	return new ImmutablePair<>(ptypes, params);
> }
> //自己手写分割函数
> private String[] splitParameterTypes(String parameterTypes) {
> 	parameterTypes=parameterTypes.trim();
> 	if(parameterTypes.length()==0) {
> 		return new String[0];
> 	}
> 	List<String>ls=new ArrayList<>();
> 	StringBuilder sb=new StringBuilder();
> 	int pL=parameterTypes.length();
> 	for(int i=0;i<pL;i++) {
> 		if(parameterTypes.charAt(i)!=',') {
> 			sb.append(parameterTypes.charAt(i));
> 		}else if(sb.length()>0) {
> 			ls.add(sb.toString());
> 			sb.delete(0, sb.length());
> 		}
> 	}
> 	if(sb.length()>0) {
> 		ls.add(sb.toString());
> 	}
> 	String[]ss=new String[ls.size()];
> 	ls.toArray(ss);
> 	return ss;
> }
> ```
