### ISSUE TITLE
soul对于zk是强依赖吗？不用可以吗

### ISSUE THREAD

**Issue by whbq** [Dromara/soul#182]
soul对于zk是强依赖吗？不用可以吗

**Comment by yu199195** [comment]
你从哪里得知是强依赖zk？

**Comment by whbq** [comment]
额，抱歉哈，我看了下，我之前在一个fork的版本看到的。



在 2020-04-11 10:19:39，"xiaoyu" <notifications@github.com> 写道：

你从哪里得知是强依赖zk？
