### ISSUE TITLE
soul配置为nacos时，服务元数据暴露不完整

### ISSUE THREAD

**Issue by robin977** [Dromara/soul#183]
soul配置为nacos时，当客户端采用@SoulClient将controller暴露出去时，souladmin接收到元数据时
，没有完整的同步到nacos的配置中心
NacosDataChangedListener的onMetaDataChanged方法中
	case REFRESH:
		case MYSELF:
			Set<String> set=new HashSet<>(META_DATA.keySet());
			changed.stream().forEach(meta->set.remove(meta.getPath()));
			META_DATA.keySet().removeAll(set);
                         break;
中应该改为
changed.stream().forEach(meta->{
				set.remove(meta.getPath());
				META_DATA.put(meta.getPath(),meta);
			});
META_DATA.keySet().removeAll(set);

**Comment by yu199195** [comment]
@CCLooMi

**Comment by robin977** [comment]
没看懂这是什么意思

**Comment by CCLooMi** [comment]
@robin977 这个问题在上周已经修复了呢
