### ISSUE TITLE
soul配置为nacos，服务下线时，soul admins未感知

### ISSUE THREAD

**Issue by robin977** [Dromara/soul#185]
soul admins配置为nacos，当某个服务下线时，zk注册中心的soul.regsitrer目录就会删除的相应的ip记录
但是soul admins的upstreamCacheManager缓存 并未感知到某个节点已经下线
当调用时，有可能还是调用到不可用的服务

**Comment by yu199195** [comment]
soul admin 并没有什么upstreamCacheManager 之类的东西

**Comment by yu199195** [comment]
soul 和nacos没有任何关系，你使用下其他的同步策略？

**Comment by robin977** [comment]
zookeeper同步策略是可以

**Comment by robin977** [comment]
我的意思，可不可以做到像alibaba springcloud实现EnableDiscoveryClient一样，把当前的应用soul.http.appName注册到nacos

**Comment by yu199195** [comment]
http的ip端口注册，并没有去支持naocs，

**Comment by CCLooMi** [comment]
@robin977 让nacos自动感知到服务下线可以做到。问题是，如果你有多个相同服务做负载均衡呢？当一个节点下线导致配置被清空就不好了，所以还需要判断同一个服务的所有client是否下线。但是这个逻辑好像已经违背了配置中心的初衷了。配置中心的数据居然被这些client控制！

**Comment by CCLooMi** [comment]
@robin977 但是dubbo的元数据配置并不关心有多少个client，而且这些配置也不应该由这些client控制。如果这些配置由client来控制，那还存数据库干吗，还提供编辑操作干嘛呢？
