### ISSUE TITLE
springcloud用户接入插件匹配

### ISSUE THREAD

**Issue by jackalyuan** [Dromara/soul#194]
1，org.dromara.soul.web.handler.SoulWebHandler.execute() 进行插件过滤时会对当前加载的所有SoulPlugin进行逐一匹配，
2，如果当前的rpctype=springCloud，在执行org.dromara.soul.web.plugin.http.WebClientPlugin.skip() 返回false ，则会执行org.dromara.soul.web.plugin.http.WebClientPlugin 的execute（）方法。
3 由于String urlPath = exchange.getAttribute(Constants.HTTP_URL); 为空，导致CANNOT_FIND_URL(-106, "未能找到合适的调用url,请检查你的配置!")

**Comment by yu199195** [comment]
springCloud插件未配置开启？ 或者配置就不对？

**Comment by jackalyuan** [comment]
开启了，配置使用的是应用启动时初始化的配置

**Comment by jackalyuan** [comment]
配置开启了，使用的是WebSocket 方式同步配置，配置信息都有同步，就是没有springcloud 插件的配置。 上报的信息时通过@soulclient 自行上报上去的

**Comment by yu199195** [comment]
哪个版本，数据库有没有？

**Comment by jackalyuan** [comment]
数据库有，2.1.2-RELEASE

**Comment by yu199195** [comment]
跑的是demo么

**Comment by jackalyuan** [comment]
soul-test 里面的 springcloud

**Comment by yu199195** [comment]
自己好好研究下吧

**Comment by chyhub** [comment]
> 自己好好研究下吧

我也遇到这个问题，soul-bootstrap启动网关，不会加载SpringCloudConfiguration，这样就没有注入SpringCloudPlugin
