### ISSUE TITLE
sign插件开启，restful风格存在问题

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#195]
sign插件开启，restful风格的url 如：localhost:9195/http/test/path/123/name

在进行path认证的时候，匹配不上，因为缓存中是/http/test/path/**/name

**Comment by yu199195** [comment]
应该是可以匹配的，使用的哪个版本

**Comment by java-Learner-lx** [comment]
2.1.2版本，但不是最新的代码

**Comment by yu199195** [comment]
master分支应该可以

**Comment by java-Learner-lx** [comment]
好，我试试
