### ISSUE TITLE
建议：admin模块增加环境支持，多套网关服务对应同一个控制台服务

### ISSUE THREAD

**Issue by AngryApe** [Dromara/soul#197]
企业开发流程往往涉及到多个环境，涉及到配置功能，多个环境之间可以方便的同步配置数据，避免重复配置

**Comment by yu199195** [comment]
你有什么好的方案吗，它只是一个springboot的应用

**Comment by AngryApe** [comment]
以我司为例，环境分为4套：开发->预发->线上->日常，配合多版本控制（主要是开发环境会存在多个项目并行的情况），同时服务端通过Spring的多数据源方案实现多环境的配置发布

**Comment by yu199195** [comment]
请问下你们的admin后台，可以操作不同环境的服务吗？ 如何切换的？ 不需要部署多个吗？

比如你有一个商品微服务的后台，部署一个？ 然后操作各种环境的吗，
