### ISSUE TITLE
并发高时，频繁出现Connection prematurely closed BEFORE response或者connection observed an error

### ISSUE THREAD

**Issue by zhang145926** [Dromara/soul#198]
在2.1.1 版本中，并发稍微高时，就会频繁出现以下两个错误
Connection prematurely closed BEFORE response
connection observed an error

**Comment by zhang145926** [comment]
经过排查，是由于reactor-netty低版本（默认0.8.4）中bug引起，具体原因请查看
https://github.com/reactor/reactor-netty/issues/498
https://blog.csdn.net/songjinbin/article/details/103537581
解决办法
将spring-boot-starter-parent版本升级至2.2.1及以上
但是升级到此版本中还会有以下几个问题：
1.soul-web中NettyHttpClientPlugin类中有冲突，需要改成
![image](https://user-images.githubusercontent.com/19919824/81521069-bf1e1600-9378-11ea-8b02-e818eabc36eb.png)
2.上传文件时提示dataSize最大支持262144字节
在soul-web中FileSizeFilter中，修改如下
![image](https://user-images.githubusercontent.com/19919824/81521212-1d4af900-9379-11ea-8021-089033327e99.png)
注意：不要相信网上各种配置，不起作用

3. heathFilter代码冲突
暂时没有找到解决方案，去掉不影响业务功能，所以可以先去掉该类，在soul-bootstrap中去掉该类即可
注：所有找到解决办法的，继续跟帖回复，多谢指教

**Comment by yu199195** [comment]
very good。

**Comment by zhang145926** [comment]
补充说明：
升级到2.2.1以以上版本，在soul-web中NettyHttpClientPlugin中冲突地方，去掉了以下代码
`nettyOutbound.options(NettyPipeline.SendOptions::flushOnEach)`，
猜测该段代码的作用可能是flush每次请求管道的，但是升级后暂时没有找到替代方法（或许新版默认会flush，无需显式设置），所以直接去掉了，暂时不影响调用
若有人找到替代方式，烦请告知
