### ISSUE TITLE
soul-admin能感知服务下线吗？

### ISSUE THREAD

**Issue by wtlihao** [Dromara/soul#203]

**Comment by yu199195** [comment]
取决于你如何使用

**Comment by wtlihao** [comment]
> 取决于你如何使用

就是soul-admin配置了zk，自己项目也配置了zk，但是服务下线的时候，后台还是显示在。

**Comment by yu199195** [comment]
请详细的描述下，不然没人懂你什么意思

**Comment by wtlihao** [comment]
> 请详细的描述下，不然没人懂你什么意思

一般是怎么配置才能让soul-admin后台系统看到服务下线

**Comment by wtlihao** [comment]
> 取决于你如何使用

我们在自己的工程中是通过@SoulClient注解放到Controller暴露出去的，启动工程成功之后，然后后台上可以看到有一个网关接口，然后再停掉服务，soul-admin后台还是能看到

**Comment by yu199195** [comment]
自己的工程中，配置使用zk注册，soul-admin也配置上zk注册就行了，具体的看文档

**Comment by wtlihao** [comment]
> 自己的工程中，配置使用zk注册，soul-admin也配置上zk注册就行了，具体的看文档

按照文档配置了soul-admin中的zk.register为true，并且配置了zk的地址，同时在自己的工程的配置了zk的地址，可以自动配置了divide，但是还是会有服务下线了，有元数据不会删除的情况

**Comment by yu199195** [comment]
>按照文档配置了soul-admin中的zk.register为true，并且配置了zk的地址，同时在自己的工程的配置了zk的地址，可以自动配置了divide，但是还是会有服务下线了，有元数据不会删除的情况


元数据并不会删除， 不知道你说的删除，到底是什么没删除？ ip 端口？

**Comment by wtlihao** [comment]
> > 按照文档配置了soul-admin中的zk.register为true，并且配置了zk的地址，同时在自己的工程的配置了zk的地址，可以自动配置了divide，但是还是会有服务下线了，有元数据不会删除的情况
> 
> 元数据并不会删除， 不知道你说的删除，到底是什么没删除？ ip 端口？

>你好，我认为的元数据也会删除的。那明白了，也就是soul-admin元数据是持久化的并且不会删除，然后会把服务状态的情况会告知soul-bootstrap。
