### ISSUE TITLE
关于duboo泛化，admin后台接口映射如何配置

### ISSUE THREAD

**Issue by xiangyang-gao** [Dromara/soul#208]
*映射

![2](https://user-images.githubusercontent.com/15973635/82291108-f3c64900-99da-11ea-90ac-f51deac97d3a.png)

如图，如果入参是byte[]，应该如何配置

**Comment by yu199195** [comment]
看不到图

**Comment by zuowenmou** [comment]
> 看不到图

那我描述下目录到功能

接口映射-->添加数据-->(弹框)接口映射页面-->*映射 这一列该如何配置入参的类型和名字

服务提供者接口例子1：
public void test(long a);
映射配置参数为：java.lang.long      java.lang.long  顺序   key名称 

服务提供者接口举例2：
public void test(byte[] bytes);
映射配置参数为：?

**Comment by zuowenmou** [comment]
> 看不到图

您好，不知道这样我是否讲明白

**Comment by yu199195** [comment]
那不就是byte类型吗。，没见过使用byte[] 类型的接口

**Comment by zuowenmou** [comment]
> 那不就是byte类型吗。，没见过使用byte[] 类型的接口

如果再配置页面配置 byte，则不会传递下去

**Comment by yu199195** [comment]
看到你的图了，你这个后台不是soul的吧
