### ISSUE TITLE
POST请求传参问题

### ISSUE THREAD

**Issue by chyhub** [Dromara/soul#210]
http用户请求，post方式接收不到参数
    @PostMapping("/posttest1")
    @SoulClient(path = "/test/posttest1", desc = "测试post请求入参")
    public String posttest1(String id, String name) {
        return id+","+name;
    }

如果加上RequestParam 就会报错：
Required String parameter 'id' is not present

**Comment by yu199195** [comment]
能否看下demo呢？  RequestParam  加上这个，你知道postman是怎么传的吗

**Comment by chyhub** [comment]
> 能否看下demo呢？ RequestParam 加上这个，你知道postman是怎么传的吗
> 
> 不要通过网关，你是怎么调用的， 如果ok证明，你的调用是正常的

json格式传不过去，id=1&name=test 这样就可以过去

**Comment by yu199195** [comment]
> json格式传不过去，id=1&name=test 这样就可以过去
json格式难道不是应该用对象接收吗，这些都是基本的常识，有个基本的原则，你先别经过网关去调用，如果是正常的，证明你的调用是正常
