### ISSUE TITLE
同一 meta_data的一个selector有多个rule的情况 服务注册admin报错

### ISSUE THREAD

**Issue by qiyunfei** [Dromara/soul#213]
[https://github.com/Dromara/soul/blob/master/soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java](url)

` handlerRule`方法
`RuleDO existRule = ruleMapper.findByName(metaDataDTO.getPath());`
如果metaDataDTO.getPath() 这个数据通过后台自己加了多个rule，这里注册的时候会报错

报错的关键信息
`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2`

`at org.dromara.soul.admin.service.impl.MetaDataServiceImpl.handlerRule(MetaDataServiceImpl.java:269) ~[classes/:na]`
 
这个 貌似没有考虑同一 meta_data的一个selector有多个rule的情况？？？
看逻辑selector 如果同一meta_data 有多个selector 也存在同样的问题？？

**Comment by yu199195** [comment]
metada_data 在设计里面已经是接口，最小的单位，你啥场景，需要一个metadata有多种选择器？

**Comment by qiyunfei** [comment]
大佬，我只是看到selector下可以新增规则，于是乎我加了一个同名rule，同一个selector可以对应多个rule，这个是允许的吧？那同一个selector下就可以建立两个同名的rule（条件可以不一样），那就会存在我说的问题吧？ metadata对应多个selector，也只是 我看形式上是允许 我这么做的，所以 我觉得逻辑上也会有一样的问题

**Comment by qiyunfei** [comment]
这里 没有限制 rule 和 selector 可以增加同名的，如果由于某些原因（可能是手动添加的，可能是执行sql添加的，也可能并发了插入了多条（这个我没验证）只是猜测可能有这种可能）产生了同名的rule 或者selector ,是不是就有 我说的问题呢？

**Comment by yu199195** [comment]
可以新增一个判断，不能容许同名的

**Comment by qiyunfei** [comment]
那可不可以 搞成支持同名的呢？

**Comment by yu199195** [comment]
>那可不可以 搞成支持同名的呢？
同名有啥好处？

**Comment by qiyunfei** [comment]
针对同一个资源，不同的调用方可以有不同的配置，比如超时这种？
