### ISSUE TITLE
报错 413 Request Entity Too Large

### ISSUE THREAD

**Issue by d1jk** [Dromara/soul#214]
你好，请问一下：可以在哪里设置请求实体的大小？

**Comment by yu199195** [comment]
不懂什么意思

**Comment by d1jk** [comment]
比如，nginx 中： client_max_body_size 具体的大小值，默认为1m; 可调整大小。

不知道这个网关里，是否也有对应的地方，去配置。

具体问题是：
请求参数超长时，报错 413 Request Entity Too Large。

**Comment by yu199195** [comment]
没有场景，和错误信息，没办法知道

**Comment by d1jk** [comment]
![71590398918_ pic_hd](https://user-images.githubusercontent.com/12113165/82799965-72c0f300-9ead-11ea-9e76-eb81be823fb3.jpg)

比如上面这个

**Comment by d1jk** [comment]
springboot项目

**Comment by yu199195** [comment]
看不到图，应该是上传文件，图片等等的问题

**Comment by d1jk** [comment]
并不是上传，只是参数值过长。

比如：
{{host}}/dict/list?categoryId=101001&codes=12285340344,12285340344,12285340345,12285340346,12285340347,12285340348,12285341,12285342,12286,12286349,12286349355,12286349356,12286349357,12286349358,12286349359,12286349360,12286350,12286350361,12286350362,12286350363,12286351,12286351364,12286351365,12286351366,12286351367,12286351368,12286351369,12286351370,12286352,12286352371,12286352372,12286352373,12286352374,12286352375,12286352376,12286352377,12286353,12286354,13,13378,13378381,13378381387,13378381388,13378381389,13378381390,13378381391,13378381392,13378381393,13378381394,13378381395,13378382,13378382396,13378382397,13378382398,13378382399,13378382400,13378382401,13378383,13378383402,13378383403,13378383404,13378383405,13378383406,13378383407,13378383408,13378383409,13378383410,13378383411,13378383412,13378384,13378384413,13378384414,13378384415,13378385,13378385416,13378385417,13378385418,13378385419,13378385420,13378386,13379,13379421,13379421426,13379421427,12285340344,12285340345,12285340346,12285340347,12285340348,12285341,12285342,12286,12286349,12286349355,12286349356,12286349357,12286349358,12286349359,12286349360,12286350,12286350361,12286350362,12286350363,12286351,12286351364,12286351365,12286351366,12286351367,12286351368,12286351369,12286351370,12286352,12286352371,12286352372,12286352373,12286352374,12286352375,12286352376,12286352377,12286353,12286354,13,13378,13378381,13378381387,13378381388,13378381389,13378381390,13378381391,13378381392,13378381393,13378381394,13378381395,13378382,13378382396,13378382397,13378382398,13378382399,13378382400,13378382401,13378383,13378383402,13378383403,13378383404,13378383405,13378383406,13378383407,13378383408,13378383409,13378383410,13378383411,13378383412,13378384,13378384413,13378384414,13378384415,13378385,13378385416,13378385417,13378385418,13378385419,13378385420,13378386,13379,13379421,13379421426,13379421427,12285340344,12285340345,12285340346,12285340347,12285340348,12285341,12285342,12286,12286349,12286349355,12286349356,12286349357,12286349358,12286349359,12286349360,12286350,12286350361,12286350362,12286350363,12286351,12286351364,12286351365,12286351366,12286351367,12286351368,12286351369,12286351370,12286352,12286352371,12286352372,12286352373,12286352374,12286352375,12286352376,12286352377,12286353,12286354,13,13378,13378381,13378381387,13378381388,13378381389,13378381390,13378381391,13378381392,13378381393,13378381394,13378381395,13378382,13378382396,13378382397,13378382398,13378382399,13378382400,13378382401,13378383,13378383402,13378383403,13378383404,13378383405,13378383406,13378383407,13378383408,13378383409,13378383410,13378383411,13378383412,13378384,13378384413,13378384414,13378384415,13378385,13378385416,13378385417,13378385418,13378385419,13378385420,13378386,13379,13379421,13379421426,13379421427,12285340344,12285340345,12285340346,12285340347,12285340348,12285341,12285342,12286,12286349,12286349355,12286349356,12286349357,12286349358,12286349359,12286349360,12286350,12286350361,12286350362,12286350363,12286351,12286351364,12286351365,12286351366,12286351367,12286351368,12286351369,12286351370,12286352,12286352371,12286352372,12286352373,12286352374,12286352375,12286352376,12286352377,12286353,12286354,13,13378,13378381,13378381387,13378381388,13378381389,13378381390,13378381391,13378381392,13378381393,13378381394,13378381395,13378382,13378382396,13378382397,13378382398,13378382399,13378382400,13378382401,13378383,13378383402,13378383403,13378383404,13378383405,13378383406,13378383407,13378383408,13378383409,13378383410,13378383411,13378383412,13378384,13378384413,13378384414,13378384415,13378385,13378385416,13378385417,13378385418,13378385419,13378385420,13378386,13379,13379421,13379421426,13379421427,12285340344,12285340345,12285340346,12285340347,12285340348,12285341,12285342,12286,12286349,12286349355,12286349356,12286349357,12286349358,12286349359,12286349360,12286350,12286350361,12286350362,12286350363,12286351,12286351364,12286351365,12286351366,12286351367,12286351368,12286351369,12286351370,12286352,12286352371,12286352372,12286352373,12286352374,12286352375,12286352376,12286352377,12286353,12286354,13,13378,13378381,13378381387,13378381388,13378381389,13378381390,13378381391,13378381392,13378381393,13378381394,13378381395,13378382,13378382396,13378382397,13378382398,13378382399,13378382400,13378382401,13378383,13378383402,13378383403,13378383404,13378383405,13378383406,13378383407,13378383408,13378383409,13378383410,13378383411,13378383412,13378384,13378384413,13378384414,13378384415,13378385,13378385416,13378385417,13378385418,13378385419,13378385420,13378386,13379,13379421,13379421426,13379421427


这样调用网关，当codes参数值过长时，会有这种问题（413 request entity too large）。

虽然可以通过把参数放到body里面解决，但想着或许网关里面某个地方可以配置上面参数的传值长度，使得可以像上面那样传参（即便参数值比较长）

**Comment by willfenglover** [comment]
我也遇到这个问题了，报错（413 request entity too large），调整了 divide 插件 Rules 中的 requestMaxSize 大小，但是没有用。
