### ISSUE TITLE
dubbo 传基本类型数组参数 问题

### ISSUE THREAD

**Issue by qiyunfei** [Dromara/soul#215]
#177 
@CCLooMi
测试代码的DubboTestServiceImpl
` @Override
    @SoulClient(path = "/queryByArray", desc = "插入一条数据")
    public String queryByArray(Integer[] ids) {
        return "param array:" + ids;
    }
`
传参数  
`[1,2,3]`
结果 
`{
    "code": 500,
    "message": "Internal Server Error"
}`
后台报错
`org.apache.dubbo.rpc.service.GenericException: java.lang.ClassCastException: java.lang.Integer cannot be cast to [Ljava.lang.Integer;
`

`  @Override
    @SoulClient(path = "/queryByStringArray", desc = "插入一条数据")
    public String queryByStringArray(String[] ids) {
        return "param string array" + ids;
    }`
请问大佬 这两个例子是怎么跑过的？我这里无论怎么传参数都会报错啊？如果是我传参数的问题请老哥告知如何传；按照你的逻辑 多参数的传参数是按json数组的形式传，
`[ "133", "233", "3333" ]`分别是第一个参数，第二个参数，第三个参数，但是这两个方法的参数本身就是个array,那得怎么传参数呢？
 按照@springMonton 大佬的逻辑 我可以跑过这些例子
 
 @yu199195 大佬也看看 这里的逻辑 测试看看 是否有问题呢？我会提了一个pr修复一下这个看看合理不

**Comment by qiyunfei** [comment]
pr 
#216

**Comment by key1012** [comment]
你调用dubbo时候  body传值能获取到吗？

**Comment by qiyunfei** [comment]
> 你调用dubbo时候 body传值能获取到吗？

先把你的dubbo的接口发出来看看，然后你用的soul的代码版本是最新版吗？然后dubbo参数解析配置是多参数的？还是没配置？

**Comment by bert82503** [comment]
参数构建机制，对于任何类型的入参，都是通过`JSON.parseObject(body)`先解析为`JSONObject paramJson`。
这样，当入参是一个数组列表类型时，就会抛出JSON对象解析异常。

<img width="1327" alt="Image" src="https://github.com/user-attachments/assets/b5b9aeb7-5861-46f4-8fca-3a2c9e1395c5" />

【解法】
把数组列表类型的入参，当做一个整体的字符串传入，不做解析。

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/af583d99-e1e9-4c2a-add6-f145ce539225" />
