### ISSUE TITLE
集成dubbo的soulClient注解 能否支持请求方式的处理？

### ISSUE THREAD

**Issue by lyh19940304** [Dromara/soul#217]
不添加请求方式的属性的话   无法构建restful风格的url...

**Comment by yu199195** [comment]
不是很明白你的意思

**Comment by lyh19940304** [comment]
> 不是很明白你的意思

就是soulClient这个注解 只有url,换句话说  用户的CRUD就需要4个不同的url
没有办法构建 Post增 Delete删 Put改 Get查   同一个url   restful   ？？？

**Comment by yu199195** [comment]
增删改查方法签名不一样，元数据也不一样，没办法通过一个url来调用dubbo的服务

**Comment by soho2019-bit** [comment]
可否增加请求方式，加入到签名规则里面去， 这样不同url 有不同请求方式， 也是不同元数据
