### ISSUE TITLE
dubbo调用时候body数据为空，导致报错

### ISSUE THREAD

**Issue by key1012** [Dromara/soul#218]
dubbo在调用时候，serverRequest.bodyToMono(String.class).switchIfEmpty(Mono.defer(() -> Mono.just(""))) .flatMap(body 
body是空，genericParamResolveService.buildParameter(body, metaData.getParameterTypes());
无参数，导致RPC调用不到。

**Comment by yu199195** [comment]
无参数请传 {}

**Comment by key1012** [comment]
有参数，传了参数，获取不到。我要传参数

**Comment by yu199195** [comment]
仔细看下文档，默认的只支持，json对象，参数是javabean对象，明白吗

**Comment by key1012** [comment]
我用的全部都是自带的，然后dubbo调用demo里的dubbo/insert  body参数也是{"id":"1234","name":"XIAO5y"}，文档中提供的，然后DubboBodyWebFilter中body获取不到参数的。

**Comment by yu199195** [comment]
are you true？ 这里只是转换成了string字符串，请问你的dubbo接口没有获取到参数吗？

**Comment by key1012** [comment]
是的，没有获取到，所以我很纳闷，执行serverRequest.bodyToMono(String.class)的时候，返回的是 MonoOnErrorResume

**Comment by yu199195** [comment]
>是的，没有获取到，所以我很纳闷，执行serverRequest.bodyToMono(String.class)的时候，返回的是 MonoOnErrorResume

能不能在  if 处打个断点？ 不要问这么无聊的问题
 
```
if (MediaType.APPLICATION_JSON.isCompatibleWith(mediaType)) {
                            exchange.getAttributes().put(Constants.DUBBO_PARAMS, body);
                        }
```

**Comment by key1012** [comment]
打了，如果body是“”，如果吧.switchIfEmpty(Mono.defer(() -> Mono.just(""))去掉，压根不会进入

**Comment by key1012** [comment]
打了，body是“”，如果吧.switchIfEmpty(Mono.defer(() -> Mono.just(""))去掉，压根不会进入

**Comment by yu199195** [comment]
>打了，如果body是“”，如果吧.switchIfEmpty(Mono.defer(() -> Mono.just(""))去掉，压根不会进入

我猜你连postman都不会用， 也许你是get请求？ body 选的不是json模式

**Comment by key1012** [comment]
我不问了，解决问题呢，不是攻击人的。

**Comment by chyhub** [comment]
> 我不问了，解决问题呢，不是攻击人的。

请求头带上  application/json;charset=UTF-8

**Comment by fddOs** [comment]
同问，我是自定义插件，单元测试能拿到body，但是部署之后日志打印为空，但是接口正常转发调用成功了

**Comment by fddOs** [comment]
> 我也遇到body是空的情况
同问，我是自定义插件，单元测试能拿到body，但是部署之后日志打印为空，但是接口正常转发调用成功了，老哥能教教怎么弄嘛
