### ISSUE TITLE
SpringCloudPlugin加载不到的问题

### ISSUE THREAD

**Issue by chyhub** [Dromara/soul#219]
@ConditionalOnClass中的LoadBalancerClient.class找不到，这样就不会实例SpringCloudConfiguration，以及SpringCloudPlugin

@ConditionalOnClass({LoadBalancerClient.class, RibbonAutoConfiguration.class, DispatcherHandler.class})
@AutoConfigureAfter({RibbonAutoConfiguration.class, LocalCacheConfiguration.class})
@ConditionalOnBean(LoadBalancerClient.class)
@EnableDiscoveryClient
@configuration
public class SpringCloudConfiguration {

**Comment by yu199195** [comment]
请引入相关的包就好了，文档不是写的很清楚吗

**Comment by chyhub** [comment]
> 请引入相关的包就好了，文档不是写的很清楚吗

pom文件看错名字了，不好意思
