### ISSUE TITLE
目前soul的稳定版本是master分支吗？镜像仓库下载下来的是master打包的吗？

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#223]

**Comment by yu199195** [comment]
可以使用master分支或者2.1.2

**Comment by java-Learner-lx** [comment]
> 可以使用master分支或者2.1.2

大佬，你的意思是这两个都是稳定版对吧？那么如果我只使用bootstrap工程，从仓库拉下来的是master还是release2. 1. 2分支呢？

**Comment by yu199195** [comment]
都可以。。

**Comment by java-Learner-lx** [comment]
> 都可以。。

大佬，确实没理解。我就问一下
<parent>
        <artifactId>soul</artifactId>
        <groupId>org.dromara</groupId>
        <version>2.1.2-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>soul-spring-boot-starter</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-web</artifactId>
        </dependency>
    </dependencies>

引的包，代码是master还是release2. 1. 2。万分感谢大佬的回答

**Comment by java-Learner-lx** [comment]
> 都可以。。

大佬，确实没理解。我就问一下
<parent>
        <artifactId>soul</artifactId>
        <groupId>org.dromara</groupId>
        <version>2.1.2-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>soul-spring-boot-starter</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-web</artifactId>
        </dependency>
    </dependencies>
引的包，代码是master还是release2. 1. 2。万分感谢大佬的回答

**Comment by java-Learner-lx** [comment]
> 都可以。。
` <dependencies>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-web</artifactId>
            <version>2.1.2-RELEASE</version>
        </dependency>
    </dependencies>`
   这个引包的是master的代码还是release2. 1. 2的代码。如果是2.1.2的代码。我如何引master的代码（还是只能自己打包了），万分感谢大佬回答
