### ISSUE TITLE
master最新代码，http接入，client引哪个

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#229]
master最新代码，soul+http，http项目引哪个client包。我目前引的是
 <groupId>org.dromara</groupId>
            <artifactId>soul-client-springmvc</artifactId>
            <version>2.1.2-RELEASE</version>
但是，重启soul-web之后就报 参数错误，重启soul-web再重启http项目就没问题了。
而且我发现 元数据只有dubbo的信息，没有http的（是不是不正常）
求大佬指教

**Comment by yu199195** [comment]
请不要使用master，你使用2.1.2 就好 了

**Comment by java-Learner-lx** [comment]
> 请不要使用master，你使用2.1.2 就好 了

2.1.2不支持多参数的。扩展也只能改源码。大佬之前你不是说master也是稳定的吗【哭笑】
