### ISSUE TITLE
soul接duboo是否支持同时接alibaba2.5.x和apache2.7.x

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#233]
soul接duboo是否支持同时接alibaba2.5.x和apache2.7.x

因为新的项目 用的是apache2.7.x，目前想要接一个老项目，老项目的dubbo是alibaba2.5.x，可以同时接吗？如果可以 需要不同的插件还是同意哥dubbo插件就可以？求大佬解答。

顺便再问一下，接dubbo集群，zk怎么配置 谢谢

**Comment by yu199195** [comment]
只支持一个

**Comment by java-Learner-lx** [comment]
> 只支持一个

大佬的意思是 就算新增dubbo插件 也不能两个都支持是吗

**Comment by yu199195** [comment]
自己改造一下，也是支持2种方式并存的

**Comment by java-Learner-lx** [comment]
> 自己改造一下，也是支持2种方式并存的

我试了一下，好像可以。反正引得不同的client

**Comment by java-Learner-lx** [comment]
2.1.2 开启dubbo插件，1.apache2.7.x 引入client包，将实现注册到网关，可以成功调用；
1存在前提，alibaba2.5.x引入client包，将实现注册到网关，可以成功调用，并且1情况也是正常的。

2.2.0目前好像不行：
我尝试了两种方式---1 修改alibaba插件的插件名（相当于一个自定义插件），启动都无问题，但是applicationConfig和registryConfig总是null，报错（No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.）。正在尝试。
2.只开启dubbo插件，apache2.7.x 引入apache-client,alibaba2.5.x也引入apache-client,这个有点忘记了，好像是dubbo项目启动报错
