### ISSUE TITLE
2.2.0版本MetricsTrackerFacade空指针

### ISSUE THREAD

**Issue by chyhub** [Dromara/soul#235]
MetricsTrackerFacade的161行 metricsTrackerManager.stop() 这里报空指针，在monitor是关闭的时候，metricsTrackerManager没有注入，直接调用stop()报空

**Comment by java-Learner-lx** [comment]
我遇到了。

**Comment by yu199195** [comment]
应该少了个判断，但是不影响使用吧

**Comment by java-Learner-lx** [comment]
> 应该少了个判断，但是不影响使用吧

还在处理其它问题中，大佬2.2.0的代码看master？还是会拉release

**Comment by chyhub** [comment]
> 应该少了个判断，但是不影响使用吧

使用不影响，就是启动的时候会报空指针，然后会断开websocket，之后会重新连接websocket
