### ISSUE TITLE
访问根路径时报ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JiaRG** [Dromara/soul#237]
访问根路径时path值为`/`，切割后`splitList `为空数组
https://github.com/Dromara/soul/blob/3975186d5bccd042b6efcd7781ae7e661f7152c2/soul-plugin/soul-plugin-global/src/main/java/org/dromara/soul/plugin/global/DefaultSoulContextBuilder.java#L90-L92

**Comment by yu199195** [comment]
你访问根路径是要干嘛

**Comment by JiaRG** [comment]
没干啥😂

**Comment by yu199195** [comment]
你可以修护它吗
