### ISSUE TITLE
自定义插件admin配置config，源码没有预留使用更新的入口，需要自己修改源码

### ISSUE THREAD

**Issue by xuhangsong** [Dromara/soul#240]
希望能提供兼容匹配的友好的方式，不想改源码

//自定义插件配置参数动态更新补充
            Map<String,Object> gson = GsonUtils.getInstance().toObjectMap(pluginData.getConfig());
            CustomSingleton customSingleton = CustomSingleton.getCustomSingletonByName(pluginData.getName());
            if(customSingleton!=null){
                customSingleton.clean();
                //清除原来的参数，防止参数key删除，导致原来的key不到而无法删除
                if(gson!=null&&gson.size()>0){
                    Iterator<String> iterator = gson.keySet().iterator();
                    while(iterator.hasNext()){
                        String key = iterator.next();
                        customSingleton.single(key,gson.get(key));
                    }
                }
            }

**Comment by yu199195** [comment]
啥意思。。

**Comment by xuhangsong** [comment]
没啥，发现新版本修复了这个功能，提供了订阅插件参数接口PluginDataHandler
