### ISSUE TITLE
soul 如何与 k8s ingress 集成，作为集群对外的网关

### ISSUE THREAD

**Issue by gy09535** [Dromara/soul#245]

**Comment by yu199195** [comment]
只是一个部署的问题，谈不上什么集成

**Comment by gy09535** [comment]
嗯..... 我主要想说的是是否可以作为 ingress control ，映射路由规则到 soul ，类似于 kong ingress。作者的意思是否是作为一个服务部署，对外提供服务？

**Comment by yu199195** [comment]
都可以，映射路由规则到 soul 这一步得自己开发

**Comment by gy09535** [comment]
好的，谢谢解答。
