### ISSUE TITLE
2.2.0 手动同步选择器和规则，网关只同步了最后一个选择器规则问题

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#246]
2.2.0 手动同步选择器和规则，网关只同步了最后一个选择器：
造成的原因：admin后台syncPluginData方法，当选择器不为空，同步规则列表是EventType应该为UPDATE而不是REFRESH

**Comment by yu199195** [comment]
REFRESH 不也是同步所有的吗

**Comment by java-Learner-lx** [comment]
如果是REFRESH ，在网关会先clear map，所以只保留了最后一个选择器的规则
