### ISSUE TITLE
接连重启soul-admin、网关服务，divide插件选择器中设置的http配置会被清空

### ISSUE THREAD

**Issue by lwh-0739** [Dromara/soul#251]
divide中选择器：
![image](https://user-images.githubusercontent.com/53554356/86314632-bc45f000-bc5a-11ea-87cf-c88e7e8bf210.png)
先后重启soul-admin、网关服务后：
![image](https://user-images.githubusercontent.com/53554356/86314790-2068b400-bc5b-11ea-8a58-80ccb6d83765.png)

注：单一重启无问题，但只要出现：重启soul-admin -> 重启网关服务，就会重置divide插件选择器中设置的http配置

**Comment by yu199195** [comment]
重启网关服务 是啥意思？ 你的http服务？

**Comment by lwh-0739** [comment]
就是网关，soul-admin源码中提供的soul-bootstrap

**Comment by lwh-0739** [comment]
![image](https://user-images.githubusercontent.com/53554356/86319679-a559ca80-bc67-11ea-8615-cc0ec66512ff.png)

**Comment by yu199195** [comment]
重启网关，和http配置并没有关系， 只会和你真实的服务状态有关系

**Comment by lwh-0739** [comment]
就是说soul-admin在重启时，会验证divide插件选择器中的http配置，如果对应的服务状态有误，会清掉是吗？
刚才的测试目前是这个样子的。
这个逻辑应该在网关中也有吧。

当时提交问题的情况过程是：
rewrite -> divide -> springcloud
rewrite插件重写URL，然后转入divide，最后交由springcloud插件处理请求；此时divide插件选择器中填入的http配置是网关本身的ip与端口。
有个疑问，单独重启网关时，http配置不会清掉，然后重启soul-admin时，数据也不会清掉，最后在重启网关，数据就清掉了，这是为啥？

**Comment by yu199195** [comment]
> 此时divide插件选择器中填入的http配置是网关本身的ip与端口

你是要上天？

**Comment by yu199195** [comment]
> rewrite插件重写URL，然后转入divide，最后交由springcloud插件处理请求

一个url请求会同时走 divide 插件和springcloud插件？

**Comment by lwh-0739** [comment]
不好意思，刚才vps有问题，没连上去。

rewrite重写之后，会执行divide插件，如果此时在rewrite的规则中
![image](https://user-images.githubusercontent.com/53554356/86325282-61b88e00-bc72-11ea-83ad-39d7985678c0.png)

处理写的是springcloud代理的请求，会再再执行springcloud插件。

**Comment by yu199195** [comment]
一个请求为什么会走divide插件，又走springcloud插件？ 你能去搞清楚吗

**Comment by lwh-0739** [comment]
![搜狗截图20200703101815](https://user-images.githubusercontent.com/53554356/86425401-a34f4480-bd17-11ea-8bd8-70a2cea616f3.png)
正常情况下，使用rewrite重写URL，divide插件之后会将请求直接发送至真实服务处理，但此时填入的的springcloud代理的请求，地址是网关本身的ip与端口，所以发送的重写URL进入网关，会重新进入插件链处理，此时会走springcloud插件。

还有就是，咱是不是有点偏题了，我的问题只是divide插件选择器的http配置会根据真实服务的状态进行判断是否重置。
这个只是偶然发现的，就目前来说，没有业务需要进行该过程。

**Comment by yu199195** [comment]
你的问题，我早就已经回答过了，是你说了一些我听不懂的东西

**Comment by lwh-0739** [comment]
好的好的，谢了

**Comment by imtiaotiao** [comment]
@yu199195 经使用测试，发现soul-admin中的自动检测任务会定时检查所代理服务节点的状态，当服务节点不可用时，会将节点摘除。
从原理上来讲，这样是说得通的。但存在的问题时，soul-admin会直接修改数据库中   selector表的handle字段，这个字段是运维人员在后台配置进去的，相当于检测程序直接修改了配置。这样导致的结果就是，只能摘除节点，但无法恢复节点。

建议程序另外维护一个字段handle_active ，存储可用节点列表，检测时使用selector的handle字段，检测结果存在到 handle_active 字段，分发给网关。望采纳。

**Comment by yu199195** [comment]
@imtiaotiao  我不是很明白你说的是运维人员，所配置的业务服务的ip+端口。  难道你们的http服务没有自动的去接入网关吗？
如果你们是这种固定模式，请在admin 配置文件中 新增 soul.upstream.check: false

**Comment by imtiaotiao** [comment]
@yu199195 我理解你说的，如果是springmvc或者springcloud等技术栈的项目，可以通过soul提供的注解实现自动化注册。实际使用中，还会存在其他技术栈的HTTP服务，如Go/Python等。如你所说，类似于nginx固定模式的就只能关闭自动检测了。
看soul的文档中，也提供了 https://dromara.org/zh-cn/docs/soul/dev-client.html  这种针对其他技术栈自定义注册的，这个文档的参数可以更细致些么？需要网关代理的每个接口都需要注册？还是也支持match模式匹配？

**Comment by mrcaobin** [comment]
这个“yu199195”说话跟别人欠他东西一样，牛逼个p啊
