### ISSUE TITLE
新增outh2插件支持

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#253]
网关新增一个outh2插件来执行标准的outh2认证

**Comment by SaberSola** [comment]
具体需求呢,是要做成什么样的,是访问业务客户端的权限,还是用户调用api的权限,这样的话,插件是不是和业务耦合比较大了,就有些类似于登陆接口来获取token的形式了

**Comment by yu199195** [comment]
应该只是一个outh2的认证的，客户端的权限， 类似于kong网关的 outh2插件
