### ISSUE TITLE
英文文档翻译

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#254]
目前只有中文的文档，有英语好的小伙伴可以参与进来，进行翻译。
所有文档在这里：https://gitee.com/shuaiqiyu/website/tree/master/docs/zh-cn/soul

这是官网的文档：https://dromara.org/website/zh-cn/docs/soul/soul.html

翻译后的md文件用 en结尾

*  翻译任务一：
- [x] sou的介绍
- [x] sou团队介绍
- [x] soul数据库设计
- [x] 数据配置流程
- [x] 数据同步原理
- [x] 元数据概念介绍

*  翻译任务二：
- [x] 搭建soul开发环境
- [x] http用户文档
- [x] dubbo用户文档
- [x] springcloud用户文档
- [x] 选择器规则详解
- [x] 数据同步策略

*  翻译任务三：
- [x] divide插件
- [x] dubbo插件
- [x] springcloud插件
- [x] rateLimiter插件
- [x] hystrix插件
- [x] monitor插件
- [x] waf插件
- [x] sign插件
- [x] rewirte插件
- [x] websokcet支持

*  翻译任务四：
- [x] 自定义filter
- [x] 自定义插件
- [x] 文件上传下载
- [x] 自定义解析IP host
- [x] 自定义返回结果
- [x] 自定义签名插件算法
- [x] 多语言http客户端接入
- [x] 线程模型
- [x] soul调优

*  翻译任务五：
- [x] 贡献值指南
- [x] 提交者指南
- [x] 文编码规范

**Comment by yida-lxw** [comment]
Let me give it a shot.

**Comment by strawberry-crisis** [comment]
I am glad to help.

**Comment by fightingting** [comment]
1

**Comment by prospect167** [comment]
2

**Comment by strawberry-crisis** [comment]
4

**Comment by yu199195** [comment]
@fightingting  你来翻译任务一

**Comment by yu199195** [comment]
@strawberry-crisis  你来翻译任务4

**Comment by HoldDie** [comment]
我选择 5

**Comment by 0x12FD16B** [comment]
5

**Comment by yu199195** [comment]
@HoldDie 你来翻译任务5

**Comment by bigwillc** [comment]
3

**Comment by yu199195** [comment]
@bigwillc  你来翻译任务3

**Comment by lasly1990** [comment]
2

**Comment by bigwillc** [comment]
> @bigwillc 你来翻译任务3

好的

**Comment by yu199195** [comment]
@lasly1990 你翻译任务二

**Comment by yu199195** [comment]
@0x12FD16B  任务都满了，你等下翻译下hmily的任务吧，去那边领取

**Comment by prospect167** [comment]
@yu199195 我第一个选择任务2

**Comment by prospect167** [comment]
我还是先本地自己翻译，顺便熟悉一下soul

**Comment by yu199195** [comment]
@prospect167 你翻译一下readme

**Comment by prospect167** [comment]
> @prospect167 你翻译一下readme
收到

**Comment by ChristineLei** [comment]
2.  lasly1990
thanks

**Comment by yu199195** [comment]
所有的文档已经翻译完毕，我会进行部署，感谢大家的努力！
