### ISSUE TITLE
Hystrix插件新增支持线程池模式支持

### ISSUE THREAD

**Issue by yu199195** [Dromara/soul#255]
目前只有信号量的模式支持，需要新增线程池模式，2种方式让用户自己来选择

**Comment by 241600489** [comment]
Can i follow this?

**Comment by yu199195** [comment]
@241600489   欢迎，你可能需要修改soul-admin （配置来源），与hystrix插件，来完成这个pr，如果有任何问题，可以联系我。

**Comment by 241600489** [comment]
好的，我这边基于master 最新代码进行修改是吗

**Comment by yu199195** [comment]
是的，基于master分支改

**Comment by 241600489** [comment]
@yu199195 我遇到一个问题： HystrixObservableCommand.Setter 类 不可以设置  HystrixThreadPoolProperties.Setter 属性，因此如果设置成线程池模式会使用hystrix 默认的 线程池配置，当然也可以使用 在配置文件里配置hystrix 线程池属性，但是这样多个comand 会使用同一份配置；还有就是用户在页面上只设置隔离模式，不需要设置 hystrix 的线程池属性吧

**Comment by yu199195** [comment]
最好的是页面上有个下拉框选择，可以选择信号量还是线程池，如果是线程池，则填写线程池相关字段，反正都是一个json，

然后，自定义相关的类来进行解析，同步，最后使用

**Comment by 241600489** [comment]
@yu199195 经过这几天调研以及实践，发现需要继承hystrix 的HystrixCommand 来实现支持线程池模式，因为HystrixObservableCommand不支持线程池模式，但是HystrixCommand 对webflux支持并不友好，一般使用在封装阻塞式io

**Comment by yu199195** [comment]
应该不会，他应该只是设置上的不同

**Comment by 241600489** [comment]
HystrixObservableCommand 官方确实不推荐支持线程池模式 详看：https://github.com/Netflix/Hystrix/issues/1228
