### ISSUE TITLE
大批量跑数据时 log日志刷http:circuitBreaker is Open.... !

### ISSUE THREAD

**Issue by DevilRebirth** [Dromara/soul#26]
我使用jemter去调用divide插件时候，500个线程，当总量到达1000之后，请求就返回：{
:   "code":-2,
:   "message":"this is bad request or fuse ing please try again later",
:   "data":null
}。log日志中刷的日志为http:circuitBreaker is Open.... !

**Comment by yu199195** [comment]
熔断了。你的服务支持500的并发？

**Comment by DevilRebirth** [comment]
> 熔断了。你的服务支持500的并发？
服务这边我不做任何处理，只是一个单纯的请求，前两天没有问题，能跑上千万数据，并且不出错，昨天和今天就开始出现这样的问题了

**Comment by yu199195** [comment]
调用出错了，或者你的配置改了

**Comment by DevilRebirth** [comment]
> 调用出错了，或者你的配置改了

能否具体点？我将熔断的配置做了一下改动：跳闸最小请求数量：50，错误半分比阀值：50，最大并发量：1000，跳闸休眠时间(单位毫秒)：500 当时用这样的配置是没有出问题的。

**Comment by yu199195** [comment]
看下服务提供者的错误日志，报什么错误
