### ISSUE TITLE
WebsocketDataHandler在处理admin的selector、rule同步信息的时候，会清空对应模块的全部map缓存信息,然后存只存当前同步对象的值

### ISSUE THREAD

**Issue by xuhangsong** [Dromara/soul#260]
` switch (eventTypeEnum) {
                case REFRESH:
                case MYSELF:
                    pluginDataSubscriber.refreshPluginData();
                    pluginDataList.forEach(pluginDataSubscriber::onSubscribe);
                    break;
                case UPDATE:
                case CREATE:
                    pluginDataList.forEach(pluginDataSubscriber::onSubscribe);
                    break;
                case DELETE:
                    pluginDataList.forEach(pluginDataSubscriber::unSubscribe);
                    break;
                default:
                    break;
            }`
REFRESH 事件清空了map中对应的全部内容，然后只存当前更新的模块，导致其他组件对应模块找不到

**Comment by xuhangsong** [comment]
2.2.0版本

**Comment by xuhangsong** [comment]
感觉应该清空的是当前更新插件对应的selector和rule，而不是整个map清空，根据pluginName进行针对性的clear

**Comment by yu199195** [comment]
这是个bug，先不要手动的去点击同步，

**Comment by yu199195** [comment]
已经fix，预计在下一个版本解决
