### ISSUE TITLE
dubbo String类型输入参数问题

### ISSUE THREAD

**Issue by wyxinlx** [Dromara/soul#262]
背景：dubbo提供的服务接口输入参数是String类型
操作方法：参考文档快速入门/user-api/user/get 这一小节，把body中的参数直接设置为 “demo”
问题：传递给dubo的参数是 null，查看源码，DefaultDubboParamResolveService 把body转换成Map<String, Object>类型的数据，结果为null。请问预期就是这样么，还是哪里用法不对？感谢。

**Comment by yu199195** [comment]
参考demo，都是通过 json格式来传的

**Comment by yu199195** [comment]
默认是通过javabean对象来转换， 请设置成 多参数，传json，请看文档
