### ISSUE TITLE
请问，dubbo服务是否是自动发现的，包括优雅上下线?

### ISSUE THREAD

**Issue by tzszhzx** [Dromara/soul#266]
请问，dubbo服务是否是自动发现的，包括优雅上下线?
还是所有的dubbo服务的地址、ip、服务等依然需要手动添加到网关中？

**Comment by yu199195** [comment]
不需要，请仔细了解下dubbo插件是怎么用的，有让你配置ip等服务的信息吗？ 不是只要配置注册中心就好了吗

**Comment by tzszhzx** [comment]
补充说明，服务应该需要手动注册到网关，并不是所有的dubbo注册中心的服务都需要通过网关暴露出来的。我指的是当某个dubbo应用的某个服务被注册到网关后，网关是否做到了自动感知该应用的dubbo服务的自动上下线。

**Comment by tzszhzx** [comment]
比如A应用查询依据学生ID查询学生信息的dubbo服务注册到网关后，然后A应用扩容了，此时网关是否能自我感知到并自动负载均衡，还是应用扩容或缩容后，都需要到网关上再操作一次？

**Comment by yu199195** [comment]
>比如A应用查询依据学生ID查询学生信息的dubbo服务注册到网关后，然后A应用扩容了，此时网关是否能自我感知到并自动负载均衡，还是应用扩容或缩容后，都需要到网关上再操作一次

当然支持自动感知

**Comment by tzszhzx** [comment]
good!!!
