### ISSUE TITLE
在 url 中传入中文参数报 400

### ISSUE THREAD

**Issue by dd01fangming** [Dromara/soul#280]
在 soul-web/src/main/java/org/dromara/soul/web/plugin/http/WebClientPlugin.java 类中，
将 WebClient.RequestBodySpec requestBodySpec = webClient.method(method).uri(urlPath); 改为：
WebClient.RequestBodySpec requestBodySpec = webClient.method(method).uri(URI.create(urlPath)); 

然后在 url 中传入中文参数，就会直接报 400

**Comment by yu199195** [comment]
我没明白你表达的意思

**Comment by dd01fangming** [comment]
httpPath 是实际请求后端服务的 url，当 webclient 请求后端服务的时候，在 uri 方法的参数列表中传入 URI 的 create 方法创建的 URI 对象，那么发送 get 请求的时候，当 httpPath 中存在带有中文的参数值，这个请求就会报 400。
