### ISSUE TITLE
Soul + nacos + SoulSpringCloudClient + FeginClient  启动报错

### ISSUE THREAD

**Issue by bigbug-dachong** [Dromara/soul#288]
业务服务通过 @SoulSpringCloudClient 自动注册到soul-admin

对下游业务调用，希望通过FeginClient调用。

组合使用下，服务无法正常启动。

有没有同学也遇到这个问题？？

报错：
`Caused by: java.util.concurrent.RejectedExecutionException: Task org.dromara.soul.client.springcloud.init.SpringCloudClientBeanPostProcessor$$Lambda$300/1388280822@ae73c80 rejected from java.util.concurrent.ThreadPoolExecutor@22f4f8f2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]`

**Comment by bigbug-dachong** [comment]
- 报错位置：
![image](https://user-images.githubusercontent.com/46708615/90373556-a70b1080-e0a4-11ea-8f72-ba56c9347ad8.png)

- 线程池关闭原因：
![image](https://user-images.githubusercontent.com/46708615/90373599-bc803a80-e0a4-11ea-80fc-73e8cef243f7.png)

![image](https://user-images.githubusercontent.com/46708615/90373636-cb66ed00-e0a4-11ea-8ac6-04b53c7ee95f.png)

**Comment by yu199195** [comment]
master分支修复这个了问题 ，线程池提前关闭的问题

**Comment by bigbug-dachong** [comment]
> master分支修复这个了问题 ，线程池提前关闭的问题

验证OK

但是master分支pom版本号并未修改，仍是2.2.0 。
直接从远程仓库的还是有问题的。

我本地打包验证ok
