### ISSUE TITLE
soul 如何集成 consul

### ISSUE THREAD

**Issue by bigbug-dachong** [Dromara/soul#296]
查了官网，和网上一些文章，并没有找到 soul对consul的集成。

查看以往的issue，说会支持，不知道当前是否已经支持？
如果已经支持，哪位能帮忙提供个接入文档？
请教

**Comment by bigbug-dachong** [comment]
有人了解吗？

**Comment by yu199195** [comment]
你可以做下贡献吗？ 或者使用consul是干嘛的？

**Comment by bigbug-dachong** [comment]
> 以做下贡献吗？ 或者使用consul是干嘛的？

公司springcloud用consul做了注册中心，想知道  soul目前是否有像nacos一样自动识别注册中心服务，注册到选择器上。

自己做贡献，嗯。如果目前没有支持，要去研究下了

**Comment by yu199195** [comment]
如果是springcloud，只是在启动下，配置sc的注册中心是consul就好了。 和nacos一样，
