### ISSUE TITLE
dubbo协议下,多参数，单参数都无法请求成功

### ISSUE THREAD

**Issue by gardenerHan** [Dromara/soul#298]
为什么给的示例中，多参数，单参数都无法请求成功；
1.单参数请求无法接收到参数值；
2.多参数、list、数组直接序列化失败；

是我哪儿不对吗？
看了其他人的issue，是还不支持吗？

目前来说，这些对于dubbo服务来说还是很重要的，请问有解决方案吗 ？ 

在调研中，麻烦给予解答，谢谢

**Comment by yu199195** [comment]
是已经支持的，demo中的dubbo 都有介绍

**Comment by gardenerHan** [comment]
你好 感谢你的回答；

我拉取了项目的master主干代码，使用了代码中的test demo；测试的结果是依然有这些情况存在；

其中admin和bootstrap使用的是你博客中提供的jar；

**Comment by yu199195** [comment]
没有返回值，应该是你没有配置正确，或者请求方式不对

**Comment by gardenerHan** [comment]
有几点需要确认下：
1.可以直接使用你博客中提供的jar吗？目前来看使用博客中jar存在我上述的问题；
2.在使用master主干的admin与bootstrap没有返回值？ 一般是哪儿配置没对呢？ 我的zookeeper、admin、bootstrap、test demo 均在一台服务器上来，使用的是默认配置，从日志上与控制台上没看到报错与不对的地方；

跪求大佬指教，十分感谢；

**Comment by gardenerHan** [comment]
可以了 ，爱了爱了 感谢  终于ok了
