### ISSUE TITLE
soul网关新增sentinel熔断插件的支持

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#301]
1.在soul网关里面新增对alibaba ，sentinel熔断插件的支持。

**Comment by dengliming** [comment]
Hello~, I'd love to take this as first contribution for this repo.

**Comment by yu199195** [comment]
@dengliming  welcome，

**Comment by yu199195** [comment]
@dengliming  hi， 最近有在做对sentinel的支持吗？ 如果有任何不懂的地方，可以找我一起协助

**Comment by dengliming** [comment]
@yu199195 差点忘了，不好意思哈。我应该这几天会提交一版。再确认下是否只需要集成sentinel熔断那块的功能？

**Comment by yu199195** [comment]
限流也可以，应该分开2个插件。 先弄熔断把。 你微信多少，我拉你先进社区贡献值群，有问题联系

**Comment by dengliming** [comment]
1196767447

**Comment by KevinClair** [comment]
> 限流也可以，应该分开2个插件。 先弄熔断把。 你微信多少，我拉你先进社区贡献值群，有问题联系

sentinel的插件是准备限流跟熔断都可以吗？最近在对接这块，准备做sentinel跟spring security的扩展。

**Comment by yangzhiw** [comment]
> 1.在soul网关里面新增对alibaba ，sentinel熔断插件的支持。

我也在尝试

**Comment by tydhot** [comment]
assigned to me
