### ISSUE TITLE
registration and discovery of HTTP services for soul

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#302]
now：IP + port probing mechanism is adopted for HTTP service
after： By registry center

**Comment by tincopper** [comment]
I want to help

**Comment by tydhot** [comment]
assigned to me

**Comment by WangRong1982** [comment]
不需要业务系统在接口上添加@SoulSpringMvcClient注解了，有API自动发现功能了是吗？
太好了。
请问业务的ip和端口号怎么上传到soul-admin？

**Comment by superbool** [comment]
可以兼容现有的一些服务发现中间件吗，比如consul等

**Comment by yu199195** [comment]
we finish it
