### ISSUE TITLE
soul如何部署集群

### ISSUE THREAD

**Issue by yihui366898** [Dromara/soul#31]
soul如何部署集群，能写个录个视频教程吗？

**Comment by yu199195** [comment]
不是有视频教程？

**Comment by yu199195** [comment]
集群就是启动多个服务，你在访问的时候，前面加一层nginx，看架构图

**Comment by yihui366898** [comment]
就是soul-bootstrap这个服务启动多个是吗？

**Comment by yu199195** [comment]
是的，他就是http服务

**Comment by walter211** [comment]
客户端是websocket soul集群可以自动实现长连接迁移吗

**Comment by yu199195** [comment]
可以的，soul可以代理websocket

**Comment by linchuyao** [comment]
集群之间会通讯吗,我看配置计算都是存到jvm里面不能实现集群互通

**Comment by daofeng1949** [comment]
> 不是有视频教程？

能麻烦发个视频地址嘛
