### ISSUE TITLE
docker-compose.yml里端口不对

### ISSUE THREAD

**Issue by bobzhanggmail** [dromara/soul#310]
soul-admin的server port是9095，docker-compose.yml里配的却是8086，建议修正下。

**Comment by yu199195** [comment]
你可以提pr来修复吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;frank&amp;nbsp;zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月22日(星期二) 中午11:32
收件人:&nbsp;&quot;dromara/soul&quot;<soul@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dromara/soul] docker-compose.yml里端口不对 (#310)
