### ISSUE TITLE
divide 插件，http 请求报404

### ISSUE THREAD

**Issue by woshiyingmu** [dromara/soul#314]
正常启动soul-test 应用，context-path 设置为soul-test， http://127.0.0.1:9195/soul-test/order/findById报404，
![image](https://user-images.githubusercontent.com/9637974/94221579-fb17d900-ff1d-11ea-8064-d938c9129e57.png)
postman里请求
![image](https://user-images.githubusercontent.com/9637974/94221617-0d921280-ff1e-11ea-8f74-3ee2bf190177.png)，
发现匹配的路径/soul-test/order/findById 这个最后没有，所以get 请求报404

**Comment by yu199195** [comment]
那你的应用名称是soul-test吗

**Comment by woshiyingmu** [comment]
是的。我把参数改为parm 就是其他的 也会出现这个问题 ，版本2.2.1

**Comment by yu199195** [comment]
那你访问原来的，能访问，把9095端口，改成你真实的服务端口？

**Comment by yu199195** [comment]
上面图中，那么大一个截图的错误日志输出输出的地址，是你真实服务的地址吗？ 
输出的地址，你能访问吗？

**Comment by woshiyingmu** [comment]
> 上面图中，那么大一个截图的错误日志输出，输出的地址，是你真实服务的地址吗？
> 输出的地址，你能访问吗？

 192.168.20.219:8187 是我本地的ip:port, 输出的地址resulting path是http://192.168.20.219:8187?id=5555nnbbbbbbbbbbb 但真实的地址应该是http://192.168.20.219:8187/order/findById?id=5555nnbbbbbbbbbbb ,就是匹配规则的时候，把/order/findById 一段过滤掉了，所以http://192.168.20.219:8187?id=5555nnbbbbbbbbbbb才报404

**Comment by woshiyingmu** [comment]
> http://127.0.0.1:9195/http/order/findById?111111

 换成你这个地址最终匹配程http://192.168.20.219:8187?111111 依然是404

**Comment by yu199195** [comment]
在admin后端，删除元数据， soulClient注解上删除 isRegisterMetaData

**Comment by woshiyingmu** [comment]
可以了


> 在admin后端，删除元数据， soulClient注解上删除 isRegisterMetaData

可以了 @

**Comment by woshiyingmu** [comment]
> 在admin后端，删除元数据， soulClient注解上删除 isRegisterMetaData

可以了
