### ISSUE TITLE
spring框架下dubbo服务提供者接入导致启动异常

### ISSUE THREAD

**Issue by patzheng** [dromara/soul#323]
dubbo版本
<groupId>com.alibaba</groupId>
<artifactId>dubbo</artifactId>
<version>2.6.5</version>
客户端版本
 <dependency>
      <groupId>org.dromara</groupId>
      <artifactId>soul-client-alibaba-dubbo</artifactId>
      <version>2.2.0</version>
    </dependency>
spring配置
<bean id="alibabaDubboServiceBeanPostProcessor"
    class="org.dromara.soul.client.alibaba.dubbo.AlibabaDubboServiceBeanPostProcessor">
    <constructor-arg ref="dubboConfig"/>
  </bean>

  <bean id="dubboConfig" class="org.dromara.soul.client.dubbo.common.config.DubboConfig">
    <property name="adminUrl" value="http://localhost:9095"/>
    <property name="contextPath" value="/你的contextPath"/>
    <property name="appName" value="你的名字"/>
  </bean>
启动异常
Caused by: java.lang.AbstractMethodError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization

**Comment by yu199195** [comment]
使用2.2.1 看看

**Comment by patzheng** [comment]
查出问题来了。出在spring版本上面。BeanPostProcessor在4版本里面需要子类实现postProcessAfterInitialization。但是在spring5版本里面不需要

**Comment by patzheng** [comment]
有很多老系统需要接入，还真的需要升级下版本
