### ISSUE TITLE
请问接入Springboot应用时, 想使用sign插件和认证管理功能，请问如何配置

### ISSUE THREAD

**Issue by WangRong1982** [dromara/soul#329]
接入Springboot应用时，在接口中加入@SoulSpringMvcClient注解后，就会向soul-admin的divied插件中注册选择器和规则，但是不会注册元数据。
例如：自动注册了一个名称为/wangrong-demo-api/user/get的规则。
此时divied插件转发正常
postman访问http://网关Ip:端口/wangrong-demo-api/user/get?id=1时，可以正常跳转到我的Springboot业务的http://业务Ip:端口/user/get?id=1中去。

之后我想使用认证管理时，我在“认证”添加页面中的“应用名称”下拉框中没有任何数据，我发现只有在“元数据管理”中添加数据之后，才能在“认证”添加页面中的“应用名称”下拉框中有数据给我选择。于是我就在元数据管理中手动添加了一条数据，其中“应用名”填写为wangrongService;     “路径”填写为/wangrong-demo-api/user/get。

于是我在认证管理的添加认证页面的“应用名称”下拉框中，选择了wangrongService，并且在资源路径中勾选了/wangrong-demo-api/user/get
保存数据之后，我发现divied插件无法正常转发了。

postman访问http://网关Ip:端口/wangrong-demo-api/user/get?id=1时，跳转到我的Springboot业务的http://业务Ip:端口/?id=1中去。这时转发uri中的“/user/get”丢了。

于是我debug调查，发现DividePlugin类的doExecute函数中的exchange对象的context属性中的SoulContext对象的realUrl属性值为null，导致获取转发路径时，/user/get没有获取到。
之后我看了构造SoulContext时，调用了DefaultSoulContextBuilder类中setSoulContextByDubbo方法了，而没有调用
setSoulContextByHttp方法。
只有在setSoulContextByHttp方法中才会设置realUrl属性值

疑问：
1）在接入Springboot应用时，想要使用sign插件和认证管理功能时，是否要添加元数据管理，因为认证管理页面中的“应用名称”下拉框必须要填写，所以我认为必须要添加一个元数据。请问，我的理解对吗？
2）当添加了元数据之后，soul就会把请求当成dubbo应用了，请问对于Springboot应用的http这些接口，要使用sign插件和认证管理这个功能，soul-admin的页面中需要怎么设置呢？

请帮忙回答，十分感谢！

**Comment by yu199195** [comment]
使用最新的master分支吧
