### ISSUE TITLE
soul-bootsttap健康检查的是否要自己写？

### ISSUE THREAD

**Issue by cugwhzenith** [dromara/soul#332]
用divide插件分流时，故意配了不对的转发地址，divide在请求转发之前并没有做健康检查，所以会转发到错误的地址。

**Comment by yu199195** [comment]
健康检查和 具体的接口有啥关系？

**Comment by cugwhzenith** [comment]
如果服务挂了，没有健康检查，还是会转发到这个服务。

**Comment by cugwhzenith** [comment]
> 健康检查和 具体的接口有啥关系？

如果服务挂了，没有健康检查，还是会转发到这个服务。

**Comment by cugwhzenith** [comment]
> > 健康检查和 具体的接口有啥关系？
> 
> 如果服务挂了，没有健康检查，还是会转发到这个服务。

配错地址模拟的时服务挂了的场景

**Comment by yu199195** [comment]
springboot是这样的吗？ 你访问一个错误的地址，提示你什么?
