### ISSUE TITLE
divide插件 配置疑问

### ISSUE THREAD

**Issue by cugwhzenith** [dromara/soul#334]
divide配置规则 uri match  /cnf/sline/admin/**  路由到后端端口的时候，不会像gateway一样去掉了/cnf/sline/admin/
前缀，只会去掉第一个前缀 /cnf。对于多前缀的转发配置不方便

**Comment by yu199195** [comment]
contextPath 写成你需要去掉的

**Comment by cugwhzenith** [comment]
> contextPath 写成你需要去掉的

![image](https://user-images.githubusercontent.com/46958942/98792484-86ebb300-2441-11eb-92de-55ace3ab5a2a.png)
divide插件没有配contextPath的地方，需要在自己的代码里面配？

**Comment by cugwhzenith** [comment]
> contextPath

我看了下官网说明文档，我的理解是配contextPath是对有注解或者元数据的路由，如果实现对全部接口的路由，用divide不行吗？
