### ISSUE TITLE
rate_limiter插件和divide插件结合使用问题

### ISSUE THREAD

**Issue by DevilRebirth** [Dromara/soul#34]
是否能够把这两个插件结合起来使用？

**Comment by yu199195** [comment]
divide 是 http代理。 rate_limiter 是限流，怎么能一起呢， dubbo请求呢

**Comment by DevilRebirth** [comment]
> divide 是 http代理。 rate_limiter 是限流，怎么能一起呢， dubbo请求呢

我有一个疑问是，我在使用http代理的去调用业务服务的某个接口，现在想把这个接口限流，我想着是不是可以结合您已经提供的限流插件结合去做控制

**Comment by DevilRebirth** [comment]
![image](https://user-images.githubusercontent.com/17892951/54664708-fa7bd680-4b1f-11e9-846d-0e2f2c8e98a6.png)
请问如果我一个http请求是这样的，会同时使用这两个插件配置吗

**Comment by yu199195** [comment]
插件是责任链执行的，看你的配置，如果你配置了 2个插件都会匹配吗他就会执行，你的限流配置是什么鬼东西，限流插件是到接口级别的，看你的配置，如果去匹配它而已

**Comment by ttiaolong** [comment]
限流插件里面：速率和容量代表什么意思？
