### ISSUE TITLE
SentinelRuleHandle handle removeRule mistake

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#345]
现在代码是这样的：removeRule里面传的是要删除的规则，这里处理是只保留了要删除的规则了。如果我没理解错的话这个逻辑是不对的吧？@tydhot
```
 @Override
    public void removeRule(final RuleData ruleData) {
        FlowRuleManager.loadRules(FlowRuleManager.getRules()
                .stream()
                .filter(r -> r.getResource().equals(getResourceName(ruleData)))
                .collect(Collectors.toList()));
        DegradeRuleManager.loadRules(DegradeRuleManager.getRules()
                .stream()
                .filter(r -> r.getResource().equals(getResourceName(ruleData)))
                .collect(Collectors.toList()));
    }
```
代码来自[https://github.com/dromara/soul/blob/master/soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/handler/SentinelRuleHandle.java#L72-L82](https://github.com/dromara/soul/blob/master/soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/handler/SentinelRuleHandle.java#L72-L82)

**Comment by tydhot** [comment]
嗯 我已经改好了 还没提交

**Comment by dengliming** [comment]
good
