### ISSUE TITLE
springCloud插件对contextPath去除的疑问

### ISSUE THREAD

**Issue by cugwhzenith** [dromara/soul#347]
配置springCloud插件，设置contextPath=/cnf/sline/admin
转发请求的时候只会截掉第一个前缀/cnf
![image](https://user-images.githubusercontent.com/46958942/99034148-7a896680-25b7-11eb-8922-e7caf8f221e9.png)

![image](https://user-images.githubusercontent.com/46958942/99033845-c4be1800-25b6-11eb-9598-999b8b6f57c6.png)
推测bug来源：
![image](https://user-images.githubusercontent.com/46958942/99034020-34cc9e00-25b7-11eb-85a4-c38a77031156.png)

**Comment by yu199195** [comment]
你有什么更新意见吗？

**Comment by cugwhzenith** [comment]
> 你有什么更新意见吗？
要想通用一点，多前缀最好支持吧。
我在本地测试多传一个metadata参数，根据metaData里面的path 用“/**”来截，但是失败了。
![image](https://user-images.githubusercontent.com/46958942/99036312-65630680-25bc-11eb-8912-a2f3f0dbf60b.png)
