### ISSUE TITLE
优化sentinel规则添加界面操作

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#349]
![image](https://user-images.githubusercontent.com/7796156/99139869-83da0800-2677-11eb-9444-250ac7f78d48.png)

目前插件处理数据管理只支持数字和字符串类型，这里页面`限流阈值类型`全部都是填数字也没有任何说明每个数字代表的类型，觉得这样不是很友好，建议增加`UI优化成下拉选项`或者`调整插件管理数据增加支持下拉框类型或者提示语`

**Comment by yu199195** [comment]
调整插件管理数据增加支持下拉框类型或者提示语 ，这个方案比较好，这里的都应该是配置的，需要新增一张配置数据字典表，
在soul-admin后台新增，新增字段的时候，选择下拉框，然后根据配置模板渲染出来就好了。
 你可以做下这个，也是个很大的优化，和重要的功能
