### ISSUE TITLE
soul在下一个版本去除Zookeeper的依赖

### ISSUE THREAD

**Issue by yu199195** [Dromara/soul#35]
soul目前是使用zookeeper来做数据的的缓存与动态监听刷新。
准备参考Apollo 的长轮询策略来做。
优点 ：这样可以去除对zookeeper的依赖，更加轻量级。
缺点： 动态的配置更新可能没有那么及时。依赖与长轮询的时间。

**Comment by SaberSola** [comment]
apollo长轮询不熟悉 rocketmq消费端长轮询模式熟悉,想参与,水平不太高,仍在努力学习中,只有周末有时间 考虑么 猫老大

**Comment by yu199195** [comment]
@SaberSola  可以，就是一给http轮询获取数据，然后写到本地，http轮询的时候要考虑到集群的情况

**Comment by 241600489** [comment]
不考虑其他开源的配置中心就是 觉得添加依赖 比较重量级吗

**Comment by yu199195** [comment]
@241600489  和开源的配置中心没任何关系，依赖那些太重

**Comment by liyong1028826685** [comment]
可以整合nacos来做 nacos本身才有的就是http长连接模式

**Comment by yu199195** [comment]
nacos太重，没必要依赖 和nacos没有什么关系

**Comment by yu199195** [comment]
@liyong1028826685

**Comment by zongtanghu** [comment]
@yu199195 您好，我们这边儿想参与soul开源项目共同建设，可以加下微信或者钉钉聊下么？
