### ISSUE TITLE
请问soul + dubbo，前端header中传递信息，dubbo中应该如何接收呢？

### ISSUE THREAD

**Issue by phpisfuture** [dromara/soul#350]
请问soul + dubbo，如前端header中传递Token信息，soul网关如何解析出用户信息如ID并传递到dubbo方法中，应该如何接收呢？

**Comment by dengliming** [comment]
我觉得你可以定制化你们自己内部dubbo插件，可以结合RpcContext的attachment透传http的header，这种也有助于不让链路丢失

**Comment by phpisfuture** [comment]
> 我觉得你可以定制化你们自己内部dubbo插件，可以结合RpcContext的attachment透传http的header，这种也有助于不让链路丢失

谢谢，定义了插件，用Invocation传递了attachment已经能拿到了

**Comment by phpisfuture** [comment]
> 我觉得你可以定制化你们自己内部dubbo插件，可以结合RpcContext的attachment透传http的header，这种也有助于不让链路丢失

谢谢，定义了插件，用Invocation传递了attachment已经能拿到了
