### ISSUE TITLE
soul转发请求到spring cloud gateway的疑问

### ISSUE THREAD

**Issue by cugwhzenith** [dromara/soul#351]
soul整合spring cloud项目访问接口必须要@SoulSringCloudClient注解吗？如果只是将请求到转发到spring cloud gateway呢，没有接口没法加上@SoulSringCloudClient注解，只能在配置文件里面配contextPath。我测试了下，slector可以匹配到（因为有contextPath），因为没有rule（gateway没接口没@SoulSringCloudClient注解）转发到gateway的请求就不通。

**Comment by KevinClair** [comment]
> soul整合spring cloud项目访问接口必须要@SoulSringCloudClient注解吗？如果只是将请求到转发到spring cloud gateway呢，没有接口没法加上@SoulSringCloudClient注解，只能在配置文件里面配contextPath。我测试了下，slector可以匹配到（因为有contextPath），因为没有rule（gateway没接口没@SoulSringCloudClient注解）转发到gateway的请求就不通。

不需要一定要加@SoulSringCloudClient的，这个注解是方便客户端生成元数据，自己手动在Admin上新增也是一样的效果。Rule也可以自己建。

**Comment by cugwhzenith** [comment]
> > soul整合spring cloud项目访问接口必须要@SoulSringCloudClient注解吗？如果只是将请求到转发到spring cloud gateway呢，没有接口没法加上@SoulSringCloudClient注解，只能在配置文件里面配contextPath。我测试了下，slector可以匹配到（因为有contextPath），因为没有rule（gateway没接口没@SoulSringCloudClient注解）转发到gateway的请求就不通。
> 
> 不需要一定要加@SoulSringCloudClient的，这个注解是方便客户端生成元数据，自己手动在Admin上新增也是一样的效果。Rule也可以自己建。

嗯嗯，是的，这个我能明白。但是gateway没有接口，没有rule（自己也没法建），访问gateway路由的接口只能匹配到contextPath对应的selector，rule匹配不到，结果会报“ -106  匹配不到选择器”的错误~

**Comment by KevinClair** [comment]
> > > soul整合spring cloud项目访问接口必须要@SoulSringCloudClient注解吗？如果只是将请求到转发到spring cloud gateway呢，没有接口没法加上@SoulSringCloudClient注解，只能在配置文件里面配contextPath。我测试了下，slector可以匹配到（因为有contextPath），因为没有rule（gateway没接口没@SoulSringCloudClient注解）转发到gateway的请求就不通。
> > 
> > 
> > 不需要一定要加@SoulSringCloudClient的，这个注解是方便客户端生成元数据，自己手动在Admin上新增也是一样的效果。Rule也可以自己建。
> 
> 嗯嗯，是的，这个我能明白。但是gateway没有接口，没有rule（自己也没法建），访问gateway路由的接口只能匹配到contextPath对应的selector，rule匹配不到，结果会报“ -106 匹配不到选择器”的错误~

为什么要在gateway上面再加一个soul呢？一开始理解错了，我以为你是需要在spring cloud上面用soul。

**Comment by cugwhzenith** [comment]
> > > > soul整合spring cloud项目访问接口必须要@SoulSringCloudClient注解吗？如果只是将请求到转发到spring cloud gateway呢，没有接口没法加上@SoulSringCloudClient注解，只能在配置文件里面配contextPath。我测试了下，slector可以匹配到（因为有contextPath），因为没有rule（gateway没接口没@SoulSringCloudClient注解）转发到gateway的请求就不通。
> > > 
> > > 
> > > 不需要一定要加@SoulSringCloudClient的，这个注解是方便客户端生成元数据，自己手动在Admin上新增也是一样的效果。Rule也可以自己建。
> > 
> > 
> > 嗯嗯，是的，这个我能明白。但是gateway没有接口，没有rule（自己也没法建），访问gateway路由的接口只能匹配到contextPath对应的selector，rule匹配不到，结果会报“ -106 匹配不到选择器”的错误~
> 
> 为什么要在gateway上面再加一个soul呢？一开始理解错了，我以为你是需要在spring cloud上面用soul。

因为我们公司的gateway上有很多逻辑处理代码，直接用soul替代gateway代价有点大

**Comment by cugwhzenith** [comment]
> 因为我们公司的gateway上有很多逻辑处理代码，直接用soul替代gateway代价有点大
soul3.0会考虑我这种转发到gateway的奇怪的需求吗？
