### ISSUE TITLE
优化soul-admin 用户密码 数据库中存储形式 由 明文->加密

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#357]

**Comment by hongyangXing** [comment]
建议前端md5

**Comment by KevinClair** [comment]
我们是做了Admin跟用户权限隔离，密码更改权限放给用户，数据库密码加密。

**Comment by yu199195** [comment]
@KevinClair 你们啥公司？登记了吗

**Comment by KevinClair** [comment]
> @KevinClair 你们啥公司？登记了吗

贵人多忘事啊大佬，我说了三遍了都。。。登记了。

**Comment by yu199195** [comment]
@KevinClair 米哈游吧，可以继续来优化

**Comment by KevinClair** [comment]
> @KevinClair 米哈游吧，可以继续来优化

嗯嗯，后续有时间会提交pr的。

**Comment by nuo-promise** [comment]
在增加一个 优化 将 Obj != null 改为 Optional.ofNullable(Obj).isPresent

**Comment by yiwenlong** [comment]
严谨起见，密码哈希存储建议使用 SHA2 或者 SHA3 系列算法。

**Comment by nuo-promise** [comment]
建议 很好,后面考虑进去

伊文龙 <notifications@github.com> 于2020年11月21日周六 上午12:41写道：
