### ISSUE TITLE
dubbo服务@SoulDubboClient注册到网关问题。

### ISSUE THREAD

**Issue by phpisfuture** [dromara/soul#360]
org.dromara.soul.client.apache.dubbo.ApacheDubboServiceBeanPostProcessor.post(String json)方法result信息返回地址已经存在，验证的是@SoulDubboClient的path信息嘛，如果这个路由的dubbo提供方信息变成，目前好像无法同步更新信息。还有我觉得已经存在不应该输出error日志，这样第二次启动的时候路由会全部打出error，还以为服务挂掉了。

**Comment by SaberSola** [comment]
最新的master已经修复了

**Comment by phpisfuture** [comment]
> 最新的master已经修复了

您好，maven发布了嘛，还是需要自己拉master自己打包？

**Comment by SaberSola** [comment]
可以自己打包的,也可以等着猫老大发新版本
