### ISSUE TITLE
插件的里面的选择器处理，规则处理，全部模板化

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#372]
1. 涉及所有插件的前端更改，前端插件应该只有一个公用的模块就行，根据 字典表，处理表来渲染

**Comment by dengliming** [comment]
指给我吧

**Comment by yu199195** [comment]
@dengliming  good job

**Comment by dengliming** [comment]
- [ ] sign
- [ ] waf
- [ ] rewrite
- [ ] rate_limiter
- [ ] divide
- [ ] dubbo
- [ ] monitor
- [ ] springCloud
- [ ] hystrix
- [ ] sentinel
