### ISSUE TITLE
修改script文件中soul.sql中初始化用户的密码为密文

### ISSUE THREAD

**Issue by yangxing9** [dromara/soul#381]
admin模块中schema.sql的默认用户密码已改为密文，全局的初始化sql应保持同步

**Comment by dengliming** [comment]
@yangxing9  有兴趣提交PR改下吗 复制schema.sql里面的过来就行了

**Comment by yangxing9** [comment]
> @yangxing9 有兴趣提交PR改下吗 复制schema.sql里面的过来就行了

ok，I will fix it

**Comment by dengliming** [comment]
fixed by [https://github.com/dromara/soul/pull/382](https://github.com/dromara/soul/pull/382)

**Comment by dengliming** [comment]
@yangxing9 Thanks for your contribution.
