### ISSUE TITLE
Soul gateway management platform didn't login expired

### ISSUE THREAD

**Issue by zfy-zhang** [dromara/soul#385]
soul网关管理平台没做登陆过期功能

**Comment by nuo-promise** [comment]
@yu199195 @zfy-zhang   登录会话过期 可否 连 权限 也做进去,毕竟 它两 几乎都是一块的？

**Comment by dengliming** [comment]
如果这样的这个工作量比较多可以细分下，可以先考虑下是否需要做这么复杂

**Comment by nuo-promise** [comment]
> 如果这样的这个工作量比较多可以细分下，可以先考虑下是否需要做这么复杂

我的想法是 soul 网关 被第三方公司使用, 三方公司 对于不同 研发或者运维的人 有 不同的配置权限。我是从这个点考虑的。

**Comment by yu199195** [comment]
先做一个过期把， 权限太重，可能会关系到按钮级别，或者页面级别。。。
