### ISSUE TITLE
soul-admin 全自动适配 针对 任何 账户 使用任何密码(明文)登录

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#386]
1.本地已存在 soul-admin 数据库,并且 任何 账户 任何明文密码  都可以 按照之前方式登录
2.登录之后,明文将被修改 使用 用户指定的秘钥 进行加密
3.本次更新只兼容 密码由 明文 转 加密 , 如果已经加密 在更换秘钥 暂时不支持

**Comment by dengliming** [comment]
closed by [https://github.com/dromara/soul/pull/387](https://github.com/dromara/soul/pull/387)
