### ISSUE TITLE
Add issue and pr templates

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#391]
官方文档：[https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests)

提供`PULL_REQUEST_TEMPLATE`、`ISSUE_TEMPLATE`这两个模板即可

可以先参考这两个做一版
[ISSUE_TEMPLATE](https://github.com/apache/skywalking/blob/master/.github/ISSUE_TEMPLATE)
[PULL_REQUEST_TEMPLATE](https://github.com/apache/skywalking/blob/master/.github/PULL_REQUEST_TEMPLATE)

**Comment by nuo-promise** [comment]
> 官方文档：https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests
> 
> 提供`PULL_REQUEST_TEMPLATE`、`ISSUE_TEMPLATE`这两个模板即可

组织大起来,这个模板 是要建立起来了.

**Comment by yu199195** [comment]
good
