### ISSUE TITLE
关于如何传递参数

### ISSUE THREAD

**Issue by Hintic** [Dromara/soul#40]
我是初学者，请多指教。
在视频教学中作者展示了http请求怎么传递多个参数，封装成对象通过@RequestBody传递。但是我想知道如何传递单个Integer参数呢，试过很多方法但是都未成功，求教。

**Comment by yu199195** [comment]
你springmvc 怎么传，那就怎么传，soul网关只是做了一层转发。

**Comment by Hintic** [comment]
作者你好。
这边尝试过了三种传递，1、通过form-data传递key=id,value=1，后台接收@RequestParam("id")  Integer id；2、通过form-data传递key=id,value=1，后台接收 Integer id；3、通过json传递{“id”:1}，后台接收@RequestBody Integer id（这种方式注解不允许）。三种方法单独的springmvc都可以成功，但是通过soul就失败，麻烦解惑告知正解。

**Comment by yu199195** [comment]
这种你是否可以使用get请求？

**Comment by Hintic** [comment]
麻烦作者。
get请求也可以通过soul网关处理转发吗，那参数应该写在哪里呢，路径上或者是header中？

**Comment by yu199195** [comment]
header 中的 extInfo ，json格式，请看文档

**Comment by Hintic** [comment]
作者你好。
我在header上加上key=extInfo,value={“id”:1},httpMethod更新为get，后台接收改为@GetMapping或者@RequestMapping下，@RequestBody Integer id或者@RequestParam(value="id") Integer id或者Integer id，统统试过都不成功。请指一条明路，是否通过soul发送参数只有封装成对象或者map才能成功。

**Comment by yu199195** [comment]
请问，你这么样，你匹配到了具体方法吗？
 @GetMapping("/id")
    public Integer testGet(@RequestParam("id") Integer id) {
        return id;
    }
header 中extInfo 字段值为{"id":1} 他的意思就会拼装成 http://ip:port/mehtod?id=1

其中ip:port是你后台传入的， method 是你具体传入的值

**Comment by Hintic** [comment]
感谢作者百忙之中为我解答。
成功取到Integer类型单参数值。
get类型http请求中header加入extInfo字段值{“id”:1}，服务后台接收@RequestParam("id") Integer id。可以成功往后台传单值。
再次感谢
