### ISSUE TITLE
Remove AppAuthQueryDTO

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#402]
#### Is your feature request related to a problem? Please describe

现在这个AppAuthQueryDTO放到query包下面了

#### Describe the solution you'd like

和其他地方保持一致, 建议去掉然后直接使用AppAuthQuery即可

**Comment by strawberry-crisis** [comment]
assign

**Comment by dengliming** [comment]
@strawberry-crisis  Thanks for your contribution.

**Comment by dengliming** [comment]
closed by [https://github.com/dromara/soul/pull/429](https://github.com/dromara/soul/pull/429)
