### ISSUE TITLE
问下 这块代码 有点没看懂 请教下哈

### ISSUE THREAD

**Issue by huarenzai** [Dromara/soul#41]
![image](https://user-images.githubusercontent.com/25600512/56177273-91a95080-6030-11e9-8e80-3be88c3eb76c.png)
dubbo 这里调用了DubboCommand 
doExecute 这边返回的是 mono.create 的mono  好像没有地方去触发返回
![image](https://user-images.githubusercontent.com/25600512/56177329-cddcb100-6030-11e9-9bae-73f354973e42.png)
可能说的不是很好  不知道您有没有明白我说的意思
就是这个调用链 好像是中断的在这里

这是我的代码 没使用 hystrix的
![image](https://user-images.githubusercontent.com/25600512/56177414-1dbb7800-6031-11e9-9a49-22d8437b88c3.png)
如果不是用hystrix 如何调用哈  对webflux 不是特别了解  希望您能解答

**Comment by yu199195** [comment]
返回mono webflux框架会去触发的
