### ISSUE TITLE
Dubbo标签路由实现简单的灰度发布

### ISSUE THREAD

**Issue by KevinClair** [dromara/soul#428]
#### Is your feature request related to a problem? Please describe
* 灰度发布

#### Describe the solution you'd like
* Dubbo的标签路由可以实现简单的灰度发布，可以通过http请求headers中的某个标签去指定请求tag的provider；
* 本来想着可以使用Dubbo的服务提供者直连的功能(#363)去实现，但是觉得不优雅，服务提供者直连多用于开发和测试环境调试。
* 目前暂用的灰度发布方案是用的这个。

#### Describe alternatives you've considered

* 灰度发布这块应该是要做成插件的，然后网关控制灰度规则，后续如果有更好的方案，再来讨论。

#### Additional context
[Dubbo标签路由](http://dubbo.apache.org/zh/docs/v2.7/user/examples/routing-rule/)

**Comment by tydhot** [comment]
如果做成插件的话 光dubbo的话不妥吧  最好能够对于各个rpc插件有更抽象的适配

**Comment by KevinClair** [comment]
嗯是的，目前简单的方式是做了这个，后面做一下具体的灰度插件，应该是跟客户端无关，由网关来控制灰度规则。

**Comment by tydhot** [comment]
但是具体到根据灰度策略进行寻址再调用的操作是各个rpc插件内部强耦合的 
能够抽象的应该是灰度策略的筛选和染色 这部分可以通过一个通用的前置插件完成 但是后续的寻址就需要每个rpc插件去自己实现了

**Comment by yu199195** [comment]
现在根据选择器和规则不就可以实现了吗

**Comment by tydhot** [comment]
> 现在根据选择器和规则不就可以实现了吗

他的意思应该是同一个规则下再做类似AB Test的筛选 比如根据入参或者比例直调某个生产者
