### ISSUE TITLE
Design logo for Soul

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#443]
design  logo

**Comment by magicalxiaochen** [comment]
![soul_1](https://user-images.githubusercontent.com/54343840/100583990-759e1400-3326-11eb-9f7f-749ca8cf0d57.png)

**Comment by magicalxiaochen** [comment]
![soul_2](https://user-images.githubusercontent.com/54343840/100584065-8e0e2e80-3326-11eb-881f-e89ad47f63e6.png)

**Comment by ipipman** [comment]
![111](https://user-images.githubusercontent.com/75295234/100887304-c57c0700-34ef-11eb-987f-5b2da777d07f.jpeg)

**Comment by ipipman** [comment]
![333](https://user-images.githubusercontent.com/75295234/100887357-d88ed700-34ef-11eb-8b1d-a8a502028a87.jpeg)

**Comment by ipipman** [comment]
![Uploading 222.jpeg…]()

**Comment by ipipman** [comment]
![222](https://user-images.githubusercontent.com/75295234/100887549-0ecc5680-34f0-11eb-985e-c7e9df97130e.jpeg)

**Comment by yiwenlong** [comment]
![981607184795_ pic](https://user-images.githubusercontent.com/9609929/101248415-da5ad380-3757-11eb-9396-bdd5281243b8.jpg)

符号取自实验室过滤分离装置的形状，然后还是中国结的一部分。
