### ISSUE TITLE
可以参考支付宝网关设计增加在线文档、在线测试功能

### ISSUE THREAD

**Issue by liyong1028826685** [Dromara/soul#45]
可以参考支付宝网关设计增加在线文档、在线测试功能

**Comment by yu199195** [comment]
你有兴趣提供一下代码吗？

**Comment by liyong1028826685** [comment]
我刚研究你这个源码，我们自己做了一套网关支持在线doc、和测试、目前后端我们只整合了rpc，控制力度没有你这全面，如果能接入到你提个的这个项目应该就比较完善了。
有个问题请教，你这个调用网关对请求参数sign应该要把请求内容作为签名的一部分，这个才比较符合实际场景。我们在易极付自研的网关就是这么做的。

**Comment by yu199195** [comment]
可以把在线doc，测试 加上来，你有时间提供下pr代码

**Comment by liyong1028826685** [comment]
我们现在公司使用的openapi http://openapi.huwochuxing.com/docs

**Comment by liyong1028826685** [comment]
我先看下你的项目。有时间我把这个整合过来。

**Comment by yu199195** [comment]
可以的，在线测试这个可以做一下
