### ISSUE TITLE
sofa插件文档的翻译

### ISSUE THREAD

**Issue by tydhot** [dromara/soul#458]
https://gitee.com/shuaiqiyu/website/blob/master/docs/zh-cn/soul/plugin-sofa.md

https://gitee.com/shuaiqiyu/website/blob/master/docs/zh-cn/soul/user-sofa.md

如果贡献pr 参考 ： https://dromara.org/website/en-us/docs/soul/contributor.html

**Comment by guanyushen** [comment]
get user-sofa

**Comment by Zhoutzzz** [comment]
get plugin-sofa

**Comment by yu199195** [comment]
ok。

**Comment by yu199195** [comment]
alreay commit。 thanks
