### ISSUE TITLE
Add test cases for plugins

### ISSUE THREAD

**Issue by SaberSola** [dromara/soul#460]
- [x] soul-plugin-base                     @BetterWp @SaberSola 
  
- [x] soul-plugin-hystrix                  @nuo-promise  

- [x] soul-plugin-ratelimiter            @wyc192273 

- [x] soul-plugin-resilience4j         @SaberSola

- [x] soul-plugin-rewrite                 @wuudongdong

- [x] soul-plugin-sentinel                @wuliendan

- [x] soul-plugin-sign                      @lxl910128

- [x] soul-plugin-apache-dubbo    

- [x] soul-plugin-alibaba-dubbo

- [x] soul-plugin-httpclient  @Trafalgar-YuI

- [x] soul-plugin-springcloud        @nuo-promise 

- [x] soul-plugin-sofa
- [x] soul-plugins-waf

**Comment by plutokaito** [comment]
get soul-plugin-divide

**Comment by wyc192273** [comment]
get soul-plugin-ratelimiter

**Comment by SaberSola** [comment]
get soul-plugin-resilience4j

**Comment by eazonshaw** [comment]
soul-plugin-httpclient

**Comment by en-o** [comment]
soul-plugin-springcloud

**Comment by tydhot** [comment]
dubbo and sofa

**Comment by lxl910128** [comment]
get  soul-plugin-sign

**Comment by BetterWp** [comment]
get soul-plugin-base

**Comment by wuudongdong** [comment]
get soul-plugin-rewrite

**Comment by guanyushen** [comment]
get soul-plugin-hystrix or  soul-plugin-springcloud or  soul-plugin-httpclient

**Comment by xiaoshuanglee** [comment]
soul-plugin-httpclient

**Comment by wuliendan** [comment]
get soul-plugin-sentinel

**Comment by wuudongdong** [comment]
> * [ ]  soul-plugin-base
> * [ ]  soul-plugin-hystrix
> * [ ]  soul-plugin-ratelimiter
> * [x]  soul-plugin-resilience4j
> * [x]  soul-plugin-rewrite
> * [ ]  soul-plugin-sentinel
> * [ ]  soul-plugin-sign
> * [x]  soul-plugin-apache-dubbo
> * [x]  soul-plugin-alibaba-dubbo
> * [ ]  soul-plugin-httpclient
> * [ ]  soul-plugin-springcloud
> * [x]  soul-plugin-sofa

**Comment by wolong0128** [comment]
take soul-plugin-httpclient

**Comment by Trafalgar-YuI** [comment]
get soul-plugin-httpclient

**Comment by nuo-promise** [comment]
Please soul-pulgin-hystrix assigned me @SaberSola

**Comment by yu199195** [comment]
@wolong0128  hi， you can participate in other tasks

**Comment by wolong0128** [comment]
> @wolong0128 hi， you can participate in other tasks

thanks

**Comment by nuo-promise** [comment]
Please soul-plugin-apache-dubbo assigned me @SaberSola

**Comment by nuo-promise** [comment]
Please soul-plugin-springcloud assigned me @SaberSola

**Comment by nuo-promise** [comment]
> Please soul-plugin-apache-dubbo assigned me @SaberSola 

merged #811
