### ISSUE TITLE
Add test cases for soul-sync-data-center module

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#480]
soul-sync-data-center module，If you are interested, you can reply to the participating modules The name of '@' behind is someone got.

- [x] soul-sync-data-http @0x12FD16B
- [x] soul-sync-data-nacos @kminjava
- [x] soul-sync-data-websocket @cocoZwwang
- [x] soul-sync-data-zookeeper @zendwang

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by 0x12FD16B** [comment]
please assign to me

**Comment by 0x12FD16B** [comment]
soul-data-sync-http

**Comment by kminjava** [comment]
I do. soul-data-nacos

**Comment by cocoZwwang** [comment]
soul-sync-data-websocket

**Comment by zendwang** [comment]
please assign to me.
soul-sync-data-zookeeper

**Comment by dengliming** [comment]
done
