### ISSUE TITLE
soul-common工具类测试集合

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#484]
需要对soul-common模块下未测试的工具类进行测试

- [x] GsonUtils.java @Trafalgar-YuI
- [x] HttpParamConverter.java @zendwang 
- [x] JsonUtils.java @strawberry-crisis
- [x] SignUtils.java @UniverseInHeart
- [x] UUIDUtils.java @BetterWp 
- [x] VersionUtils.java @Lin1nGithub

constant包下的测试类：
- [x] ZkPathConstants.java @songyuequan

pull reuqest 流程请看 ： https://dromara.org/website/en-us/docs/soul/contributor.html

**Comment by tangtian8** [comment]
please assign to me

**Comment by Trafalgar-YuI** [comment]
get GsonUtils.java

**Comment by strawberry-crisis** [comment]
plz assign JsonUtils.java to me

**Comment by zendwang** [comment]
please assign to me

**Comment by fightingting** [comment]
get SignUtils.java

**Comment by Lin1nGithub** [comment]
get VersionUtils.java

**Comment by songyuequan** [comment]
take VersionUtils.java

**Comment by BetterWp** [comment]
get UUIDUtils.java

**Comment by songyuequan** [comment]
take ZkPathConstants.java

**Comment by UniverseInHeart** [comment]
take  SignUtils.java

**Comment by yu199195** [comment]
@UniverseInHeart 领完了，下次优先分个给你

**Comment by UniverseInHeart** [comment]
> @UniverseInHeart SignUtils to you

thanks (*￣︶￣)

**Comment by songyuequan** [comment]
Hey~  I have finished ZkPathConstants.java, I think you forget to mark it in the TODO list @yu199195

**Comment by yu199195** [comment]
all finish it， we will close it
