### ISSUE TITLE
Test enums for soul-common

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#485]
- [x] ConfigGroupEnum @coderlmm
- [x] DataEventTypeEnum @50133142
- [x] DataSyncEnum @patrickWuP 
- [x] HttpMethodEnum @tangtian8
- [x] MatchModeEnum @sherk7monster
- [ ] OperatorEnum @mcnultyboy 
- [x] ParamTypeEnum @wilbur1991 
- [x] PluginEnum @abysscat-yj 
- [ ] RpcTypeEnum @xiaoshuanglee
- [x] SerializeEnum @Wincher 

pull reuqest ： https://dromara.org/website/en-us/docs/soul/contributor.html

**Comment by 50133142** [comment]
take DataEventTypeEnum

**Comment by xiaoshuanglee** [comment]
RpcTypeEnum

**Comment by tangtian8** [comment]
please assign to me HttpMethodEnum

**Comment by coderlmm** [comment]
领取 ConfigGroupEnum

**Comment by Wincher** [comment]
take SerializeEnum

**Comment by abysscat-yj** [comment]
PluginEnum

**Comment by wilbur1991** [comment]
take ParamTypeEnum

**Comment by mcnultyboy** [comment]
OperatorEnum

**Comment by mrly202016** [comment]
take RpcTypeEnum

**Comment by mrly202016** [comment]
take MatchModeEnum

**Comment by patrickWuP** [comment]
take DataSyncEnum

**Comment by sherk7monster** [comment]
take MatchModeEnum

**Comment by yu199195** [comment]
@sherk7monster  领取完了，下次优先分配给你

**Comment by songyuequan** [comment]
Hey~  @patrickWuP has  finished    DataSyncEnum   on  https://github.com/dromara/soul/pull/518  @yu199195
