### ISSUE TITLE
rewrite插件有示例么

### ISSUE THREAD

**Issue by CNlichao** [dromara/soul#489]
## Question

配置rewirte match  url；这样处理的结果进入divide我看到处理的还是原始url不是rewrite的url；
rewrite需要怎么使用？请提供下示例，谢谢！

**Comment by dengliming** [comment]
https://dromara.org/website/zh-cn/docs/soul/plugin-rewrite.html

**Comment by CNlichao** [comment]
> https://dromara.org/website/zh-cn/docs/soul/plugin-rewrite.html

这个不是示例，只是引入配置

**Comment by CNlichao** [comment]
怎么就给关了，也没解决问题啊

**Comment by tydhot** [comment]
> 怎么就给关了，也没解决问题啊

Can you describe in detail how you use the plugin and how it is ineffective

**Comment by CNlichao** [comment]
### rewrite配置
![rewrite config](https://github.com/CNlichao/images/blob/main/a.png?raw=true)
### divide 配置
![divide config](https://github.com/CNlichao/images/blob/main/b.png?raw=true)
### 请求地址
![request](https://github.com/CNlichao/images/blob/main/c.png?raw=true)
### AbstractMatchStrategy匹配规则的时候用的realpath
![AbstractMatchStrategy](https://github.com/CNlichao/images/blob/main/d.png?raw=true)
### divide只是最后转发用到rewrite变量
![divide](https://github.com/CNlichao/images/blob/main/e.png?raw=true)

## 疑问：
是不是只能处理单个地址的转发（转发到固定地址）？
且只能处理uri 最后一部分变化的这种情况（divide和rewrite配置相同 \a\**；转发\**部分）？（我开始以为像nginx那种转发 可以部分替换的）

**Comment by CNlichao** [comment]
@yu199195 @tydhot @yzhuomaoy

**Comment by CNlichao** [comment]
追加一问:
sign是不是也只支持单个uri匹配：
![sign config](https://github.com/CNlichao/images/blob/main/f.png?raw=true)
![sign code](https://github.com/CNlichao/images/blob/main/g.png?raw=true)
我rule 和 selector 内容配置的都是match 和 /sb-demo-api/**
代码这里直接是equal就过不去了；
是不是设计初中就是单个uri个赋权

**Comment by yu199195** [comment]
Can you describe it in English？

**Comment by CNlichao** [comment]
中文形容的问题不是问题？还是关掉了就不是问题， Cann't you read Chinese?

**Comment by CNlichao** [comment]
@tydhot  @yzhuomaoy

**Comment by tydhot** [comment]
All our issues are preparing to be translated into English, so we hope you can reopen an issue in English about this question .
