### ISSUE TITLE
Now slow down traffic (traffic warming up) for downstream HTTP services

### ISSUE THREAD

**Issue by xiangyang-gao** [dromara/soul#492]
soul现在针对下游的http服务，慢放流量（流量预热）
适用的业务场景：
下游的http服务刚启动成功时，会不太稳定，甚至有些链接可能还没建立成功，这个时候需要慢放流量（流量预热），避免大流量产生大量报错或耗时久问题。
属于服务稳定性需求
流量模型如下
![image](https://user-images.githubusercontent.com/15973635/100989676-0f1a2f80-358c-11eb-99f6-8bab8de0e3d3.png)

**Comment by lmhmhl** [comment]
Rate limiter plugin which use token bucket algorithm written in lua scripts can solve this. @yu199195
