### ISSUE TITLE
数据缓存失效

### ISSUE THREAD

**Issue by jaychoubaby** [dromara/soul#493]
## Environment

- Soul version(s): [e.g. 2.2.1]

## Steps to reproduce
使用一个内存较小的服务器运行，并频繁更新缓存

**Comment by yu199195** [comment]
能否描述清楚，有多小的内存？  有没gc？ 内存溢出的日志？

**Comment by nuo-promise** [comment]
@jaychoubaby 方便 贴出 当时 错误的 log 么？

**Comment by jaychoubaby** [comment]
> 能否描述清楚，有多小的内存？ 有没gc？ 内存溢出的日志？

其实主要是因为服务器运行了太多项目导致内存不够，重启网关之后恢复正常

**Comment by jaychoubaby** [comment]
> @jaychoubaby 方便 贴出 当时 错误的 log 么？

这个需要等待服务器再次异常的时候才可以截取到，我会留意下日志 稍后反馈
