### ISSUE TITLE
typo issue in HttpClientPluginConfiguration of prefix define for httpClientProperties

### ISSUE THREAD

**Issue by yzhuomaoy** [dromara/soul#494]
## Describe the bug
see title

## Environment

- Soul version(s): [e.g. 2.2.1]

## Fix the typo issue 
    @ConfigurationProperties(prefix = "soul.httpclinet")  -> fixed to "soul.httpclient"

**Comment by tydhot** [comment]
如果你有空的话 能不能参考这个流程https://dromara.org/website/en-us/docs/soul/contributor.html 提一个pr解决这个问题呢
