### ISSUE TITLE
Add test cases for soul-admin utils

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#505]
**_util:_**
- [x] AesUtils
- [x] CipherUtils

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by nuo-promise** [comment]
get

**Comment by HoldDie** [comment]
get

**Comment by HoldDie** [comment]
please assign me.

**Comment by PayneWoo** [comment]
CipherUtils

**Comment by HoldDie** [comment]
I've added both classes

**Comment by dengliming** [comment]
solved by [https://github.com/dromara/soul/pull/523](https://github.com/dromara/soul/pull/523), thanks to @HoldDie
