### ISSUE TITLE
Add test cases for soul-admin DataChangedListener

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#506]
**_listener:_**
- [ ] http @nuo-promise
- [ ] nacos @cottom
- [ ] websocket @hyuk-sudo
- [ ] zookeeper @tyjwan

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by 0x12FD16B** [comment]
assign to me

**Comment by nuo-promise** [comment]
get

**Comment by cottom** [comment]
nacos case

**Comment by hyuk-sudo** [comment]
take websocket case

**Comment by tyjwan** [comment]
get zookeeper test case
