### ISSUE TITLE
Add test cases for soul-admin service

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#507]
**_service_**
- [x] AppAuthService @jnzhouhao
- [x] DashboardUserService @cherlas
- [x] EnumService @onlyonezhongjinhui
- [x] MetaDataService @funpad
- [x] PluginHandleService @keru-s
- [x] PluginService @wuliendan
- [x] RuleService @kennhua
- [x] SelectorService @Lin1nGithub
- [x] SoulClientRegisterService @sakiila
- [x] SyncDataService @Redick01

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by Lin1nGithub** [comment]
get SelectorService

**Comment by wuliendan** [comment]
get PluginService

**Comment by Redick01** [comment]
> **_service_**
> 
> * [ ]  AppAuthService
> * [ ]  DashboardUserService
> * [ ]  EnumService
> * [ ]  MetaDataService
> * [ ]  PluginHandleService
> * [ ]  PluginService
> * [ ]  RuleService
> * [ ]  SelectorService
> * [ ]  SoulClientRegisterService
> * [ ]  SyncDataService
> 
> Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

SyncDataService

**Comment by Redick01** [comment]
get SyncDataService

**Comment by kennhua** [comment]
get RuleService

**Comment by onlyonezhongjinhui** [comment]
get EnumService

**Comment by funpad** [comment]
SyncDataService

**Comment by funpad** [comment]
MetaDataService

**Comment by jnzhouhao** [comment]
get  AppAuthService

**Comment by sakiila** [comment]
get  SoulClientRegisterService

**Comment by cherlas** [comment]
get DashboardUserService

**Comment by keru-s** [comment]
get PluginHandleService

**Comment by yu199195** [comment]
all merged ，thanks！
