### ISSUE TITLE
Add test cases for soul-admin config

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#508]
**_config:_**

- [x] DataSyncConfiguration @xwzwmt
- [x] HttpSyncProperties @onlyonezhongjinhui
- [x] NacosConfiguration、NacosProperties @cmj167
- [x] SecretConfiguration、SecretProperties @jjnnzb
- [x] SwaggerConfiguration @Lin1nGithub
- [x] WebConfig @Yejiajun
- [x] WebsocketSyncProperties @xiaoshen11
- [x] ZookeeperConfiguration、ZookeeperProperties @fengzhenbing

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by Lin1nGithub** [comment]
get SwaggerConfiguration

**Comment by BestChong** [comment]
get

**Comment by Yejiajun** [comment]
get WebConfig

**Comment by onlyonezhongjinhui** [comment]
HttpSyncProperties

**Comment by xwzwmt** [comment]
get DataSyncConfiguration

**Comment by xiaoshen11** [comment]
get WebsocketSyncProperties

**Comment by fengzhenbing** [comment]
get WebsocketSyncProperties

**Comment by fengzhenbing** [comment]
ZookeeperConfiguration、ZookeeperProperties

**Comment by jjnnzb** [comment]
get SecretConfiguration、SecretProperties

**Comment by cmj167** [comment]
get NacosConfiguration、NacosProperties

**Comment by dengliming** [comment]
done
