### ISSUE TITLE
Add test cases for soul-admin mapper

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#509]
**_mapper_**
- [x] AppAuthMapper @tangtian8
- [x] AuthParamMapper @sydgeek
- [x] AuthPathMapper @itmiwang
- [x] DashboardUserMapper @peiht
- [x] MetaDataMapper @Pismery
- [x] PluginHandleMapper @NemoIntellego
- [x] PluginMapper @HJ43
- [x] RuleConditionMapper @Andy-86
- [x] RuleMapper @hellboy0621
- [x] SelectorConditionMapper @bigwillc
- [x] SelectorMapper @coderlmm

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by tangtian8** [comment]
plase assign to me

**Comment by coderlmm** [comment]
take SelectorMapper

**Comment by hellboy0621** [comment]
take RuleMapper

**Comment by HJ43** [comment]
take PluginMapper

**Comment by peiht** [comment]
take DashboardUserMapper

**Comment by sydgeek** [comment]
take AuthParamMapper

**Comment by Andy-86** [comment]
take RuleConditionMapper

**Comment by itmiwang** [comment]
take AuthPathMapper

**Comment by NemoIntellego** [comment]
take PluginHandleMapper

**Comment by Pismery** [comment]
take MetaDataMapper

**Comment by bigwillc** [comment]
teke SelectorConditionMapper

**Comment by dengliming** [comment]
done
