### ISSUE TITLE
sign插件的使用方法

### ISSUE THREAD

**Issue by HYJgithub** [Dromara/soul#51]
作者你好。关于sign插件的使用，步骤是先要在认证管理创建一对module和appSecret，然后在sign插件中的选择器中，条件为module（认证管理填的值）；但是后面的规则中，   条件写method(具体拦截请求)，那下一行的处理是怎么填写的？请问我在认证管理和sign插件配置使用方法对么？

认证管理：
![image](https://user-images.githubusercontent.com/46957989/57510564-be077280-7339-11e9-84a9-b312fd908a06.png)
sign插件的选择器：
![image](https://user-images.githubusercontent.com/46957989/57510421-56e9be00-7339-11e9-82fc-f1aa660fba9e.png)
规则：
![image](https://user-images.githubusercontent.com/46957989/57510782-2eae8f00-733a-11e9-9079-6d9482aab673.png)

**Comment by HYJgithub** [comment]
在请求的的时候，还需要添加什么参数么？
![image](https://user-images.githubusercontent.com/46957989/57511389-c52f8000-733b-11e9-809a-777268f2de74.png)

**Comment by yu199195** [comment]
处理可以不填写，sign值你看下文档，有算法的，前端是同样的算法得到签名sign值，传递到网关

**Comment by HYJgithub** [comment]
作者你好，我看了文档的算法，但是还是验证不通过。可以帮我看一下我的请求头参数和RequestDTO初始化是否有错？
![image](https://user-images.githubusercontent.com/46957989/57593244-29855600-756d-11e9-86b2-16059f4f255f.png)
![image](https://user-images.githubusercontent.com/46957989/57593261-386c0880-756d-11e9-96bb-265a23ca16ca.png)
![image](https://user-images.githubusercontent.com/46957989/57593276-4a4dab80-756d-11e9-80ea-c84cffc145ef.png)

**Comment by yu199195** [comment]
SignPlugin 这个类，字段断点调试下，不就可以了？

**Comment by HYJgithub** [comment]
好的，谢谢

**Comment by HYJgithub** [comment]
谢谢。原来是要在header的参数中添加timestamp，即创建sign值的时间。
![image](https://user-images.githubusercontent.com/46957989/57595202-39edfe80-7576-11e9-98e3-3ea325a8a85d.png)
