### ISSUE TITLE
Add test cases for soul-admin controller

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#510]
**_controller_**
- [ ] AppAuthController @magicalxiaochen
- [x] ConfigController @HoldDie
- [x] DashboardUserController @operaxxx
- [x] IndexController @lw1243925457
- [x] MetaDataController @fcwalker
- [x] PlatformController @wangwenjie666
- [x] PluginController @guanyushen
- [x] PluginHandleController @charlesgongC
- [x] RuleController @shijie666
- [x] SelectorController @cchenxi
- [x] SoulClientController @branchen

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by HoldDie** [comment]
1

**Comment by lw1243925457** [comment]
1

**Comment by operaxxx** [comment]
get

**Comment by magicalxiaochen** [comment]
get AppAuthController

**Comment by branchen** [comment]
get IndexController

**Comment by shijie666** [comment]
get RuleController

**Comment by wangwenjie666** [comment]
get PlatformController

**Comment by fcwalker** [comment]
get MetaDataController

**Comment by branchen** [comment]
get SoulClientController

**Comment by cchenxi** [comment]
get SelectorController

**Comment by guanyushen** [comment]
get  PluginController

**Comment by charlesgongC** [comment]
get PluginHandleController

**Comment by dengliming** [comment]
done
