### ISSUE TITLE
refactor chinese to english in soul.sql

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#511]
Hi :
All communitys, we should  refactor chinese to english in soul.sql 

you can find it in :   https://github.com/dromara/soul/blob/master/script/soul.sql  and  https://github.com/dromara/soul/blob/master/soul-admin/src/main/resources/META-INF/schema.sql 

The Chinese description in it is changed to English.

Please read the Contribution Guideline before submitting the PR  .  thanks !

**Comment by yiwenlong** [comment]
get

**Comment by evasnowind** [comment]
assign me

**Comment by funpad** [comment]
手都这么快的么
