### ISSUE TITLE
Whether the Test Case needs to be standardized？

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#527]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]
Improve code quality

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.
We can divide it into 
Functions, logic, and scenarios
I think this can be used as a judgment at the time of review.

**Comment by tydhot** [comment]
How to describe the standard

**Comment by nuo-promise** [comment]
> How to describe the standard

My understanding is that this is actually to see the function of the class, if it is just a simple tool class, then it is a simple functional test. If there is a relationship between the functions of the class itself, then the function test needs to test whether the relationship between the functions gets through after passing it. Scenario testing this currently I think should be attached with modules above.
