### ISSUE TITLE
dubbo插件开启之后无法访问

### ISSUE THREAD

**Issue by laulee5135** [Dromara/soul#53]
作者好，请问一下，开启了dubbo插件相关的配置和配了，但就是无法访问，能进soul但是没有任何返回，也没有跳转到dubbo服务去，主要是也没有任何错误信息。。。照着视频配的都不行。。。
![image](https://user-images.githubusercontent.com/26890253/57581460-3a40b800-74ea-11e9-81d3-1a543b3a4de8.png)
配置选择器：
![image](https://user-images.githubusercontent.com/26890253/57581469-4e84b500-74ea-11e9-81a1-a20c21095c93.png)
配置规则：
![image](https://user-images.githubusercontent.com/26890253/57581472-57758680-74ea-11e9-94b7-12314634c104.png)
开启dubbo插件：
![image](https://user-images.githubusercontent.com/26890253/57581478-62301b80-74ea-11e9-9bbe-af11f3b299cf.png)
代码还是那些。求救看看是咋回事，谢谢

**Comment by yu199195** [comment]
最新版本dubbo参数是从body里面传过去，视频是之前的版本

**Comment by laulee5135** [comment]
> 最新版本dubbo参数是从body里面传过去，视频是之前的版本
谢谢。还真是，立马就好了，看了一下午😢
