### ISSUE TITLE
soul-admin下 AppAuthMapper 中 insertSelective 方法异常  

### ISSUE THREAD

**Issue by tangtian8** [dromara/soul#558]
## Describe the bug
insertSelective(AppAuthDO appAuthDO)
如果appAuthDO不传入userId和extInfo该方法正确使用
但是传入extInfo或userId其中一个 会抛出异常

## Environment

- Soul version(s): [e.g. 2.2.1]

## Steps to reproduce
在测试用例中
实例AppAuthDO对象appAuthDO
每个属性都设置值
特别注意给下面赋值
        appAuthDO.setExtInfo("");
        appAuthDO.setUserId("");
调用insertSelective(AppAuthDO appAuthDO)

## Expected behavior
成功返回1

## Debug logs

<details>
<summary>Click to expand</summary>

```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'user_id' in 'class org.dromara.soul.admin.entity.AppAuthDO'
```
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'ext_info' in 'class org.dromara.soul.admin.entity.AppAuthDO'
```

</details>

**Comment by dengliming** [comment]
![image](https://user-images.githubusercontent.com/7796156/101237277-56cac380-3712-11eb-8f9f-bf8799edc8af.png)

你改下这里吧
