### ISSUE TITLE
如何集成链路追踪工具

### ISSUE THREAD

**Issue by laulee5135** [Dromara/soul#56]
作者好，感谢前几次的回复。soul是异步的框架，那他怎么使用依赖threadlocal的链路追踪工具呀，比如cat、zipkin这些工具呢？

**Comment by yu199195** [comment]
和soul没关系

**Comment by laulee5135** [comment]
比如用CAT，它本身是用threadlocal来收集日志的，但是soul又是异步的，只会把请求转发给后端集群，这样的话，一个请求在网关和后端服务之间是分离的，CAT的threadlocal就不起作用的了呀。

**Comment by zparkgao** [comment]
that's a good question
