### ISSUE TITLE
Only use SecretProperties or remove it

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#570]
## Describe the bug

This bean is defined as below code:
```
/**
     *  egister cipherUtils in spring ioc.
     *
     * @return CipherUtils
     */
    @Bean
    @ConditionalOnProperty(prefix = "soul.aes.secret", value = "key", havingValue = "2095132720951327")
    public SecretProperties secretProperties() {
        return new SecretProperties();
    }
```
But we currently only use in this way. and the key is inconsistent.
`org.dromara.soul.admin.service.impl.DashboardUserServiceImpl`
`org.dromara.soul.admin.controller.DashboardUserController`
```
 @Value("${aes.secret.key:2095132720951327}")
    private String aesKey;
```

## Environment

- Soul version(s): [e.g. 2.2.1]

## Expected behavior

Keep consistent. Only use `SecretProperties`

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by jjnnzb** [comment]
Get this task.

**Comment by dengliming** [comment]
@jjnnzb Thanks for your contribution.

**Comment by dengliming** [comment]
closed by [https://github.com/dromara/soul/pull/593](https://github.com/dromara/soul/pull/593)
