### ISSUE TITLE
soul扩展功能

### ISSUE THREAD

**Issue by HYJgithub** [Dromara/soul#59]
作者你好，我在soul-web这个模块中的plugin文件夹中实现soulplugin接口，程序也会运行（即执行自定义插件），但是要如何接收到boby或者是自定义的内容呢？（或者自定义的内容存放在哪里）

![image](https://user-images.githubusercontent.com/46957989/57909768-4a73e100-78b6-11e9-94af-c9ba492a8d8b.png)

**Comment by yu199195** [comment]
仔细看看文档

**Comment by HYJgithub** [comment]
作者你好，我看了文档还是有点疑问。扩展的话需要重新创建一个模块么？还是在一个指定的模块里进行开发？扩展模块的操作步骤：1.继承或者实现soulplugin，2.在管理中心创建指对应的插件模块与规则；这样理解是否有误？

**Comment by yu199195** [comment]
这个已经是java基础问题了。 扩展就是引用soul-web的jar包，然后再实现接口，当然你在源码的基础上更改也是一样，就好像你实现spring的接口，引用spring，实现他的接口是一样的，个人建议是建立自己项目，就像soul-bootstrap那样。方便自己的项目特性，其次是soul-web有更新，你不需要管，其他的问题你加群问下其他人

**Comment by xiaoluozai** [comment]
> 这个已经是 java 基础问题了。 扩展就是引用 soul-web 的 jar 包，然后再实现接口，当然你在源码的基础上更改也是一样，就好像你实现 spring 的接口，引用 spring，实现他的接口是一样的，个人建议是建立自己项目，就像 soul-bootstrap 那样。方便自己的项目特性，其次是 soul-web 有更新，你不需要管，其他的问题你加群问下其他人

群加不了，为什么
