### ISSUE TITLE
About GsonUtils.java issue

### ISSUE THREAD

**Issue by Trafalgar-YuI** [dromara/soul#595]
## Describe the bug
has three issue in GsonUtils.java
1.  the convertToMap of method with high Cognitive Complexity will be difficult to maintain. Too many nested relationships,  to  read the code.
```java
/**
 * Convert to map map.
 *
 * @param json the json
 * @return the map
 */
public Map<String, Object> convertToMap(final String json) {
    Map<String, Object> map = GSON_MAP.fromJson(json, new TypeToken<Map<String, Object>>() {
    }.getType());
    if (!map.isEmpty()) {
        for (String key : map.keySet()) {
            Object value = map.get(key);
            if (value instanceof String) {
                String valueStr = ((String) value).trim();
                if (valueStr.startsWith("{") && valueStr.endsWith("}")) {
                    Map<String, Object> mv = convertToMap(value.toString());
                    map.put(key, mv);
                }
            } else if (value instanceof JsonObject) {
                map.put(key, convertToMap(value.toString()));
            } else if (value instanceof JsonArray) {
                JsonArray jsonArray = (JsonArray) value;
                List<Object> mapList = new ArrayList<>(jsonArray.size());
                for (Object object : jsonArray) {
                    String objStr = this.toJson(object);
                    if (objStr.startsWith("{") && objStr.endsWith("}")) {
                        mapList.add(convertToMap(object.toString()));
                    } else {
                        mapList.add(objStr);
                    }
                }
                map.put(key, mapList);
            }
        }
    }
    return map;
}
```
2. And the convertToMap of method has Gson's class about JsonArray, it will append quotation marks around String. I will check JsonArray.java.
it's test case
```java
Map<String, Object> map = new HashMap<>();
List<String> innerList = new ArrayList<String>() {
    {
        add("1");
        add("2");
        add("3");
    }
};
map.put("list", innerList);
String testJson = "{\"list\":[\"1\",\"2\",\"3\"]}";

Map<String, Object> parseMap = GsonUtils.getInstance().convertToMap(testJson);
Assert.assertEquals(map, parseMap);
```
it's result
![](https://user-images.githubusercontent.com/13451528/101285823-443faf80-3822-11eb-9f31-317211a75f8a.png)

3. The toTreeMap of method, type of ConcurrentSkipListMap, but Gson transform to LinkedHashMap
```java
/**
 * To tree map tree map.
 *
 * @param json the json
 * @return the tree map
 */
public ConcurrentSkipListMap<String, Object> toTreeMap(final String json) {
    return GSON_MAP.fromJson(json, new TypeToken<ConcurrentSkipListMap<String, Object>>() {
    }.getType());
}
```
it's test case
```java
ConcurrentSkipListMap<String, Object> map = new ConcurrentSkipListMap<String, Object>(){
    {
        put("name", "test");
        put("id", 123);
    }
};
String json = "{\"name\":\"test\",\"id\":123}";
ConcurrentSkipListMap<String, Object> parseMap = GsonUtils.getInstance().toTreeMap(json);
Assert.assertEquals(map, parseMap);
```
it's Gson's method
![](https://user-images.githubusercontent.com/13451528/101286077-8a494300-3823-11eb-862b-ddf963292c33.png)
it's result
![](https://user-images.githubusercontent.com/13451528/101286081-8e756080-3823-11eb-8058-1832a6fb1578.png)
the type is changed

## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
can you fix it？

**Comment by Trafalgar-YuI** [comment]
yeah, I will do

**Comment by tydhot** [comment]
About no.2 , do you think there is something wrong with parseMap?

**Comment by Trafalgar-YuI** [comment]
> About no.2 , do you think there is something wrong with parseMap?

I fount the reason, the JsonArray's inside is JsonElement, but it forced transform to Object. Using Object's toString method is wrong. 
So, using JsonElement's getAsString method can resolve it.

**Comment by Nero-Chaos** [comment]
> > About no.2 , do you think there is something wrong with parseMap?
> 
> I fount the reason, the JsonArray's inside is JsonElement, but it forced transform to Object. Using Object's toString method is wrong.
> So, using JsonElement's getAsString method can resolve it.

I sent a request like {"a":[{"b":"xx"}]}.And I got the error

> java.lang.UnsupportedOperationException: JsonObject
        at com.google.gson.JsonElement.getAsString(JsonElement.java:191) ~[gson-2.8.0.jar!/:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.dromara.soul.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.dromara.soul.web.filter.WebSocketParamFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.dromara.soul.web.filter.FileSizeFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.dromara.soul.bootstrap.filter.HealthFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/xxx" [ExceptionHandlingWebHandler]
Stack trace:
                at com.google.gson.JsonElement.getAsString(JsonElement.java:191) ~[gson-2.8.0.jar!/:na]
                at org.dromara.soul.common.utils.GsonUtils.jsonArrayToListInConvertToMap(GsonUtils.java:277) ~[soul-common-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.common.utils.GsonUtils.convertToMap(GsonUtils.java:259) ~[soul-common-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.plugin.base.utils.RpcParamUtils.buildSingleParameter(RpcParamUtils.java:49) ~[soul-plugin-base-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.plugin.base.utils.RpcParamUtils.buildParameters(RpcParamUtils.java:69) ~[soul-plugin-base-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.web.rpc.DefaultDubboParamResolveServiceImpl.buildParameter(DefaultDubboParamResolveServiceImpl.java:33) ~[soul-web-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.plugin.alibaba.dubbo.proxy.AlibabaDubboProxyService.genericInvoker(AlibabaDubboProxyService.java:73) ~[soul-plugin-alibaba-dubbo-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.plugin.alibaba.dubbo.AlibabaDubboPlugin.doExecute(AlibabaDubboPlugin.java:79) ~[soul-plugin-alibaba-dubbo-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.plugin.base.AbstractSoulPlugin.execute(AbstractSoulPlugin.java:95) ~[soul-plugin-base-2.2.1.jar!/:2.2.1]
                at org.dromara.soul.web.handler.SoulWebHandler$DefaultSoulPluginChain.lambda$execute$0(SoulWebHandler.java:100) ~[soul-web-2.2.1.jar!/:2.2.1]

May we should use the toString instead of getAsString in GsonUtils.java:277 ?
