### ISSUE TITLE
内存持续缓慢增长，长时间（三个月）增长至70%多

### ISSUE THREAD

**Issue by maoly1012** [dromara/soul#612]
## Environment

- Soul version(s): 2.1.2-RELEASE

## mat分析内存泄漏如下图
![Image of mat](https://images.gitee.com/uploads/images/2020/1208/093037_b283b517_1241133.png)

**Comment by dengliming** [comment]
提供下你dump出的源文件？

**Comment by maoly1012** [comment]
> 提供下你dump出的源文件？



文件上传不了，只能传10m,    QQ群里已经上传过了

**Comment by SaberSola** [comment]
上次我看了一下,chunk里边是lettcue的线程,但是存的数据有很多业务数据,soul里边用到的lettcue只有redis限流的么,不应该有大量的业务数据,是不是你这边对网关有扩展造成连接泄露之类的

**Comment by yu199195** [comment]
We will close this issue. You can write a new issue in English. We will look at this issue.
