### ISSUE TITLE
add test case for module soul-client

### ISSUE THREAD

**Issue by tydhot** [dromara/soul#615]
- [ ] soul-client-alibaba-dubbo @0x12FD16B
- [ ] soul-client-apache-dubbo @nuo-promise
- [x] soul-client-springcloud @plutokaito
- [x] soul-client-sofa @HoldDie 

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

You can take reference soul-client-springmvc's test case.

**Comment by branchen** [comment]
get soul-client-alibaba-dubbo

**Comment by plutokaito** [comment]
get soul-client-springcloud

**Comment by lw1243925457** [comment]
get soul-client-apache-dubbo

**Comment by nuo-promise** [comment]
get soul-client-sofa

**Comment by tydhot** [comment]
> get soul-client-sofa

猫大不是说有别的安排给你么。。。

**Comment by HoldDie** [comment]
get soul-client-sofa

**Comment by HoldDie** [comment]
那我来吧，嘎嘎

**Comment by HoldDie** [comment]
啪的一下子，很快奥！
