### ISSUE TITLE
waf插件条件使用ip控制

### ISSUE THREAD

**Issue by HYJgithub** [Dromara/soul#62]
作者你好，对于在waf插件的条件中，有ip这个选项，如果使用ip这个选项，那么条件填写的格式是怎么样的呀?
![image](https://user-images.githubusercontent.com/46957989/58223344-d28d3700-7d4b-11e9-8065-4b3f6ad95dbf.png)
![image](https://user-images.githubusercontent.com/46957989/58223371-e9338e00-7d4b-11e9-9c4b-ce53e294ba1c.png)

**Comment by HYJgithub** [comment]
在条件中，前面的条件是任意字符
![image](https://user-images.githubusercontent.com/46957989/58298200-37f52c80-7e0d-11e9-987f-8e85ddc0f8df.png)

**Comment by yu199195** [comment]
ip和 host 这里可以是任意字符，是根据后面的值，与httpReuqest 中的ip，host来匹配的
