### ISSUE TITLE
Add Test Case For soul-metrics

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#651]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

**Comment by tydhot** [comment]
We are preparing to dismantle this part of the test case.

**Comment by nuo-promise** [comment]
> We are preparing to dismantle this part of the test case.

Give me all this module. I'll try it

**Comment by tydhot** [comment]
ok
