### ISSUE TITLE
add test case 4 soul-admin listener package

### ISSUE THREAD

**Issue by tydhot** [dromara/soul#652]
- [x] org.dromara.soul.admin.listener.zookeeper.HttpServiceDiscovery. HttpServiceDiscovery  & org.dromara.soul.admin.listener.zookeeper.HttpServiceDiscovery.ZookeeperDataInit @bitkylin

- [x] org.dromara.soul.admin.listener.http.HttpLongPollingDataChangedListener (@onlyonezhongjinhui )

Now the 2 of part's coverage is pretty low.

**Comment by onlyonezhongjinhui** [comment]
get org.dromara.soul.admin.listener.http.HttpLongPollingDataChangedListener

**Comment by bitkylin** [comment]
get org.dromara.soul.admin.listener.zookeeper.HttpServiceDiscovery. HttpServiceDiscovery & org.dromara.soul.admin.listener.zookeeper.HttpServiceDiscovery.ZookeeperDataInit
