### ISSUE TITLE
Add test case for soul-common

### ISSUE THREAD

**Issue by SaberSola** [dromara/soul#654]
- [ ]  org.dromara.soul.common.concurrent.SoulThreadFactory  @FocusZhouGD

- [ ] org.dromara.soul.common.utils.ThreadUtils      @onlyonezhongjinhui

**Comment by onlyonezhongjinhui** [comment]
get org.dromara.soul.common.utils.ThreadUtils

**Comment by FocusZhouGD** [comment]
get SoulThreadFactory
