### ISSUE TITLE
Add test case for soul-common constants&enum

### ISSUE THREAD

**Issue by SaberSola** [dromara/soul#655]
- [x] org.dromara.soul.common.constant.RedisKeyConstants  @DaveModl 

- [x] org.dromara.soul.common.enums.OperatorEnum    @bigwillc

- [ ] org.dromara.soul.common.enums.SelectorTypeEnum @branchen

**Comment by DaveModl** [comment]
assign **RedisKeyConstants**  to me..

**Comment by branchen** [comment]
get SelectorTypeEnum

**Comment by bigwillc** [comment]
get operatorEnum

**Comment by DaveModl** [comment]
> * [x]  org.dromara.soul.common.constant.RedisKeyConstants  @DaveModl
> * [x]  org.dromara.soul.common.enums.OperatorEnum    @bigwillc
> * [ ]  org.dromara.soul.common.enums.SelectorTypeEnum @branchen
