### ISSUE TITLE
Optimize test cases to improve code coverage.

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#668]
- [x] ReflectUtils @augfool
- [x] ParamCheckUtils @xwzwmt 
- [x] HttpParamConverter @xxl115
- [x] LogUtils  @HoldDie 
- [x] UUIDUtils  @xiaoshen11 
- [x] JsonUtils @Trafalgar-YuI 
- [x] ExtensionLoader @wyc192273
- [x] ExceptionHandlers  @bigwillc 
- [x] PluginController @xxl115
- [x] SoulDictController @zendwang
- [x] MetaDataController @prospect167

https://codecov.io/gh/dromara/soul

**Comment by augfool** [comment]
get

**Comment by augfool** [comment]
get  ReflectUtils

**Comment by wyc192273** [comment]
get ExtensionLoader

**Comment by xiaoshen11** [comment]
get UUIDUtils

**Comment by HoldDie** [comment]
get LogUtils

**Comment by bigwillc** [comment]
get ExceptionHandlers

**Comment by zendwang** [comment]
get SoulDictController

**Comment by xwzwmt** [comment]
get ParamCheckUtils

**Comment by xxl115** [comment]
PluginController

**Comment by xxl115** [comment]
get MetaDataController

**Comment by 0x12FD16B** [comment]
PluginController

**Comment by prospect167** [comment]
get MetaDataController

**Comment by xxl115** [comment]
get HttpParamConverter
