### ISSUE TITLE
Test enums in soul-common

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#687]
- [x] HystrixIsolationModeEnum @HoldDie 
- [x] LoadBalanceEnum @tyjwan 
- [x] PluginRoleEnum  @iitdachaoge
- [x] RedisModeEnum @YarNeCn
- [x] ResultEnum @rockpig
- [x] WafEnum @sharpzhango 
- [x] WafModuleEnum @xwzwmt

**Comment by HoldDie** [comment]
get RedisModeEnum

**Comment by YarNeCn** [comment]
get RedisModeEnum

**Comment by itdachaoge** [comment]
get PluginRoleEnum

**Comment by rockpig** [comment]
get ResultEnum

**Comment by tyjwan** [comment]
LoadBalanceEnum

**Comment by sharpzhango** [comment]
get WafEnum

**Comment by xwzwmt** [comment]
WafModuleEnum

**Comment by kennhua** [comment]
get WafModuleEnum

**Comment by flwrchild42** [comment]
Yes

**Comment by yu199195** [comment]
all merged thanks
