### ISSUE TITLE
ResponsePlugin没有处理http response header和其它code、cookie

### ISSUE THREAD

**Issue by hujunzhong** [Dromara/soul#69]
比如应用返回302会转化成200

**Comment by yu199195** [comment]
soul只不过是包装了一层，你也可以自定义ResponsePlugin 重写它

**Comment by hujunzhong** [comment]
好的，目前我们是自己加了个plugin处理的，谢谢

**Comment by yu199195** [comment]
可以提供你们的pr，上来看看，使用者，请登记

**Comment by chengdongwei** [comment]
> 好的，目前我们是自己加了个plugin处理的，谢谢

你好。现在也遇到同样的问题一直返回200。而且redirect参数丢失比如三个参数只有一个。
