### ISSUE TITLE
生产环境实践问题

### ISSUE THREAD

**Issue by mushanzi1216** [Dromara/soul#7]
请问这套东西有在生产环境部署过嘛，实际使用情况如何

**Comment by SteNicholas** [comment]
@mushanzi1216 肯定部署过

**Comment by timGRK** [comment]
是国内哪个大厂部署过啊

**Comment by mushanzi1216** [comment]
同问

**Comment by klboke** [comment]
各位，我们凯京集团：https://www.keking.com 生产集群跑了大半年了，对soul做了纯粹的业务二开，以及很小的改动，基本没动核心，直接代替了原来的Nginx + lua的模式（这种模式维护麻烦）。线上资源占用很稳定，放心使用吧

**Comment by zhisheng17** [comment]
@klboke 优秀
