### ISSUE TITLE
divideplugin的重试

### ISSUE THREAD

**Issue by liuzhebaba** [Dromara/soul#70]
divide插件配置了重试，看到代码没有用到retry字段，而且配置的重试次数也确实没起作用，是bug么？
![image](https://user-images.githubusercontent.com/22785707/59255658-fc5bbe80-8c64-11e9-8620-233cee6587fe.png)

**Comment by yu199195** [comment]
重试会有内存溢出的风险，已经被去除了

**Comment by yzhuomaoy** [comment]
根据最新(2.2.1版本)的使用WebClient，该重试可以加进来，尝试了下可用，是否存在内存溢出风险？

**Comment by yzhuomaoy** [comment]
> 重试会有内存溢出的风险，已经被去除了

根据最新(2.2.1版本)的使用WebClient，该重试可以加进来，尝试了下可用，是否存在内存溢出风险？

**Comment by tydhot** [comment]
> > 重试会有内存溢出的风险，已经被去除了
> 
> 根据最新(2.2.1版本)的使用WebClient，该重试可以加进来，尝试了下可用，是否存在内存溢出风险？

Maybe you need to provide proof that the problem no longer exists, such as links to version iterations.And we encourage communication in English in github
