### ISSUE TITLE
有官方钉钉群吗

### ISSUE THREAD

**Issue by wanhuhou** [Dromara/soul#71]
有官方钉钉群吗

**Comment by yu199195** [comment]
只有qq 或者微信群哈

**Comment by wanhuhou** [comment]
微信群是哪个 发下

**Comment by zhisheng17** [comment]
微信群需要加 @yu199195 微信好友，然后拉你进微信群，可以先加 QQ 群 

![](https://camo.githubusercontent.com/4e1586393c969a0e64c6d91a524535d9ddb64c5d/68747470733a2f2f79753139393139352e6769746875622e696f2f696d616765732f736f756c2d71712e706e67)
