### ISSUE TITLE
soul文档

### ISSUE THREAD

**Issue by wanhuhou** [Dromara/soul#72]
部署 server 菜单
修改application.yml,如果zookeeper插件是必须配置的。 如果你使用限流插件，请配置redis。如果是使用监控插件，请配置influxdb，如果是使用springcloud插件，还需要配置eureka.句话是不是有问题

**Comment by yu199195** [comment]
目前是这样的，下个版本会改掉，有比较大的更新

**Comment by wanhuhou** [comment]
如果zookeeper插件是必须配置的。预发错误吧，还有就是我把吧server配置文件 删掉 关于influxdb 和eureka的配置，网关启动报错，难道是强制依赖这些东西吗

**Comment by wanhuhou** [comment]
下个版本什么时候发布

**Comment by yu199195** [comment]
并不是必须的，只不过依赖了start包，你去掉配置，会报错，这是基本的spring boot 常识。 下个版本会改掉，

**Comment by klboke** [comment]
@wanhuhou 我们正在调研soul，去掉eureka需要在配置文件中关闭，如： eureka.client.enabled = false 。
不用监控的话，去掉influxdb，需要修改InfluxDbService.java中InfluxDBTemplate的注入方式，如：
`    @Autowired(required = false)
    private InfluxDBTemplate influxDBTemplate; 
`
这样，在配置文件中去除eureka和influxDb的配置就不影响应用启动了

**Comment by timGRK** [comment]
文档在实际操作过，希望再细节完善一下！东西的设计理念目前与业界这些zuul 、gateway，kong，openresty比较，对于一个体系化的java微服务网关来说，那些都弱爆。
