### ISSUE TITLE
Questions in rate limiting plugin.

### ISSUE THREAD

**Issue by lmhmhl** [dromara/soul#749]
## Describe the bug

In rate limiting plugin, users can not configure the replenish rate and capacity by themself. So front pages should add some options for users.
## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
that is not bug.   users can config it
