### ISSUE TITLE
认证管理

### ISSUE THREAD

**Issue by 59471032** [Dromara/soul#75]
![image](https://user-images.githubusercontent.com/1281536/60066373-7c8c2480-9739-11e9-867b-ab38ef236d11.png)
无法更新秘钥appSecret

**Comment by 59471032** [comment]
![image](https://user-images.githubusercontent.com/1281536/60066404-a1809780-9739-11e9-83dc-fab4c00229d2.png)

**Comment by yu199195** [comment]
下个版本 修正，目前可以先删除再添加，不能修改
