### ISSUE TITLE
签名插件似乎没有对请求内容进行签名

### ISSUE THREAD

**Issue by huangxiupu** [dromara/soul#752]
## Question
soul 自带的签名插件似乎只能对请求进行认证，并且参与签名计算的只有时间戳、版本号、请求路径等基本参数，只能满足最低限度的调用接口调用合法性。
安全性要求更高的加验签机制计算要素应该包含接口内容的所有字段或关键字段。
接口请求进行验签，接口应答加签。

**Comment by yu199195** [comment]
please in english
