### ISSUE TITLE
为何服务重启了网关就会进入假死状态？

### ISSUE THREAD

**Issue by jaychoubaby** [dromara/soul#760]
## Describe the bug
当服务发包重启服务，对应的soul网关就会进入假死状态，必须重启网关才能调用

## Environment

- Soul version(s): [e.g. 2.2.1]

## Steps to reproduce
重启网关对应的服务，然后服务调用网关接口则无法通过

## Expected behavior
正常情况网关与服务应该互不干预，服务重启应该不会影响到网关

## Debug logs
没有日志

**Comment by yu199195** [comment]
please in English。 we will close it。
