### ISSUE TITLE
FileSizeFilter maxSize properties bug

### ISSUE THREAD

**Issue by bygzh958** [dromara/soul#782]
![image](https://user-images.githubusercontent.com/76154300/102465668-e95f5100-4088-11eb-8421-11762dca7dc8.png)

**Comment by bygzh958** [comment]
期待是10 但实际上是0 2.2.2版本

**Comment by bygzh958** [comment]
更正一下 soul 2.2.1版本

**Comment by bygzh958** [comment]
maxSize 初始化后期待默认值是10 但实际上是0 
Soul 2.2.1版本

**Comment by dengliming** [comment]
We only accept English here and please folow this template `https://github.com/dromara/soul/issues/new?labels=type%3A+bug&template=bug-report.md`

**Comment by yu199195** [comment]
can you set  soul.file.enabled = true？ please in english，we will close it

**Comment by yu199195** [comment]
we fixed in master，thanks
