### ISSUE TITLE
FileSizeFilter codec method not working

### ISSUE THREAD

**Issue by bygzh958** [dromara/soul#783]
Soul 2.2.1
FileSizeFilter的相关代码：
 HandlerStrategies.builder().codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(maxSize * BYTES_PER_MB));
 this.messageReaders = HandlerStrategies.withDefaults().messageReaders();

codecs()方法未按预期生效 改成如下代码段解决：
 HandlerStrategies.Builder builder = HandlerStrategies.builder();
       builder.codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(maxSize * BYTES_PER_MB));
        this.messageReaders = builder.build().messageReaders();

**Comment by dengliming** [comment]
Seems you already found the solution. Would you mind submit a PR. BTW Can you describe more detail about the exactly behavior you expected?

**Comment by bygzh958** [comment]
In previous code， when upload a picture more than 256k with multipart file, an exception throws:
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
    at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:101)
    Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
   ...

When I change the code, this exception dispeared

**Comment by bygzh958** [comment]
HandlerStrategies.builder().codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(maxSize * BYTES_PER_MB));
-- New an object with maxInMemorySize of maxSize * BYTES_PER_MB

this.messageReaders = HandlerStrategies.withDefaults().messageReaders();
-- New another object with maxInMemorySize of defaut value :262144

So need change code to pointer to the same object  of ServerCodecConfigurer in DefaultHandlerStrategiesBuilder

**Comment by yu199195** [comment]
we will fix it
