### ISSUE TITLE
Improve code coverage in soul-client-apache-dubbo

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#798]
- [ ]  ApacheDubboClientValidation
- [ ] ApacheDubboClientValidator
- [ ] ApacheDubboServiceBeanPostProcessor

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by nuo-promise** [comment]
Please assigned to me @yu199195

**Comment by xwzwmt** [comment]
get ApacheDubboClientValidation

**Comment by fengzhenbing** [comment]
get ApacheDubboServiceBeanPostProcessor

**Comment by nuo-promise** [comment]
This module task cannot be separated, you can exercise other modules @xwzwmt @fengzhenbing

**Comment by coderlmm** [comment]
get ApacheDubboClientValidator
