### ISSUE TITLE
Improve code coverage in soul-client-dubbo-common

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#799]
- [ ] DubboConfig
- [ ] DubboRpcExt
- [ ] MetaDataDTO

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by xxl115** [comment]
get DubboConfig

**Comment by zendwang** [comment]
get DubboRpcExt

**Comment by HoldDie** [comment]
get DubboConfig
