### ISSUE TITLE
Improve code coverage in soul-client-springcloud

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#800]
- [ ] SpringCloudClientBeanPostProcessor

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by lxl910128** [comment]
let my try SpringCloudRegisterDTO

**Comment by plutokaito** [comment]
get SoulSpringCloudConfig

**Comment by DaveModl** [comment]
I want all..

**Comment by HoldDie** [comment]
get SoulSpringCloudConfig

**Comment by yu199195** [comment]
@DaveModl  you maybe To complete all

**Comment by HoldDie** [comment]
This task has been completed, I just tested, the class coverage is 100%.
Please close this issue.

**Comment by HoldDie** [comment]
![](https://cdn.jsdelivr.net/gh/HoldDie/img1/20210128204843.png)
