### ISSUE TITLE
Improve code coverage in soul-client-springmvc

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#801]
- [ ] SpringMvcClientBeanPostProcessor @onlyonezhongjinhui
- [ ] IpUtils @HoldDie

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by onlyonezhongjinhui** [comment]
get

**Comment by HoldDie** [comment]
get IpUtils
