### ISSUE TITLE
Improve code coverage in soul-admin

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#802]
- [x] SoulClientRegisterServiceImpl @plutokaito
- [x] UpstreamCheckService @zendwang
- [x] AppAuthServiceImpl  @magicalxiaochen 
- [x] MetaDataServiceImpl  @yiwenlong
- [x] PluginServiceImpl @midnight2104
- [x] SelectorServiceImpl  @yiwenlong 
- [x] SoulDictServiceImpl @branchen 
- [x] AesUtils @wuudongdong
- [ ] SoulResultMessage @Halcastle 
 

They already have test classes. Please modify them on the original test class。

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by yiwenlong** [comment]
Get

**Comment by wuudongdong** [comment]
get AesUtils

**Comment by zendwang** [comment]
get UpstreamCheckService

**Comment by magicalxiaochen** [comment]
get AppAuthServiceImpl

**Comment by yiwenlong** [comment]
Get SelectorServiceImpl

**Comment by Halcastle** [comment]
get SoulResultMessage

**Comment by branchen** [comment]
get SoulDictServiceImpl

**Comment by plutokaito** [comment]
get  SoulClientRegisterServiceImpl

**Comment by midnight2104** [comment]
assign PluginServiceImpl to me, please

**Comment by wuudongdong** [comment]
AesUtils done.

**Comment by HoldDie** [comment]
- [ ] SoulClientRegisterServiceImpl

This task has been completed. Please mark completed.

![](https://cdn.jsdelivr.net/gh/HoldDie/img1/20210128205648.png)

**Comment by HoldDie** [comment]
- [ ] SoulDictServiceImpl

This task has been completed. Please mark completed.

![](https://cdn.jsdelivr.net/gh/HoldDie/img1/20210128205812.png)

**Comment by HoldDie** [comment]
- [ ] SoulResultMessage

This is a constant class that holds static fields and does not require a test class.

![image](https://user-images.githubusercontent.com/22816271/106141909-c194fa00-61ab-11eb-89cc-a0202a0bb50c.png)

**Comment by HoldDie** [comment]
Please close this issue, LGTM. @yu199195
