### ISSUE TITLE
浏览器异常信息返回乱码

### ISSUE THREAD

**Issue by plm479104792** [dromara/soul#803]
## Question

// your question here;
 通过浏览器请求网关  网关由于没有匹配到选择器、路由规则、或者后端服务接口超时，返回异常信息在浏览器乱码。
![image](https://user-images.githubusercontent.com/27324381/102571541-afdc2380-4124-11eb-86bf-b27af0a3deea.png)

WebFluxResultUtils.result(final ServerWebExchange exchange, final Object result)
排出到 exchange.getResponse().getHeaders() 里面到ContentType == null 导致乱码。
重新设置下即可解决

**Comment by yu199195** [comment]
please in english, we will close it
