### ISSUE TITLE
Improve code coverage in soul-client-sofa

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#804]
- [x] SofaConfig @xwzwmt 
- [x] SofaServiceBeanPostProcessor @xwzwmt 

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by sydgeek** [comment]
take it

**Comment by HoldDie** [comment]
get SofaConfig

**Comment by HoldDie** [comment]
get SofaRpcExt

**Comment by Redick01** [comment]
get SofaConfig

**Comment by midnight2104** [comment]
get   MetaDataDTO

**Comment by xwzwmt** [comment]
get SofaServiceBeanPostProcessor
