### ISSUE TITLE
Improve code coverage listener in soul-admin

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#805]
- [ ] HttpLongPollingDataChangedListener  @xwzwmt 
- [x] WebsocketCollector  and  WebsocketDataChangedListener @wuudongdong 
- [x]  ZookeeperDataChangedListener @tyjwan 
- [ ] AbstractDataChangedListener @yiwenlong 
- [ ]  ApplicationStartListener @magicalxiaochen 
- [x]  DataChangedEventDispatcher @wyc192273

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by tyjwan** [comment]
get ZookeeperDataChangedListener

**Comment by wyc192273** [comment]
get DataChangedEventDispatcher

**Comment by xwzwmt** [comment]
get HttpLongPollingDataChangedListener

**Comment by wuudongdong** [comment]
get DataChangedEventDispatcher

**Comment by magicalxiaochen** [comment]
ApplicationStartListener

**Comment by wuudongdong** [comment]
get WebsocketCollector and WebsocketDataChangedListener

**Comment by wyc192273** [comment]
get AbstractDataChangedListener

**Comment by wuudongdong** [comment]
WebsocketCollector done.
