### ISSUE TITLE
The soul-admin default account in document(https://dromara.org/website/zh-cn/docs/soul/setup.html) is incorrect

### ISSUE THREAD

**Issue by 2YSP** [dromara/soul#822]
## Question
soul-admin.jar version is 2.2.1,and when I use the default password(admin/123456) to try to login,it alter the error message "the username or password is incorrect". 
I saw the password in database is jHcpKkiDbbQh7W7hh8yQSA==.
So I want to know the correct pwd thanks .

**Comment by dengliming** [comment]
Can you try the lastest master version?

**Comment by yu199195** [comment]
if you used 2.2.1  , you can init sql by master

**Comment by 2YSP** [comment]
> if you used 2.2.1 , you can init sql by master

Yes,I tried the init sql of master branch,and it does't work.

**Comment by yu199195** [comment]
> Yes,I tried the init sql of master branch,and it does't work.

you can not used init sql of master branch.

**Comment by 2YSP** [comment]
> > Yes,I tried the init sql of master branch,and it does't work.
> 
> you can not used init sql of master branch.

<img width="1013" alt="pic" src="https://user-images.githubusercontent.com/22067095/102783023-4d5d7e80-43d5-11eb-968f-433dcb723c8d.png">
<img width="835" alt="pic2" src="https://user-images.githubusercontent.com/22067095/102783055-56e6e680-43d5-11eb-91cd-2576dad2fb9f.png">
They are the same.

**Comment by dengliming** [comment]
Use `master ` `sources`.

**Comment by KevinClair** [comment]
Please check the file `application-local.yml` in sou-admin.

**Comment by 2YSP** [comment]
I have found the reason, the soul-admin.jar 2.2.1 is too old, package a new jar using code of master branch can solve this problem.
