### ISSUE TITLE
Is it necessary to do retry, when failure happens?

### ISSUE THREAD

**Issue by lmhmhl** [dromara/soul#831]
## Feature Request

We can combine Curcuit-Breaker and Retry in Resilizece4J to acquire high availability of gateway.

**Comment by dengliming** [comment]
Please describe it in more detail.

**Comment by lmhmhl** [comment]
> Please describe it in more detail.

Sorry,  I mean we can use R4J Retry module to accomplish this feature.

**Comment by yu199195** [comment]
you can pull request  to this feature.

**Comment by dengliming** [comment]
No progress now. Closing it and please feel free to reopen it if you have any question. Thanks.
