### ISSUE TITLE
Add test case for soul-plugin-httpclient

### ISSUE THREAD

**Issue by Trafalgar-YuI** [dromara/soul#837]
- [x] WebClientPlugin @Trafalgar-YuI 
- [x] WebClientReponsePlugin @Trafalgar-YuI 
- [ ] NettyHttpClientPlugin @Trafalgar-YuI 
- [ ] NettyClientReponsePlugin @Trafalgar-YuI

**Comment by coderlmm** [comment]
take NettyHttpClientPlugin

**Comment by Trafalgar-YuI** [comment]
@coderlmm Sorry, I forget to tag my name.
