### ISSUE TITLE
Some questions in hash load balance algorithm.

### ISSUE THREAD

**Issue by lmhmhl** [dromara/soul#862]
The hashloadbalance algorithm first uses the IP address of the gateway to calculate a hash value, and then traverses to calculate the hah value in the upstream list. The concurrencskiplistmap is used to ensure that the elements are sorted according to the hash value, and the first element larger than the hash value of the gateway IP is selected. However, if the hash values calculated by different upstreams are the same, because there is no conflict handling mechanism, the new value will replace the old one Although the probability of this situation is very small, it is possible. In other words, the hash algorithm can guarantee that the hash value of each calculation is different?

翻译：
hashloadbalance算法首先是使用网关的ip地址计算出一个hash值，然后遍历计算upstreamlist中的hah值，使用ConcurrentSkipListMap保证元素按照hash值进行排序，选择比网关ip的hash值大的第一个元素，但是如果不同的upstream计算出的hash值相同，由于没有冲突处理机制，新的值会把旧的值覆盖，虽然这种情况的概率很小，但是是可能发生的。或者说hash算法从根本上能保证每次计算的hash值都不同呢？

**Comment by yu199195** [comment]
There will be no hash conflicts

**Comment by lmhmhl** [comment]
Why not use ConcurrentHashMap, and every time pick the 

> There will be no hash conflicts

It exists in theory, but the probability is small, there should be a more elegant way, which needs further discussion

**Comment by lmhmhl** [comment]
> There will be no hash conflicts

Each upstream stream calculates 5 times of hash value, which reduces the probability of different upstream with the same hash value  being covered.

**Comment by yu199195** [comment]
you can provide pull request  to fix it
