### ISSUE TITLE
Add test  webFilter in Soul-web

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#867]
- [ ]  CrossFilter  @Trafalgar-YuI
- [ ]  FileSizeFilter  @hellboy0621 
- [ ]  WebSocketParamFilter  @marina432

**Comment by Trafalgar-YuI** [comment]
get CrossFilter

**Comment by marina432** [comment]
get WebSocketParamFilter

**Comment by yooryan** [comment]
get FileSizeFilter

**Comment by hellboy0621** [comment]
get FileSizeFilter

**Comment by hellboy0621** [comment]
> get FileSizeFilter

When I run the code bellow, the error occurs.
java.lang.AssertionError: expectation "expectComplete" failed (expected: onComplete(); actual: onError(java.lang.NullPointerException: The Mono returned by the supplier is null))

I need help.

`ServerWebExchange webExchange =
		MockServerWebExchange.from(MockServerHttpRequest
				.post("http://localhost:8080")
				.contentType(MediaType.TEXT_PLAIN)
				.contentLength(1)
				.body("a"));

ServerHttpRequest mutatedRequest = webExchange.getRequest().mutate().header(CONTENT_TYPE,
		String.valueOf(MULTIPART_FORM_DATA)).build();
webExchange = webExchange.mutate().request(mutatedRequest).build();

mutatedRequest = webExchange.getRequest().mutate().header(CONTENT_LENGTH,
		String.valueOf(10000)).build();
webExchange = webExchange.mutate().request(mutatedRequest).build();


WebFilterChain webFilterChain = mock(WebFilterChain.class);
when(webFilterChain.filter(webExchange)).thenReturn(Mono.empty());

FileSizeFilter fileSizeFilter = new FileSizeFilter(1);
Mono<Void> voidMono = fileSizeFilter.filter(webExchange, webFilterChain);
StepVerifier.create(voidMono).expectSubscription().verifyComplete();`

**Comment by HoldDie** [comment]
```java
when(webFilterChain.filter(webExchange)).thenReturn(Mono.empty());
```

replace with:

```java
import static org.mockito.ArgumentMatchers.any;
...
when(webFilterChain.filter(any())).thenReturn(Mono.empty());
```
-------
Because of the chain filter call in your filter.

```java
  return bodyInsert.insert(outputMessage, new BodyInserterContext())
              .then(Mono.defer(() -> {
                  ServerHttpRequest decorator = decorate(exchange, outputMessage);
                  return chain.filter(exchange.mutate().request(decorator).build());
  
              }));
```

**Comment by hellboy0621** [comment]
> ```java
> when(webFilterChain.filter(webExchange)).thenReturn(Mono.empty());
> ```
> 
> replace with:
> 
> ```java
> import static org.mockito.ArgumentMatchers.any;
> ...
> when(webFilterChain.filter(any())).thenReturn(Mono.empty());
> ```
> 
> Because of the chain filter call in your filter.
> 
> ```java
>   return bodyInsert.insert(outputMessage, new BodyInserterContext())
>               .then(Mono.defer(() -> {
>                   ServerHttpRequest decorator = decorate(exchange, outputMessage);
>                   return chain.filter(exchange.mutate().request(decorator).build());
>   
>               }));
> ```

got it, thank you.
