### ISSUE TITLE
add test handler in soul-web

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#869]
- [x] GlobalErrorHandler 
- [x] SoulWebHandler @FocusZhouGD

**Comment by Duelist-Fiora** [comment]
get

**Comment by FocusZhouGD** [comment]
get SoulWebHandle

**Comment by yangxing9** [comment]
i will do this job

**Comment by dengliming** [comment]
Done. Thanks to @yangxing9 and @FocusZhouGD
