### ISSUE TITLE
soul考虑过注册中心支持nacos吗

### ISSUE THREAD

**Issue by moutangyou** [Dromara/soul#91]
soul会考虑注册中心支持nacos，不单单使用zookeeper吗？

**Comment by yu199195** [comment]
zookeeper 只是同步数据的一种方式而已

**Comment by moutangyou** [comment]
是的，了解过这个源码，公司要求改用nacos，弃用zookeeper，如果要切换soul-admin可以不用动，覆盖即可，但是soul-web几乎每一个插件都要动，会不太好，后期也不考虑把这块儿独立出来，方便扩展啥的，仅使用zookeeper吗？

**Comment by yu199195** [comment]
no，现在2.0已经和zookeeper没有任何关系， 和nacos 也没有任何关系

**Comment by moutangyou** [comment]
没注意看2.0已经出来，先研究一下，谢谢

**Comment by inotgaoshou** [comment]
对应的文档有更新吗。
