### ISSUE TITLE
Rule Condition’s param not support HTTP Request Type Set!

### ISSUE THREAD

**Issue by yangzhiw** [dromara/soul#924]
## Feature Request

When setting the rule conditions, we will find that the uri will have the same request, but the request method is different. such as

- get one order info uri：/api/order/:id,requestType：GET
- delete one order uri：/api/order/:id，requestType：DELETE

But the current does not support setting the conditions of the request method:

![image](https://user-images.githubusercontent.com/13634974/103404080-4977ec00-4b8d-11eb-8473-a465d2d02a7e.png)

#### Describe the solution you'd like

1. Add requestType to param_tyep in the condition selection box, param_value is the request method, supporting GET, POST, PUT, DELETE, PATCH, etc.

2. Then the logic of request mode judgmentin in the AbstractMatchStrategyAdd class，The request method can be obtained at exchange.getRequest().getMethodValue()

**Comment by yu199195** [comment]
please in english， 

first， config one rule It is enough.

**Comment by yangzhiw** [comment]
> please in english，
> 
> first， config one rule It is enough.

Normally yes, but the same url will appear, but the request method is different；Like the example I said above, my current project has such a situation

**Comment by yu199195** [comment]
the same API ，have other HTTP method get or post？  if not use api gateway，you service how to support?

**Comment by yangzhiw** [comment]
> the same API ，have other HTTP method get or post？ if not use api gateway，you service how to support?
Yes, this situation is not common. It can generally be avoided by setting different urls. Let me give you an example in the soul-admin project, such as the queryRules method (if the parameters in the method are removed) and the createRule method in the RuleController class. They are the same URL, but the RequestMethod is different.

**Comment by yangzhiw** [comment]
> the same API ，have other HTTP method get or post？ if not use api gateway，you service how to support?

Yes, this situation is not common. It can generally be avoided by setting different urls. Let me give you an example in the soul-admin project, such as the queryRules method (if the parameters in the method are removed) and the createRule method in the RuleController class. They are the same URL, but the RequestMethod is different.

**Comment by yu199195** [comment]
@yangzhiw  we not provider this special fetrue

**Comment by yangzhiw** [comment]
Okay, let me write a Pull Request first。
