### ISSUE TITLE
Some thoughts about data sync

### ISSUE THREAD

**Issue by lmhmhl** [dromara/soul#928]
We can use java reaction programming model to do the whole data sync, thus we can use some reactive database like mongoDB or some relational reactive database middle ware like R2DBC to construct a pipeline from soul admin to soul gateway, when some data changed in soul admin database, the propagation of data changing will handled by soul gate way to maintain data consistency, however It seems like It is not doable based on current project, because the whole project is mature and It is  hard to test. I just wanna propose my perspective on data sync in soul.
BTW, java reactive programming is not the mainstream in china, and It is difficult to change the mindset of traditional Java. So Is it worth to spend time learning it?

**Comment by KevinClair** [comment]
The problem of data consistency exists all the time, but in my opinion, the final consistency can be achieved by soul. High performance requires sacrifice.

**Comment by yu199195** [comment]
Don't worry, Reactor  code is the future
