### ISSUE TITLE
the method PrometheusMetricsTrackerManager  stop() may throw a nullpointerexception

### ISSUE THREAD

**Issue by gaoweicong** [dromara/soul#934]
## Describe the bug

if we use a wrong address to initialize Prometheus HTTPServer(class PrometheusMetricsTrackerManager line 62), it may throw an IOException, that will cause HTTPServer has a null value. when we refresh the plugin monitor, the system will call a restart method (class MonitorPluginDataHandler line 66), that operation will cause an exception

## Environment

- Soul version(s): [e.g. 2.2.1]

## Steps to reproduce
1 create a wrong Prometheus socket address
2 sync plugin monitor
3 change the address to a correct one
4  sync plugin monitor

## Expected behavior

the monitor provide a new socket address

## Debug logs

throw a NullpointerException

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
@gaoweicong  Would you be interested in fixing it? It seems that you only need to add a check to see if the server is null when you call the stop method.
