### ISSUE TITLE
Hope to complete the validation exception information of dubbo,

### ISSUE THREAD

**Issue by lyj-stack** [dromara/soul#941]
For example: param1 cannot be null, and the maximum value of param2 cannot exceed 100.
The current exception message returned by Validation: detailMessage=javax.validation.ValidationException: cannot be null, and the maximum cannot exceed 100.
I hope that We can directly get the condensed message in the error of soulResult (e.g. param1 cannot be null, and the maximum value of param2 cannot exceed 100), instead of all the exception information.

I hope the author can pay attention to the problem or provide me with solutions.
Thanks a lot.

**Comment by KevinClair** [comment]
hello，it has been supported, but you have to `open` it,for example:
```java
@Service(validation = "soulValidation")
public class MainServiceImpl implements IMainService {

    @Override
    @SoulDubboClient(path = "/test", desc = "test method")
    public String test(@Valid HelloServiceRequest name) throws SoulException {
        if (true){
            throw new SoulException("Param binding error.");
        }
        return "Hello " + name.getName();
    }
}
```
* The request param
```java
public class HelloServiceRequest implements Serializable {

    private static final long serialVersionUID = -5968745817846710197L;

    @NotEmpty(message = "name cannot be empty")
    private String name;

    @NotNull(message = "age cannot be null")
    private Integer age;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}
```
* Send request
```java
{
    "name": ""
}
```
* Response
```java
{
    "code": 500,
    "message": "Internal Server Error",
    "data": "name cannot be empty,age cannot be null"
}
```
* The corresponding submission record is https://github.com/dromara/soul/pull/736#issue-539525762

**Comment by lyj-stack** [comment]
thanks ！

**Comment by lyj-stack** [comment]
I did as you said, but the information returned is not as shown in your example

{
    "code": 500,
    "message": "Internal Server Error",
    "data": "Failed to invoke the method $invoke in the service com.alibaba.dubbo.rpc.service.GenericService. Tried 3 times of the providers [192.168.1.89:20001] (1/1) from the registry localhost:2181 on the consumer 192.168.1.89 using the dubbo version 2.6.5. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://192.168.1.89:20001/la.newlife.sys.api.DemoClient?anyhost=true&application=soul_proxy&bean.name=ServiceBean:la.newlife.sys.api.DemoClient&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&interface=la.newlife.sys.api.DemoClient&loadbalance=random&methods=getName,sayHello,listPageDemos,getUser,pageHelperDemos&pid=9140&protocol=dubbo&register=true&register.ip=192.168.1.89&release=2.7.3&remote.timestamp=1609981763012&retries=2&side=consumer&timeout=5000&timestamp=1609982493647, cause: java.io.IOException: Response data error, expect Throwable, but get {suppressedExceptions=[], cause=(this Map), exceptionClass=javax.validation.ValidationException, stackTrace=[Ljava.lang.StackTraceElement;@2a267b30, detailMessage=javax.validation.ValidationException: companyId 不能为空,count 不能超过100\r\njavax.validation.ValidationException: companyId 不能为空,count 不能超过100\r\n\t
}
Did I neglect some configuration?
How can I condense the content of the “data” like your example?

**Comment by lyj-stack** [comment]
> hello，it has been supported, but you have to `open` it,for example:
> 
> ```java
> @Service(validation = "soulValidation")
> public class MainServiceImpl implements IMainService {
> 
>     @Override
>     @SoulDubboClient(path = "/test", desc = "test method")
>     public String test(@Valid HelloServiceRequest name) throws SoulException {
>         if (true){
>             throw new SoulException("Param binding error.");
>         }
>         return "Hello " + name.getName();
>     }
> }
> ```
> 
> * The request param
> 
> ```java
> public class HelloServiceRequest implements Serializable {
> 
>     private static final long serialVersionUID = -5968745817846710197L;
> 
>     @NotEmpty(message = "name cannot be empty")
>     private String name;
> 
>     @NotNull(message = "age cannot be null")
>     private Integer age;
> 
>     public String getName() {
>         return name;
>     }
> 
>     public void setName(String name) {
>         this.name = name;
>     }
> 
>     public Integer getAge() {
>         return age;
>     }
> 
>     public void setAge(Integer age) {
>         this.age = age;
>     }
> }
> ```
> 
> * Send request
> 
> ```java
> {
>     "name": ""
> }
> ```
> 
> * Response
> 
> ```java
> {
>     "code": 500,
>     "message": "Internal Server Error",
>     "data": "name cannot be empty,age cannot be null"
> }
> ```
> 
> * The corresponding submission record is [#736 (comment)](https://github.com/dromara/soul/pull/736#issue-539525762)

**Comment by KevinClair** [comment]
Please show me your `la.newlife.sys.api.DemoClient` class.

**Comment by lyj-stack** [comment]
import la.newlife.sys.api.DemoClient;
import la.newlife.sys.dto.DemoDTO;
import la.newlife.sys.dto.DemoRequest;
import la.newlife.sys.dto.GenericDemoResponse;
import la.newlife.sys.dto.ListDemoResponse;
import la.newlife.sys.model.DemoDO;
import la.newlife.sys.service.IDemoService;
import org.apache.dubbo.config.annotation.Service;
import org.dromara.soul.client.dubbo.common.annotation.SoulDubboClient;
import org.dromara.soul.common.exception.SoulException;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;

import javax.validation.Valid;
import java.util.List;

import static java.util.stream.Collectors.toList;

/**
 * @author colin
 * @date 2020/11/2.
 */
@Service(timeout = 5000,validation = "soulValidation")
public class DemoClientImpl implements DemoClient {

 

    @Override
    @SoulDubboClient(path = "/user/getId", desc = "获得用户详细")
    public String getUser(Integer id) {
        return "User:" + id;
    }

    @Override
    @SoulDubboClient(path = "/sayHello", desc = "demoSayHello")
    public GenericDemoResponse sayHello(@Valid DemoRequest demoRequest) throws SoulException{
        
        System.out.println("demoRequest = [" + demoRequest + "]");
        return new GenericDemoResponse("demo", null);
    }
    

}

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DemoRequest implements Serializable{
    @NotEmpty(message = "companyId不能为空")
    private String companyId;
    @NotBlank(message = "{message.name}")
    private String teamId;
    @Max(value = 100,message = "count不能超过100")
    private int count;
}

**Comment by lyj-stack** [comment]
solved.
because the dubbo in the soul-bootstrap depends on Alibaba dubbo instead of Apache dubbo.
Thanks for your help
