### ISSUE TITLE
Why does the divide plugin automatically remove the first prefix

### ISSUE THREAD

**Issue by Queeee** [dromara/soul#942]
Version: 2.2.1
Description: When I use divide plugin, it will automatically remove the first prefix in uri. Selector and rule as shown in the figure below, when I request /api/client/** it will be forwarded to  /client/** instead of /api/client/**，my question is, why is the first prefix removed automatically and not stated in the official documentation？
![image](https://user-images.githubusercontent.com/28085221/103740272-e6c19d00-5031-11eb-8933-d30bd1e2808e.png)
![image](https://user-images.githubusercontent.com/28085221/103740300-f214c880-5031-11eb-9e58-4dd75f13e7be.png)

When I type **http://localhost:8081/api/client/health** it will be forwarded to **http://127.0.0.1:8080/client/health** instead of 
**http://127.0.0.1:8080/api/client/health**
![image](https://user-images.githubusercontent.com/28085221/103740475-3d2edb80-5032-11eb-8458-1501b41a512e.png)
![image](https://user-images.githubusercontent.com/28085221/103740443-2e482900-5032-11eb-968c-03287cde135c.png)

**Comment by yu199195** [comment]
now , soul need  context path to divide http services,  just like nginx.

**Comment by Queeee** [comment]
Thank you, and hope you can supplement the documentation
