### ISSUE TITLE
To optimize the soul test class

### ISSUE THREAD

**Issue by yu199195** [dromara/soul#945]
Hi all guys 

Over the past month,The community has done a lot of work on test cases.  now,  we shoud optimize the soul test class.

optimize  rules:

1. assertEquals()  must be Modified to assertThat()
2. must use inline import static class in test case  , just like `import static org.mockito.Mockito.mock;`,  `import static org.junit.Assert.assertTrue;`
3. Delete unnecessary blank lines
4. Optimize the java doc
5. There should be no obvious yellow warning of IDEA
6. remove final variable Inside the method
7. use constants for all string variables
8. English words should be expressed clearly. for example :  `setUp` maybe to `setup`
9.  all test class maybe add final modifier

Task List ：

- [ ] soul-admin  @Trafalgar-YuI
- [x] soul-boostrap  @sccauxupei
- [x] soul-client  @HoldDie
- [ ] soul-common @magicalxiaochen
- [x] soul-metrics  @xxl115
- [ ] soul-plugin @Redick01
- [ ] soul-spi @abysscat-yj 
- [ ] soul-spring-boot-starter @strawberry-crisis
- [x] soul-sync-data-center @vinceDa
- [ ] soul-web @FocusZhouGD

**Comment by Trafalgar-YuI** [comment]
get soul-admin

**Comment by magicalxiaochen** [comment]
get soul-common

**Comment by HoldDie** [comment]
get  soul-client

**Comment by strawberry-crisis** [comment]
assign soul-spring-boot-starter to me plz

**Comment by abysscat-yj** [comment]
get soul-spi

**Comment by lmhmhl** [comment]
get soul-sync-data-center

**Comment by Redick01** [comment]
get soul-plugin

**Comment by xxl115** [comment]
soul-metrics

**Comment by branchen** [comment]
get soul-boostrap

**Comment by sccauxupei** [comment]
get soul-boostrap

**Comment by vinceDa** [comment]
get soul-sync-data-center

**Comment by lmhmhl** [comment]
?

**Comment by vinceDa** [comment]
> ?

看岔了  我删了

**Comment by lmhmhl** [comment]
> > ?
> 
> 看岔了 我删了

If u still wanna do it, we can  optimize the soul test class in soul-sync-data-center together, I can do the first 2 model `http` and `nacos`, the rest two is yours.

**Comment by vinceDa** [comment]
> > > ?
> > 
> > 
> > 看岔了 我删了
> 
> If u still wanna do it, we can optimize the soul test class in soul-sync-data-center together, I can do the first 2 model `http` and `nacos`, the rest two is yours.

NoNoNo, it's yours, my bad; i can do this next time, thank you！
