### ISSUE TITLE
楼主每个调用为什么要删除掉host头

### ISSUE THREAD

**Issue by liuzhebaba** [Dromara/soul#95]
![image](https://user-images.githubusercontent.com/22785707/61618527-a173a900-ac9f-11e9-9be1-68db091b1ecf.png)
这里有什么特殊作用么？没有的话，我是否可以去掉

**Comment by michjony** [comment]
这行代码的作用是：这里移除的是请求网关的url中的host，网关需要将这个请求转发给后台的服务，需要移除原始链接中的host，应该是不能删除的

**Comment by liuzhebaba** [comment]
这个host是原始的requestHeader的host，后台服务是有可能会使用到的，删除了会有影响，而不删除其实目前来看是不会有什么影响的
