### ISSUE TITLE
optimize soul-client-alibaba-dubbo 

### ISSUE THREAD

**Issue by xiangyang-gao** [dromara/soul#967]
描述：
AlibabaDubboServiceBeanPostProcessor 的onApplicationEvent （finalContextRefreshedEvent contextRefreshedEvent）  
if (Objects.nonNull(contextRefreshedEvent.getApplicationContext().getParent())) {
            return;
        }
此行代码表达是：Spring容器初始化完成会触发该事件,判断时为了防止重复触发

此处属于治标不治本，优化一下

**Comment by xiangyang-gao** [comment]
分给我

**Comment by hebaceous** [comment]
Why not use ApplicationStartedEvent？
