### ISSUE TITLE
Little question for soul-bootstrap pom.xml

### ISSUE THREAD

**Issue by lxl910128** [dromara/soul#975]
## Question

In soul-bootstrap pom.xml 
![image](https://rfc2616.oss-cn-beijing.aliyuncs.com/blog/bug-tmp.png)

I think soul-spring-boot-starter-plugin-httpclient It's a very important plugin. 

It shouldn't put in 
 < ! --if you use http proxy start this -- >
  ………………
  < ! --if you use http proxy end this -- >

Because For beginners, it may be commented out together with plugin-divide. 

so I think It's should be move to other place.

**Comment by dengliming** [comment]
I think  `soul-bootstrap` is the startup project that users can refer to. The recommendation is to customize your own gateway entry.

**Comment by lxl910128** [comment]
When I customize my own gateway entry , I delete http client and divide together. Then soul can not work, so I think other people maybe delete too. in my opinion , http client is belong to divide, and divide is optional.
