### ISSUE TITLE
Failed to register interface using SpringBoot 1.5X

### ISSUE THREAD

**Issue by baijuexzz** [dromara/soul#988]
When using SpringBoot 1.5X for interface registration, there is an abstract method error problem. The reason is that springmvc-client is compiled based on SpringBoot2.X, and the implemented BeanPostProcessor interface is modified by default in the new version, but it must be mandatory in SpringBoot1.5X Realize, cause the error.

**Comment by yu199195** [comment]
can you show error?

**Comment by baijuexzz** [comment]
> 
引用的地址为<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>soul-spring-boot-starter-client-springmvc</artifactId>
			<version>2.2.1</version>
		</dependency>

**Comment by baijuexzz** [comment]
> 引用的地址为<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>soul-spring-boot-starter-client-springmvc</artifactId>
			<version>2.2.1</version>
		</dependency>

**Comment by baijuexzz** [comment]
> can you show error?

The referenced address is < dependency >
< groupid > or. Dromara </groupId >
< artifactId > soul-spring-boot-starter-client-spring MVC </artifactId >
< version > 2.2.1 </version >
Dependency >

**Comment by baijuexzz** [comment]
> can you show error?
The problem is that the “Beanpostprocessor” is in Spring 5. Version X provides the default ‘default’ method, which is based on Spring 4. X does not provide an implementation of default。For some reason, I can’t reproduce
![image](https://user-images.githubusercontent.com/48422218/104816064-a34a0880-5853-11eb-91c4-d52d128a7c8e.png)

**Comment by baijuexzz** [comment]
> can you show error?
![image](https://user-images.githubusercontent.com/48422218/104816574-1608b300-5857-11eb-803c-419213d86ab5.png)
![image](https://user-images.githubusercontent.com/48422218/104816569-130dc280-5857-11eb-8094-1ee750dbe612.png)
![image](https://user-images.githubusercontent.com/48422218/104816578-186b0d00-5857-11eb-95ea-77b1e95eb229.png)

**Comment by dengliming** [comment]
Can you try to remove `@NonNull` annotation?

**Comment by jcmob-afj** [comment]
SpringBoot1.X  are not compatible SpringBoot2.X ;
If your project needs to be introduced dependency <soul-spring-boot-starter-client-springmvc> and the SpringBoot version of your project is 1.x , sorry , You cannot use this dependency ;
You can use it by copying the soul-client --> soul-client-http --> soul-client-springmvc  project into your own project，so you can use @SoulSpringMvcClient .
