### ISSUE TITLE
soul-admin metadata sync to soul-bootstrap NPE 

### ISSUE THREAD

**Issue by Silencesk** [dromara/soul#994]
## Describe the bug

If my metadata has some interface which is no parameter. then i click syncData, the soul-boostrap will throw NPE.

## Environment

- Soul version(s): 2.2.1

## Steps to reproduce
1. click SynchronousData
![image](https://user-images.githubusercontent.com/4735494/104844703-b40a8500-590c-11eb-8e41-4b19595a92d1.png)
2. soul-bootstrap NPE
![image](https://user-images.githubusercontent.com/4735494/104844760-fdf36b00-590c-11eb-893f-e85d2283014c.png)

## Debug logs
![image](https://user-images.githubusercontent.com/4735494/104844831-5296e600-590d-11eb-844e-8fbb6fd31c77.png)

**Comment by dengliming** [comment]
Can you fix it?

**Comment by Silencesk** [comment]
@yu199195 mr mao, i can fix it. assign to me

**Comment by Silencesk** [comment]
i can

**Comment by Silencesk** [comment]
deadline: 2021-01-18
